import { readFileSync, writeFileSync, existsSync } from 'fs';
import { ROOT } from './utils.js';

// =============================================================================
// Types
// =============================================================================

export type FontSource = 'google-fonts' | 'system' | 'asset' | 'custom-cdn';

export interface FontMeta {
  $description?: string;
  source: FontSource;
  weights?: number[];
  styles?: string[];
  fallback: string;
  /** Platforms where this font is pre-installed (e.g. ["android"]). */
  platform?: string[];
  /** URL for custom-cdn fonts. */
  url?: string;
}

// =============================================================================
// Loader
// =============================================================================

export function loadFontRegistry(): Record<string, FontMeta> {
  const path = `${ROOT}/sources/core/font-registry.json`;
  if (!existsSync(path)) {
    console.warn('  [font-registry] sources/core/font-registry.json not found — skipping.');
    return {};
  }
  const raw = JSON.parse(readFileSync(path, 'utf-8')) as { fontRegistry: Record<string, FontMeta> };
  return raw.fontRegistry ?? {};
}

// =============================================================================
// Dart: BTechFontRegistry
// =============================================================================

/**
 * Generates packages/tokens-dart/lib/src/typography/font_registry.dart.
 *
 * Exports BTechFontRegistry with:
 *   isGoogleFont(family)  — decides GoogleFonts.getFont() vs TextStyle(fontFamily:)
 *   isSystemFont(family)  — pre-installed on the OS, no download needed
 *   fallbackFor(family)   — CSS-style fallback string for informational use
 */
export function generateFlutterFontRegistry(
  outDir: string,
  registry: Record<string, FontMeta>,
): void {
  const HEADER = [
    '// AUTO-GENERATED by @btech/design-system — do not edit manually.',
    '// Run `pnpm generate` to regenerate from sources/core/font-registry.json.',
    '',
    '// ignore_for_file: lines_longer_than_80_chars',
    '',
  ].join('\n');

  const googleFonts = Object.entries(registry)
    .filter(([, m]) => m.source === 'google-fonts')
    .map(([name]) => name);

  const systemFonts = Object.entries(registry)
    .filter(([, m]) => m.source === 'system')
    .map(([name]) => name);

  const L: string[] = [
    HEADER,
    "import 'package:flutter/material.dart';",
    '',
    '/// Font source registry — generated from sources/core/font-registry.json.',
    '///',
    '/// Tells each platform how to load a font family:',
    '///   google-fonts → use GoogleFonts.getFont() (downloaded on demand)',
    '///   system       → use TextStyle(fontFamily:) (OS resolves natively)',
    '///   asset        → use TextStyle(fontFamily:) (Flutter asset pipeline)',
    '///',
    '/// ```dart',
    "/// import 'package:google_fonts/google_fonts.dart';",
    '///',
    "/// TextStyle _build(String family) =>",
    "///   BTechFontRegistry.isGoogleFont(family)",
    "///       ? GoogleFonts.getFont(family, fontSize: 16)",
    "///       : TextStyle(fontFamily: family, fontSize: 16);",
    '/// ```',
    'abstract class BTechFontRegistry {',
    '',
    '  /// Font families available via the google_fonts Flutter package.',
    '  static const Set<String> googleFonts = {',
    ...googleFonts.map(name => `    '${name}',`),
    '  };',
    '',
    '  /// Font families pre-installed on the OS — no network fetch required.',
    '  static const Set<String> systemFonts = {',
    ...systemFonts.map(name => `    '${name}',`),
    '  };',
    '',
    '  /// CSS-style fallback stacks for each registered family.',
    '  static const Map<String, String> fallbacks = {',
    ...Object.entries(registry).map(([name, m]) => `    '${name}': '${m.fallback.replace(/'/g, "\\'")}',`),
    '  };',
    '',
    '  /// Returns true if [family] can be loaded via the google_fonts package.',
    '  static bool isGoogleFont(String family) => googleFonts.contains(family);',
    '',
    '  /// Returns true if [family] is pre-installed on the OS.',
    '  static bool isSystemFont(String family) => systemFonts.contains(family);',
    '',
    "  /// Returns the CSS fallback stack for [family], or 'sans-serif' if unknown.",
    "  static String fallbackFor(String family) => fallbacks[family] ?? 'sans-serif';",
    '}',
    '',
  ];

  writeFileSync(`${outDir}/font_registry.dart`, L.join('\n') + '\n');
}

// =============================================================================
// Web: font-registry.ts
// =============================================================================

/**
 * Generates packages/tokens-web/src/typography/font-registry.ts.
 *
 * Exports:
 *   FontMeta / FontSource  — types
 *   fontRegistry           — full metadata map (name → FontMeta)
 *   isGoogleFont(family)   — true if loaded from Google Fonts CDN
 *   buildGoogleFontsUrl()  — <link href="..."> URL covering all google-fonts entries
 *   buildGoogleFontsCssImport() — @import rule string for stylesheet prepending
 */
export function generateWebFontRegistry(
  outDir: string,
  registry: Record<string, FontMeta>,
): void {
  const HEADER = [
    '// AUTO-GENERATED by @btech/design-system — do not edit manually.',
    '// Run `pnpm generate` to regenerate from sources/core/font-registry.json.',
    '',
  ].join('\n');

  const registryLines = Object.entries(registry).map(([name, meta]) => {
    const parts: string[] = [`source: '${meta.source}'`];
    if (meta.weights?.length)  parts.push(`weights: [${meta.weights.join(', ')}]`);
    if (meta.styles?.length)   parts.push(`styles: [${meta.styles.map(s => `'${s}'`).join(', ')}]`);
    parts.push(`fallback: '${meta.fallback.replace(/'/g, "\\'")}'`);
    if (meta.platform?.length) parts.push(`platform: [${meta.platform.map(p => `'${p}'`).join(', ')}]`);
    if (meta.url)              parts.push(`url: '${meta.url}'`);
    return `  '${name}': { ${parts.join(', ')} },`;
  });

  const L: string[] = [
    HEADER,
    "export type FontSource = 'google-fonts' | 'system' | 'asset' | 'custom-cdn';",
    '',
    'export interface FontMeta {',
    '  source: FontSource;',
    '  weights?: number[];',
    '  styles?: string[];',
    '  fallback: string;',
    '  /** Platforms where this is a system font (e.g. ["android"]). */',
    '  platform?: string[];',
    '  /** CDN URL for custom-cdn fonts. */',
    '  url?: string;',
    '}',
    '',
    '/**',
    ' * Registry of every font family used in the BTech design system.',
    ' * Generated from sources/core/font-registry.json.',
    ' *',
    ' * Use this to drive `<link>` injection, @font-face rules,',
    ' * or conditional font-loading logic in React / Vue apps.',
    ' *',
    " * @example React",
    " * import { buildGoogleFontsUrl } from '@btech/tokens';",
    " * <link rel='stylesheet' href={buildGoogleFontsUrl()} />",
    ' *',
    " * @example Vue (with @vueuse/head)",
    " * import { buildGoogleFontsUrl } from '@btech/tokens';",
    " * useHead({ link: [{ rel: 'stylesheet', href: buildGoogleFontsUrl() }] });",
    ' */',
    'export const fontRegistry: Record<string, FontMeta> = {',
    ...registryLines,
    '};',
    '',
    '/** Returns true if [family] should be loaded from the Google Fonts CDN. */',
    'export function isGoogleFont(family: string): boolean {',
    "  return fontRegistry[family]?.source === 'google-fonts';",
    '}',
    '',
    '/**',
    ' * Builds a Google Fonts CDN URL covering all `google-fonts` entries in the registry.',
    ' * Each family includes all registered weights and italic variants automatically.',
    ' */',
    'export function buildGoogleFontsUrl(): string {',
    '  const families = Object.entries(fontRegistry)',
    "    .filter(([, meta]) => meta.source === 'google-fonts')",
    '    .map(([name, meta]) => {',
    "      const weights = (meta.weights ?? [400]).join(';');",
    "      const hasItalic = meta.styles?.includes('italic') ?? false;",
    '      const encoded = encodeURIComponent(name);',
    '      return hasItalic',
    "        ? `family=${encoded}:ital,wght@0,${weights};1,${weights}`",
    "        : `family=${encoded}:wght@${weights}`;",
    '    });',
    "  return `https://fonts.googleapis.com/css2?${families.join('&')}&display=swap`;",
    '}',
    '',
    '/**',
    ' * Returns a CSS `@import` statement for all Google Fonts in the registry.',
    ' * Prepend this to your global stylesheet or inject via a `<style>` tag.',
    ' *',
    ' * @example',
    " * import { buildGoogleFontsCssImport } from '@btech/tokens';",
    " * const fullCss = buildGoogleFontsCssImport() + existingStylesheet;",
    ' */',
    'export function buildGoogleFontsCssImport(): string {',
    "  return `@import url('${buildGoogleFontsUrl()}');\\n`;",
    '}',
    '',
  ];

  writeFileSync(`${outDir}/font-registry.ts`, L.join('\n') + '\n');
}

// =============================================================================
// CSS: prepend @import to styles.css
// =============================================================================

/**
 * Prepends a Google Fonts @import to packages/tokens-web/dist/styles.css.
 * Idempotent — skips if the import is already present.
 */
export function prependGoogleFontsCssImport(
  cssPath: string,
  registry: Record<string, FontMeta>,
): void {
  const googleEntries = Object.entries(registry).filter(([, m]) => m.source === 'google-fonts');
  if (googleEntries.length === 0) return;

  const families = googleEntries.map(([name, meta]) => {
    const weights = (meta.weights ?? [400]).join(';');
    const hasItalic = meta.styles?.includes('italic') ?? false;
    const encoded = encodeURIComponent(name);
    return hasItalic
      ? `family=${encoded}:ital,wght@0,${weights};1,${weights}`
      : `family=${encoded}:wght@${weights}`;
  });

  const importLine = `@import url('https://fonts.googleapis.com/css2?${families.join('&')}&display=swap');\n\n`;

  const existing = readFileSync(cssPath, 'utf-8');
  if (existing.startsWith('@import url(')) return; // already present

  writeFileSync(cssPath, importLine + existing, 'utf-8');
  console.log(`  CSS @import  — Google Fonts prepended to styles.css (${googleEntries.length} families)`);
}
