# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.
"""BTech design tokens for Python UI consumers (Streamlit, Gradio, NiceGUI, ...).

Public surface:
  * ``BTechColor``, ``BTechSpacing``, ``BTechRadius``, ``BTechStroke``,
    ``BTechFont``, ``BTechShadow`` — token values.
  * ``BTechColorBrandPrimary`` / ``BTechColorBrandSecondary`` —
    primitive brand color ramps (50..900), tenant-overridable.
  * ``set_mode('light' | 'dark')`` — toggle ``BTechColor``’s mode-aware accessors.
    Module-level state; safe for single-process UI apps and notebooks.
  * ``LIGHT``, ``DARK`` — namespace constants for deterministic side-by-side
    use (tests, settings preview, multi-user-deployed Streamlit dashboards).
  * ``to_css(mode, selector)`` — CSS custom property block for raw injection.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Literal

from . import _state
from .color import (
    BTechColor,
    LIGHT_COLOR,
    DARK_COLOR,
    _ColorRootStatic,
)
from .spacing import BTechSpacing
from .radius import BTechRadius
from .stroke import BTechStroke
from .typography import (
    BTechFont,
    BTechFontFamily,
    BTechFontSize,
    BTechFontWeight,
    BTechLineHeight,
)
from .shadow import BTechShadow
from .swatches import (
    BTechColorBrandPrimary,
    BTechColorBrandSecondary,
)
from .helpers import to_css


__all__ = [
    'BTechColor',
    'BTechSpacing',
    'BTechRadius',
    'BTechStroke',
    'BTechFont',
    'BTechFontFamily',
    'BTechFontSize',
    'BTechFontWeight',
    'BTechLineHeight',
    'BTechShadow',
    'BTechColorBrandPrimary',
    'BTechColorBrandSecondary',
    'LIGHT',
    'DARK',
    'set_mode',
    'to_css',
]


def set_mode(mode: Literal['light', 'dark']) -> None:
    """Set the active mode for ``BTechColor`` accessors.

    Module-level state. Fine for single-process UI apps (notebooks, local
    Streamlit, desktop tools). For multi-user-deployed dashboards where each
    user may want a different mode, use the ``LIGHT`` / ``DARK`` namespace
    constants instead — they don’t read shared state.
    """
    if mode not in ('light', 'dark'):
        raise ValueError(f"mode must be 'light' or 'dark', got {mode!r}")
    _state._mode = mode


@dataclass(frozen=True, slots=True)
class _Namespace:
    color: _ColorRootStatic


LIGHT: _Namespace = _Namespace(color=LIGHT_COLOR)
DARK: _Namespace = _Namespace(color=DARK_COLOR)
