# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.

from __future__ import annotations
from dataclasses import dataclass
from . import _data, _state

@dataclass(frozen=True, slots=True)
class BTechColorBg:
    inverse: str
    overlay: str
    primary: str
    secondary: str
    subtle: str
    subtler: str
    subtlest: str
    tertiary: str

@dataclass(frozen=True, slots=True)
class BTechColorBorder:
    disabled: str
    inverse: str
    primary: str
    secondary: str
    tertiary: str

@dataclass(frozen=True, slots=True)
class BTechColorBrand:
    primary: str
    primary_bold: str
    primary_subtle: str
    secondary: str
    secondary_bold: str
    secondary_subtle: str

@dataclass(frozen=True, slots=True)
class BTechColorExt:
    error: str
    error_bold: str
    error_subtle: str
    error_subtler: str
    info: str
    info_bold: str
    info_subtle: str
    info_subtler: str
    success: str
    success_bold: str
    success_subtle: str
    success_subtler: str
    warning: str
    warning_bold: str
    warning_subtle: str
    warning_subtler: str

@dataclass(frozen=True, slots=True)
class BTechColorIcon:
    disabled: str
    error: str
    info: str
    inverse: str
    link: str
    primary: str
    secondary: str
    success: str
    tertiary: str
    warning: str

@dataclass(frozen=True, slots=True)
class BTechColorText:
    disabled: str
    error: str
    info: str
    inverse: str
    link: str
    primary: str
    secondary: str
    success: str
    tertiary: str
    warning: str

_LIGHT_BG = BTechColorBg(
    inverse='#181c20',
    overlay='#181c20cc',
    primary='#ffffff',
    secondary='#ecedee',
    subtle='#f4f5f6',
    subtler='#dbdde1',
    subtlest='#C1C6CD',
    tertiary='#64748b',
)
_DARK_BG = BTechColorBg(
    inverse='#ecedee',
    overlay='#181c20cc',
    primary='#181c20',
    secondary='#3c4450',
    subtle='#292f37',
    subtler='#505c6d',
    subtlest='#64748B',
    tertiary='#ecedee',
)

_LIGHT_BORDER = BTechColorBorder(
    disabled='#c1c6cd',
    inverse='#292f37',
    primary='#dbdde1',
    secondary='#98a2b0',
    tertiary='#c1c6cd',
)
_DARK_BORDER = BTechColorBorder(
    disabled='#3c4450',
    inverse='#ecedee',
    primary='#505c6d',
    secondary='#64748b',
    tertiary='#dbdde1',
)

_LIGHT_BRAND = BTechColorBrand(
    primary='#08a94c',
    primary_bold='#0a853e',
    primary_subtle='#f0f8f4',
    secondary='#0d9488',
    secondary_bold='#0d766c',
    secondary_subtle='#f0f8f7',
)
_DARK_BRAND = BTechColorBrand(
    primary='#41e084',
    primary_bold='#08a94c',
    primary_subtle='#072d17',
    secondary='#3ed8ca',
    secondary_bold='#0d766c',
    secondary_subtle='#082a27',
)

_LIGHT_EXT = BTechColorExt(
    error='#ef4444',
    error_bold='#d81818',
    error_subtle='#f0d9d9',
    error_subtler='#f6eaea',
    info='#0ea5e9',
    info_bold='#0f81b4',
    info_subtle='#d0e4ed',
    info_subtler='#e7f0f4',
    success='#08a94c',
    success_bold='#0a853e',
    success_subtle='#c5ead5',
    success_subtler='#e2f3e9',
    warning='#f59e0b',
    warning_bold='#bd7c0c',
    warning_subtle='#efe3d0',
    warning_subtler='#f5f0e7',
)
_DARK_EXT = BTechColorExt(
    error='#e88d8d',
    error_bold='#f9f2f2',
    error_subtle='#991515',
    error_subtler='#ef4444',
    info='#69bee4',
    info_bold='#f1f6f9',
    info_subtle='#0f5e81',
    info_subtler='#0ea5e9',
    success='#41e084',
    success_bold='#f0f8f4',
    success_subtle='#0a632f',
    success_subtler='#08a94c',
    warning='#e8ba6c',
    warning_bold='#f9f6f1',
    warning_subtle='#885a0d',
    warning_subtler='#f59e0b',
)

_LIGHT_ICON = BTechColorIcon(
    disabled='#c1c6cd',
    error='#991515',
    info='#0f5e81',
    inverse='#ffffff',
    link='#0d766c',
    primary='#181c20',
    secondary='#64748b',
    success='#0a632f',
    tertiary='#98a2b0',
    warning='#885a0d',
)
_DARK_ICON = BTechColorIcon(
    disabled='#505c6d',
    error='#ebbdbd',
    info='#aad4e7',
    inverse='#181c20',
    link='#0d9488',
    primary='#ecedee',
    secondary='#98a2b0',
    success='#94e2b5',
    tertiary='#64748b',
    warning='#e9d2ab',
)

_LIGHT_TEXT = BTechColorText(
    disabled='#c1c6cd',
    error='#991515',
    info='#0f5e81',
    inverse='#ffffff',
    link='#0d766c',
    primary='#181c20',
    secondary='#64748b',
    success='#0a632f',
    tertiary='#98a2b0',
    warning='#885a0d',
)
_DARK_TEXT = BTechColorText(
    disabled='#505c6d',
    error='#ebbdbd',
    info='#aad4e7',
    inverse='#181c20',
    link='#0d9488',
    primary='#ecedee',
    secondary='#98a2b0',
    success='#94e2b5',
    tertiary='#64748b',
    warning='#e9d2ab',
)

@dataclass(frozen=True, slots=True)
class _ColorRootStatic:
    bg: BTechColorBg
    border: BTechColorBorder
    brand: BTechColorBrand
    ext: BTechColorExt
    icon: BTechColorIcon
    text: BTechColorText

LIGHT_COLOR = _ColorRootStatic(
    bg=_LIGHT_BG,
    border=_LIGHT_BORDER,
    brand=_LIGHT_BRAND,
    ext=_LIGHT_EXT,
    icon=_LIGHT_ICON,
    text=_LIGHT_TEXT,
)
DARK_COLOR = _ColorRootStatic(
    bg=_DARK_BG,
    border=_DARK_BORDER,
    brand=_DARK_BRAND,
    ext=_DARK_EXT,
    icon=_DARK_ICON,
    text=_DARK_TEXT,
)

class _ColorAccessor:
    """Mode-aware singleton: reads `_state._mode` at attribute access time.

    Use `BTechColor.background.primary` for ergonomic access that follows
    `set_mode()`. For deterministic / no-global-state access (tests, side-by-
    side previews, multi-user-deployed Streamlit), use the `LIGHT` / `DARK`
    namespace constants exported from the package root instead.
    """
    __slots__ = ()

    @property
    def bg(self) -> BTechColorBg:
        return _LIGHT_BG if _state._mode == 'light' else _DARK_BG

    @property
    def border(self) -> BTechColorBorder:
        return _LIGHT_BORDER if _state._mode == 'light' else _DARK_BORDER

    @property
    def brand(self) -> BTechColorBrand:
        return _LIGHT_BRAND if _state._mode == 'light' else _DARK_BRAND

    @property
    def ext(self) -> BTechColorExt:
        return _LIGHT_EXT if _state._mode == 'light' else _DARK_EXT

    @property
    def icon(self) -> BTechColorIcon:
        return _LIGHT_ICON if _state._mode == 'light' else _DARK_ICON

    @property
    def text(self) -> BTechColorText:
        return _LIGHT_TEXT if _state._mode == 'light' else _DARK_TEXT

BTechColor: _ColorAccessor = _ColorAccessor()
