# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.
from __future__ import annotations
from typing import Literal

from . import _data


def to_css(mode: Literal['light', 'dark'] = 'light', selector: str = ':root') -> str:
    """Render tokens as a CSS custom property block.

    Examples:
        Streamlit:
            st.markdown(f"<style>{to_css()}</style>", unsafe_allow_html=True)
        NiceGUI:
            ui.add_css(to_css())
        Gradio:
            gr.HTML(f"<style>{to_css()}</style>")

    Variable names follow ``--btech-{group}-{name}`` with snake_case keys
    converted to kebab-case (e.g. ``color.background.primary_hover`` becomes
    ``--btech-color-background-primary-hover``). These names are intentionally
    simpler than the @btech/tokens CSS variables (which apply category renames
    such as stroke -> border); use ``BTechColor.background.primary`` etc. for
    cross-platform value parity.
    """
    if mode not in ('light', 'dark'):
        raise ValueError(f"mode must be 'light' or 'dark', got {mode!r}")

    color_map = _data.COLOR_LIGHT if mode == 'light' else _data.COLOR_DARK
    lines: list[str] = [f"{selector} {{"]

    for group, items in color_map.items():
        group_kebab = group.replace('_', '-')
        for name, value in items.items():
            name_kebab = name.replace('_', '-')
            lines.append(f"  --btech-color-{group_kebab}-{name_kebab}: {value};")

    for name, value in _data.SPACING.items():
        lines.append(f"  --btech-spacing-{name.replace('_', '-')}: {value}px;")

    for name, value in _data.RADIUS.items():
        lines.append(f"  --btech-radius-{name.replace('_', '-')}: {value}px;")

    for name, value in _data.STROKE.items():
        lines.append(f"  --btech-stroke-{name.replace('_', '-')}: {value}px;")

    for name, value in _data.FONT_FAMILIES.items():
        lines.append(f"  --btech-font-family-{name.replace('_', '-')}: {value};")

    for name, value in _data.FONT_SIZES.items():
        lines.append(f"  --btech-font-size-{name.replace('_', '-')}: {value}px;")

    for name, value in _data.FONT_WEIGHTS.items():
        lines.append(f"  --btech-font-weight-{name.replace('_', '-')}: {value};")

    for name, value in _data.LINE_HEIGHTS.items():
        lines.append(f"  --btech-line-height-{name.replace('_', '-')}: {value};")

    lines.append('}')
    return '\n'.join(lines)
