# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.

from __future__ import annotations
from dataclasses import dataclass
from typing import TypedDict

class ShadowLayer(TypedDict):
    """One layer of a shadow definition.

    Compose into a CSS box-shadow string with:
        ' '.join(...) per layer, ', '.join(layers).
    """
    color: str
    offset_x: float
    offset_y: float
    blur: float
    spread: float
    inset: bool

@dataclass(frozen=True, slots=True)
class BTechShadowButton:
    pressed: list[ShadowLayer]

@dataclass(frozen=True, slots=True)
class BTechShadowElevation:
    lg: list[ShadowLayer]
    md: list[ShadowLayer]
    sm: list[ShadowLayer]
    xl: list[ShadowLayer]
    xs: list[ShadowLayer]

@dataclass(frozen=True, slots=True)
class BTechShadowTable:
    left: list[ShadowLayer]
    right: list[ShadowLayer]

_BUTTON = BTechShadowButton(
    pressed=[
        {
            'color': 'rgba(0,0,0,0.25)',
            'offset_x': 0,
            'offset_y': 4,
            'blur': 4,
            'spread': 0,
            'inset': True,
        },
    ],
)

_ELEVATION = BTechShadowElevation(
    lg=[
        {
            'color': 'rgba(0,0,0,0.05)',
            'offset_x': 0,
            'offset_y': 4,
            'blur': 6,
            'spread': -4,
            'inset': False,
        },
        {
            'color': 'rgba(0,0,0,0.10)',
            'offset_x': 0,
            'offset_y': 10,
            'blur': 15,
            'spread': -3,
            'inset': False,
        },
    ],
    md=[
        {
            'color': 'rgba(0,0,0,0.06)',
            'offset_x': 0,
            'offset_y': 2,
            'blur': 4,
            'spread': -2,
            'inset': False,
        },
        {
            'color': 'rgba(0,0,0,0.10)',
            'offset_x': 0,
            'offset_y': 4,
            'blur': 6,
            'spread': -1,
            'inset': False,
        },
    ],
    sm=[
        {
            'color': 'rgba(0,0,0,0.06)',
            'offset_x': 0,
            'offset_y': 1,
            'blur': 2,
            'spread': -1,
            'inset': False,
        },
        {
            'color': 'rgba(0,0,0,0.10)',
            'offset_x': 0,
            'offset_y': 1,
            'blur': 3,
            'spread': 0,
            'inset': False,
        },
    ],
    xl=[
        {
            'color': 'rgba(0,0,0,0.04)',
            'offset_x': 0,
            'offset_y': 8,
            'blur': 10,
            'spread': -6,
            'inset': False,
        },
        {
            'color': 'rgba(0,0,0,0.10)',
            'offset_x': 0,
            'offset_y': 20,
            'blur': 25,
            'spread': -5,
            'inset': False,
        },
    ],
    xs=[
        {
            'color': 'rgba(0,0,0,0.05)',
            'offset_x': 0,
            'offset_y': 1,
            'blur': 2,
            'spread': 0,
            'inset': False,
        },
    ],
)

_TABLE = BTechShadowTable(
    left=[
        {
            'color': 'rgba(0,0,0,0.15)',
            'offset_x': 4,
            'offset_y': 0,
            'blur': 4,
            'spread': 0,
            'inset': False,
        },
    ],
    right=[
        {
            'color': 'rgba(0,0,0,0.15)',
            'offset_x': -4,
            'offset_y': 0,
            'blur': 4,
            'spread': 0,
            'inset': False,
        },
    ],
)

@dataclass(frozen=True, slots=True)
class _ShadowRoot:
    button: BTechShadowButton
    elevation: BTechShadowElevation
    table: BTechShadowTable

BTechShadow = _ShadowRoot(
    button=_BUTTON,
    elevation=_ELEVATION,
    table=_TABLE,
)
