# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.

from __future__ import annotations
from dataclasses import dataclass
from . import _data

@dataclass(frozen=True, slots=True)
class _BTechSpacingClass:
    s2xs: float
    xs: float
    sm: float
    md: float
    lg: float
    xl: float
    s2xl: float
    s3xl: float

BTechSpacing: _BTechSpacingClass = _BTechSpacingClass(**_data.SPACING)
