# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.

from __future__ import annotations
from dataclasses import dataclass
from . import _data

@dataclass(frozen=True, slots=True)
class _BTechFontFamilyClass:
    sans: str
    mono: str

@dataclass(frozen=True, slots=True)
class _BTechFontSizeClass:
    s3xs: float
    s2xs: float
    xs: float
    sm: float
    md: float
    lg: float
    xl: float
    s2xl: float
    s3xl: float
    s4xl: float
    s5xl: float

@dataclass(frozen=True, slots=True)
class _BTechFontWeightClass:
    regular: int
    medium: int
    semibold: int
    bold: int

@dataclass(frozen=True, slots=True)
class _BTechLineHeightClass:
    s2xs: float
    xs: float
    sm: float
    md: float
    lg: float
    xl: float
    s2xl: float
    s3xl: float
    s4xl: float

BTechFontFamily: _BTechFontFamilyClass = _BTechFontFamilyClass(**_data.FONT_FAMILIES)
BTechFontSize: _BTechFontSizeClass = _BTechFontSizeClass(**_data.FONT_SIZES)
BTechFontWeight: _BTechFontWeightClass = _BTechFontWeightClass(**_data.FONT_WEIGHTS)
BTechLineHeight: _BTechLineHeightClass = _BTechLineHeightClass(**_data.LINE_HEIGHTS)

@dataclass(frozen=True, slots=True)
class _BTechFontClass:
    family: _BTechFontFamilyClass
    size: _BTechFontSizeClass
    weight: _BTechFontWeightClass
    line_height: _BTechLineHeightClass

BTechFont: _BTechFontClass = _BTechFontClass(
    family=BTechFontFamily,
    size=BTechFontSize,
    weight=BTechFontWeight,
    line_height=BTechLineHeight,
)
