// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'color/color.theme.dart';
import 'radius/radius.theme.dart';
import 'typography/font.theme.dart';
import 'theme_builder.dart';

// ── Light (public — Pattern B) ─────────────────────────────────────────────

/// Default light-mode color tokens. Used when no tenant package is active.
const BTechColorTheme btechColor = BTechColorTheme(
  text: BTechColorText(
    primary: Color(0xFF181C20),
    secondary: Color(0xFF64748B),
    tertiary: Color(0xFF98A2B0),
    inverse: Color(0xFFFFFFFF),
    disabled: Color(0xFFC1C6CD),
    link: Color(0xFF0D766C),
    success: Color(0xFF0A632F),
    error: Color(0xFF991515),
    warning: Color(0xFF885A0D),
    info: Color(0xFF0F5E81),
  ),
  icon: BTechColorIcon(
    primary: Color(0xFF181C20),
    secondary: Color(0xFF64748B),
    tertiary: Color(0xFF98A2B0),
    inverse: Color(0xFFFFFFFF),
    disabled: Color(0xFFC1C6CD),
    link: Color(0xFF0D766C),
    success: Color(0xFF0A632F),
    error: Color(0xFF991515),
    warning: Color(0xFF885A0D),
    info: Color(0xFF0F5E81),
  ),
  border: BTechColorBorder(
    primary: Color(0xFFDBDDE1),
    secondary: Color(0xFF98A2B0),
    tertiary: Color(0xFFC1C6CD),
    inverse: Color(0xFF292F37),
    disabled: Color(0xFFC1C6CD),
  ),
  bg: BTechColorBg(
    primary: Color(0xFFFFFFFF),
    secondary: Color(0xFFECEDEE),
    tertiary: Color(0xFF64748B),
    inverse: Color(0xFF181C20),
    subtle: Color(0xFFF4F5F6),
    subtler: Color(0xFFDBDDE1),
    subtlest: Color(0xFFC1C6CD),
    overlay: Color(0xCC181C20),
  ),
  brand: BTechColorBrand(
    primarySubtle: Color(0xFFF0F8F4),
    primary: Color(0xFF08A94C),
    primaryBold: Color(0xFF0A853E),
    secondarySubtle: Color(0xFFF0F8F7),
    secondary: Color(0xFF0D9488),
    secondaryBold: Color(0xFF0D766C),
  ),
  ext: BTechColorExt(
    successSubtler: Color(0xFFE2F3E9),
    successSubtle: Color(0xFFC5EAD5),
    success: Color(0xFF08A94C),
    successBold: Color(0xFF0A853E),
    infoSubtler: Color(0xFFE7F0F4),
    infoSubtle: Color(0xFFD0E4ED),
    info: Color(0xFF0EA5E9),
    infoBold: Color(0xFF0F81B4),
    warningSubtler: Color(0xFFF5F0E7),
    warningSubtle: Color(0xFFEFE3D0),
    warning: Color(0xFFF59E0B),
    warningBold: Color(0xFFBD7C0C),
    errorSubtler: Color(0xFFF6EAEA),
    errorSubtle: Color(0xFFF0D9D9),
    error: Color(0xFFEF4444),
    errorBold: Color(0xFFD81818),
  ),
);

// ── Dark (private) ─────────────────────────────────────────────────────────

const BTechColorTheme _btechColorDark = BTechColorTheme(
  text: BTechColorText(
    primary: Color(0xFFECEDEE),
    secondary: Color(0xFF98A2B0),
    tertiary: Color(0xFF64748B),
    inverse: Color(0xFF181C20),
    disabled: Color(0xFF505C6D),
    link: Color(0xFF0D9488),
    success: Color(0xFF94E2B5),
    error: Color(0xFFEBBDBD),
    warning: Color(0xFFE9D2AB),
    info: Color(0xFFAAD4E7),
  ),
  icon: BTechColorIcon(
    primary: Color(0xFFECEDEE),
    secondary: Color(0xFF98A2B0),
    tertiary: Color(0xFF64748B),
    inverse: Color(0xFF181C20),
    disabled: Color(0xFF505C6D),
    link: Color(0xFF0D9488),
    success: Color(0xFF94E2B5),
    error: Color(0xFFEBBDBD),
    warning: Color(0xFFE9D2AB),
    info: Color(0xFFAAD4E7),
  ),
  border: BTechColorBorder(
    primary: Color(0xFF505C6D),
    secondary: Color(0xFF64748B),
    tertiary: Color(0xFFDBDDE1),
    inverse: Color(0xFFECEDEE),
    disabled: Color(0xFF3C4450),
  ),
  bg: BTechColorBg(
    primary: Color(0xFF181C20),
    secondary: Color(0xFF3C4450),
    tertiary: Color(0xFFECEDEE),
    inverse: Color(0xFFECEDEE),
    subtle: Color(0xFF292F37),
    subtler: Color(0xFF505C6D),
    subtlest: Color(0xFF64748B),
    overlay: Color(0xCC181C20),
  ),
  brand: BTechColorBrand(
    primarySubtle: Color(0xFF072D17),
    primary: Color(0xFF41E084),
    primaryBold: Color(0xFF08A94C),
    secondarySubtle: Color(0xFF082A27),
    secondary: Color(0xFF3ED8CA),
    secondaryBold: Color(0xFF0D766C),
  ),
  ext: BTechColorExt(
    successSubtler: Color(0xFF08A94C),
    successSubtle: Color(0xFF0A632F),
    success: Color(0xFF41E084),
    successBold: Color(0xFFF0F8F4),
    infoSubtler: Color(0xFF0EA5E9),
    infoSubtle: Color(0xFF0F5E81),
    info: Color(0xFF69BEE4),
    infoBold: Color(0xFFF1F6F9),
    warningSubtler: Color(0xFFF59E0B),
    warningSubtle: Color(0xFF885A0D),
    warning: Color(0xFFE8BA6C),
    warningBold: Color(0xFFF9F6F1),
    errorSubtler: Color(0xFFEF4444),
    errorSubtle: Color(0xFF991515),
    error: Color(0xFFE88D8D),
    errorBold: Color(0xFFF9F2F2),
  ),
);

// ── Radius ──────────────────────────────────────────────────────────────────

/// Default radius tokens.
const BTechRadiusTheme btechRadius = BTechRadiusTheme(
  interactive: 8.0,
  card: 12.0,
  badge: 9999.0,
  tooltip: 2.0,
);

// ── Font ────────────────────────────────────────────────────────────────────

/// Default font tokens.
const BTechFontTheme btechFont = BTechFontTheme(
  family: BTechFontFamily(sans: 'Inter'),
);

// ── Theme builder ───────────────────────────────────────────────────────────

/// Build a default BTech [ThemeData]. Use when no tenant package is needed.
///
/// ```dart
/// MaterialApp(
///   theme:     btechTheme(),
///   darkTheme: btechTheme(brightness: Brightness.dark),
///   themeMode: ThemeMode.system,
/// )
/// ```
ThemeData btechTheme({Brightness brightness = Brightness.light, ThemeData? base}) =>
    buildBtechTheme(btechColor, _btechColorDark, btechRadius, btechFont,
                    brightness: brightness, base: base);
