// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from sources/tenants/**.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'tenants/default.dart';
import 'tenants/tenant_a.dart';
import 'tenants/tenant_bjb.dart';

/// Resolved semantic token set for a specific tenant.
/// Use [BTechTenantTokens.forTenant] to look up by tenant ID,
/// or reference a tenant directly: [BTechTenantTokens.defaultTokens].
///
/// In widgets, prefer the context extension:
///   context.btechColor.background.primary
///   context.btechRadius.interactive
///   context.btechFont.sans
class BTechTenantTokens {

  final Color colorBackgroundSurface;
  final Color colorBackgroundSurfaceSubtle;
  final Color colorBackgroundSurfaceRaised;
  final Color colorBackgroundPrimary;
  final Color colorBackgroundPrimaryHover;
  final Color colorBackgroundPrimaryPressed;
  final Color colorBackgroundPrimaryDisable;
  final Color colorBackgroundPrimarySubtle;
  final Color colorBackgroundSecondary;
  final Color colorBackgroundSecondaryHover;
  final Color colorBackgroundSecondaryPressed;
  final Color colorBackgroundSecondaryDisable;
  final Color colorBackgroundSecondarySubtle;
  final Color colorBackgroundDanger;
  final Color colorBackgroundDangerHover;
  final Color colorBackgroundDangerPressed;
  final Color colorBackgroundDangerDisable;
  final Color colorBackgroundDangerSubtle;
  final Color colorBackgroundSuccess;
  final Color colorBackgroundSuccessSubtle;
  final Color colorBackgroundWarning;
  final Color colorBackgroundWarningSubtle;
  final Color colorBackgroundInfo;
  final Color colorBackgroundInfoSubtle;
  final Color colorBackgroundNeutral;
  final Color colorBackgroundNeutralSubtle;
  final Color colorTextNeutral;
  final Color colorTextNeutralSubtle;
  final Color colorTextNeutralDisabled;
  final Color colorTextNeutralInverse;
  final Color colorTextOnPrimary;
  final Color colorTextOnSecondary;
  final Color colorTextOnDanger;
  final Color colorTextOnInfo;
  final Color colorIconNeutral;
  final Color colorIconNeutralSubtle;
  final Color colorIconNeutralDisabled;
  final Color colorIconNeutralInverse;
  final Color colorIconOnPrimary;
  final Color colorIconOnDanger;
  final Color colorStrokeNeutral;
  final Color colorStrokeNeutralStrong;
  final Color colorStrokeNeutralSubtle;
  final Color colorStrokePrimary;
  final Color colorStrokePrimaryBolder;
  final Color colorStrokeDanger;
  final double radiusInteractive;
  final double radiusCard;
  final double radiusBadge;
  final String typographyFontFamilySans;

  const BTechTenantTokens({
    required this.colorBackgroundSurface,
    required this.colorBackgroundSurfaceSubtle,
    required this.colorBackgroundSurfaceRaised,
    required this.colorBackgroundPrimary,
    required this.colorBackgroundPrimaryHover,
    required this.colorBackgroundPrimaryPressed,
    required this.colorBackgroundPrimaryDisable,
    required this.colorBackgroundPrimarySubtle,
    required this.colorBackgroundSecondary,
    required this.colorBackgroundSecondaryHover,
    required this.colorBackgroundSecondaryPressed,
    required this.colorBackgroundSecondaryDisable,
    required this.colorBackgroundSecondarySubtle,
    required this.colorBackgroundDanger,
    required this.colorBackgroundDangerHover,
    required this.colorBackgroundDangerPressed,
    required this.colorBackgroundDangerDisable,
    required this.colorBackgroundDangerSubtle,
    required this.colorBackgroundSuccess,
    required this.colorBackgroundSuccessSubtle,
    required this.colorBackgroundWarning,
    required this.colorBackgroundWarningSubtle,
    required this.colorBackgroundInfo,
    required this.colorBackgroundInfoSubtle,
    required this.colorBackgroundNeutral,
    required this.colorBackgroundNeutralSubtle,
    required this.colorTextNeutral,
    required this.colorTextNeutralSubtle,
    required this.colorTextNeutralDisabled,
    required this.colorTextNeutralInverse,
    required this.colorTextOnPrimary,
    required this.colorTextOnSecondary,
    required this.colorTextOnDanger,
    required this.colorTextOnInfo,
    required this.colorIconNeutral,
    required this.colorIconNeutralSubtle,
    required this.colorIconNeutralDisabled,
    required this.colorIconNeutralInverse,
    required this.colorIconOnPrimary,
    required this.colorIconOnDanger,
    required this.colorStrokeNeutral,
    required this.colorStrokeNeutralStrong,
    required this.colorStrokeNeutralSubtle,
    required this.colorStrokePrimary,
    required this.colorStrokePrimaryBolder,
    required this.colorStrokeDanger,
    required this.radiusInteractive,
    required this.radiusCard,
    required this.radiusBadge,
    required this.typographyFontFamilySans,
  });

  /// Default tenant.
  static const BTechTenantTokens defaultTokens = btechTenantDefault;

  /// Tenant: tenant-a.
  static const BTechTenantTokens tenantA = btechTenantTenantA;

  /// Tenant: tenant-bjb.
  static const BTechTenantTokens tenantBjb = btechTenantTenantBjb;

  /// Registry — add new tenants here after running `pnpm generate`.
  static const Map<String, BTechTenantTokens> _registry = {
    'default': defaultTokens,
    'tenant-a': tenantA,
    'tenant-bjb': tenantBjb,
  };

  /// Resolve tokens for [tenantId]. Falls back to [defaultTokens] if unknown.
  static BTechTenantTokens forTenant(String tenantId) =>
      _registry[tenantId] ?? btechTenantDefault;
}
