// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'color/color.theme.dart';
import 'radius/radius.theme.dart';
import 'typography/font.theme.dart';

/// Builds a [ThemeData] with BTech design tokens registered as [ThemeExtension]s.
///
/// Call from each tenant's `btechTheme()` one-liner — logic lives here, not in the tenant.
///
/// ```dart
/// MaterialApp(
///   theme:     btechTheme(),
///   darkTheme: btechTheme(brightness: Brightness.dark),
/// )
/// ```
ThemeData buildBtechTheme(
  BTechColorTheme colorLight,
  BTechColorTheme colorDark,
  BTechRadiusTheme radius,
  BTechFontTheme font, {
  Brightness brightness = Brightness.light,
  ThemeData? base,
}) {
  BTechColor.activateBoth(colorLight, colorDark);
  BTechRadius.activate(radius);
  BTechFont.activate(font);
  final activeColor = brightness == Brightness.dark ? colorDark : colorLight;
  return (base ?? ThemeData(brightness: brightness))
      .copyWith(extensions: [activeColor, radius, font]);
}
