// BTButton types — Figma source: node 114:2645.
// Generated by btech mason brick — do not edit the brick template.
// This file is now owned by your project — customize freely.

/// Visual style of the button.
enum BTButtonVariant {
  primary,
  secondary,
  destructive,
  outline,
  ghost,
}

/// Padding scale.
enum BTButtonSize {
  /// Default — 12 px vertical × 16 px horizontal.
  md,

  /// Small — 8 px on all sides.
  sm,
}
