// Python-specific helpers for token generation.
// Kept separate from generators/utils.ts because Python casing rules and
// reserved-word handling differ from TypeScript / Dart.

const PY_KEYWORDS = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await',
  'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except',
  'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is',
  'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try',
  'while', 'with', 'yield', 'match', 'case',
]);

/** kebab-case → snake_case. Preserves existing snake_case. */
export function toSnakeCase(s: string): string {
  return s.replace(/-/g, '_');
}

/** Make a name a valid Python identifier:
 *   2xs        → s2xs   (numeric-leading)
 *   primary-hover → primary_hover
 *   class      → class_  (reserved word)
 */
export function pySafeName(name: string): string {
  let safe = toSnakeCase(name);
  if (/^[0-9]/.test(safe)) safe = `s${safe}`;
  if (PY_KEYWORDS.has(safe)) safe = `${safe}_`;
  return safe;
}

/** Parse a px-bearing dimension to a Python float literal. '8px' → '8.0'. */
export function pxToPyFloat(value: string | number): string {
  const n = parseFloat(String(value).replace('px', ''));
  if (Number.isNaN(n)) return '0.0';
  return Number.isInteger(n) ? `${n}.0` : String(n);
}

/** Escape a string for a Python single-quoted literal. */
export function pyStr(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Standard header for every generated .py file. */
export const PY_HEADER =
  '# AUTO-GENERATED by @btech/design-system — do not edit by hand.\n' +
  '# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.\n';
