/**
 * python-generator.ts
 * Generates the btech_tokens Python package under platforms/python/.
 *
 * Output structure:
 *   platforms/python/btech_tokens/
 *     _tokens.py     — flat resolved dict (all tokens)
 *     color.py       — BTechColor with nested dot-access
 *     spacing.py     — BTechSpacing (int px values)
 *     radius.py      — BTechRadius  (int px values)
 *     stroke.py      — BTechStroke  (int px values)
 *     shadow.py      — BTechShadow  (CSS shadow strings)
 *     typography.py  — BTechTypography (font families, sizes, weights)
 *     __init__.py    — public API: token(), BTechColor, BTechSpacing, …
 */
import { mkdirSync, writeFileSync, readFileSync } from 'fs';
import { ROOT } from '../utils.js';
import type { ResolvedTokenMap } from '../token-loader.js';

// ── Constants ──────────────────────────────────────────────────────────────────
const PYTHON_OUT = `${ROOT}/platforms/python/btech_tokens`;
const HEADER     = `# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run \`pnpm generate\` to regenerate from packages/tokens/sources/.
`;

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Convert a token key like "2xs" or "2xl" to a valid Python identifier. */
function pyName(key: string): string {
  // Keys starting with a digit get an "s" prefix: "2xs" → "s2xs"
  if (/^\d/.test(key)) return `s${key.replace(/-/g, '_')}`;
  return key.replace(/-/g, '_');
}

/** Parse "12px" → 12; "9999px" → 9999; "1.5px" → 1 */
function parsePx(val: string): number {
  return Math.round(parseFloat(val.replace('px', '')));
}

/** Indent every line of a string by n spaces. */
function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s.split('\n').map(l => (l.trim() === '' ? '' : pad + l)).join('\n');
}

/**
 * Convert a DTCG shadow value (object or array) to a CSS box-shadow string.
 * Handles the raw JSON from shadow.primitive.json.
 */
function shadowToCss(val: unknown): string {
  function one(s: Record<string, unknown>): string {
    const inset  = s.inset ? 'inset ' : '';
    return `${inset}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`;
  }
  if (Array.isArray(val)) return val.map(s => one(s as Record<string, unknown>)).join(', ');
  if (val && typeof val === 'object') return one(val as Record<string, unknown>);
  return String(val);
}

// ── File generators ────────────────────────────────────────────────────────────

function genTokensFlat(data: ResolvedTokenMap, shadows: Record<string, string>): string {
  const lines: string[] = [HEADER, 'from __future__ import annotations\n', 'TOKENS: dict[str, str] = {'];

  // Semantic colors
  for (const [group, cats] of Object.entries(data.semanticColors)) {
    for (const [cat, variants] of Object.entries(cats)) {
      for (const [name, val] of Object.entries(variants)) {
        lines.push(`    "color.${group}.${cat}.${name}": ${JSON.stringify(val)},`);
      }
    }
  }

  // Spacing
  for (const [k, v] of Object.entries(data.spacing)) {
    lines.push(`    "spacing.${k}": ${JSON.stringify(v)},`);
  }

  // Radius (semantic preferred, fall back to core)
  const radius = { ...data.radius.core, ...data.radius.semantic };
  for (const [k, v] of Object.entries(radius)) {
    lines.push(`    "radius.${k}": ${JSON.stringify(v)},`);
  }

  // Shadows
  for (const [k, v] of Object.entries(shadows)) {
    lines.push(`    ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  }

  // Typography
  for (const [group, props] of Object.entries(data.typography.semantic)) {
    for (const [prop, val] of Object.entries(props)) {
      lines.push(`    "typography.${group}.${prop}": ${JSON.stringify(val)},`);
    }
  }

  lines.push('}\n');
  return lines.join('\n');
}


function genColor(data: ResolvedTokenMap): string {
  const lines: string[] = [HEADER, 'from __future__ import annotations\n'];

  // Build color group classes (text, bg, icon, border, brand, ext)
  const groups = data.semanticColors;

  // One inner class per semantic group
  for (const [group, cats] of Object.entries(groups)) {
    const className = `_BTechColor${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`\nclass ${className}:`);

    for (const [cat, variants] of Object.entries(cats)) {
      // Each category is a sub-object with variants (primary, secondary, …)
      // OR flat values (e.g. brand.primary-default)
      const subClass = `_BTechColor${group.charAt(0).toUpperCase()}${group.slice(1)}${cat.charAt(0).toUpperCase()}${cat.slice(1).replace(/-/g, '')}`;
      const hasVariants = Object.keys(variants).length > 1 ||
        !Object.keys(variants).includes('primary');

      if (hasVariants && Object.keys(variants).length > 0) {
        lines.push(`\n    class ${subClass}:`);
        for (const [name, val] of Object.entries(variants)) {
          lines.push(`        ${pyName(name)}: str = ${JSON.stringify(val)}`);
        }
        lines.push(`    ${pyName(cat)}: ${subClass} = ${subClass}()`);
      } else {
        for (const [, val] of Object.entries(variants)) {
          lines.push(`    ${pyName(cat)}: str = ${JSON.stringify(val)}`);
        }
      }
    }
  }

  // Core color shades (BTechColorShades)
  lines.push('\n\nclass _BTechColorShades:');
  for (const [group, shades] of Object.entries(data.coreColors)) {
    lines.push(`    class _${group.charAt(0).toUpperCase()}${group.slice(1)}:`);
    for (const [shade, val] of Object.entries(shades)) {
      const safeName = /^\d/.test(shade) ? `s${shade}` : shade;
      lines.push(`        s${shade}: str = ${JSON.stringify(val)}`);
    }
    lines.push(`    ${group} = _${group.charAt(0).toUpperCase()}${group.slice(1)}()`);
  }

  // Root BTechColor class
  lines.push('\n\nclass BTechColor:');
  lines.push('    """Static dot-access to all resolved semantic color tokens."""');
  for (const group of Object.keys(groups)) {
    const className = `_BTechColor${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`    ${group}: ${className} = ${className}()`);
  }
  lines.push('    shades: _BTechColorShades = _BTechColorShades()');

  return lines.join('\n') + '\n';
}


function genSimple(
  label: string,
  className: string,
  entries: Record<string, string>,
): string {
  const lines: string[] = [HEADER, 'from __future__ import annotations\n', `\nclass ${className}:`,
    `    """Static dot-access to resolved ${label} tokens (int px values)."""`];
  for (const [k, v] of Object.entries(entries)) {
    lines.push(`    ${pyName(k)}: int = ${parsePx(v)}`);
  }
  return lines.join('\n') + '\n';
}


function genShadow(shadows: Record<string, string>): string {
  // Group by first segment: button, table, elevation
  const groups: Record<string, Record<string, string>> = {};
  for (const [key, val] of Object.entries(shadows)) {
    // key like "shadow.elevation.md" → strip "shadow."
    const parts = key.replace(/^shadow\./, '').split('.');
    const [group, name] = parts.length === 2 ? parts : [parts[0], parts.slice(1).join('_')];
    if (!groups[group]) groups[group] = {};
    groups[group][name] = val;
  }

  const lines: string[] = [HEADER, 'from __future__ import annotations\n'];

  for (const [group, variants] of Object.entries(groups)) {
    const cls = `_BTechShadow${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`\nclass ${cls}:`);
    lines.push(`    """CSS box-shadow strings for ${group} tokens."""`);
    for (const [name, val] of Object.entries(variants)) {
      lines.push(`    ${pyName(name)}: str = ${JSON.stringify(val)}`);
    }
  }

  lines.push('\n\nclass BTechShadow:');
  lines.push('    """Static dot-access to all resolved shadow tokens."""');
  for (const group of Object.keys(groups)) {
    const cls = `_BTechShadow${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`    ${group}: ${cls} = ${cls}()`);
  }
  return lines.join('\n') + '\n';
}


function genTypography(data: ResolvedTokenMap): string {
  const lines: string[] = [HEADER, 'from __future__ import annotations\n',
    '\nclass _BTechFontFamily:',
    '    """Resolved font-family strings."""'];

  for (const [k, v] of Object.entries(data.typography.fontFamilies)) {
    lines.push(`    ${pyName(k)}: str = ${JSON.stringify(v)}`);
  }

  lines.push('\n\nclass _BTechTypeScaleEntry:');
  lines.push('    def __init__(self, font_size: float, font_weight: int, line_height: float):');
  lines.push('        self.font_size = font_size');
  lines.push('        self.font_weight = font_weight');
  lines.push('        self.line_height = line_height');
  lines.push('    def __repr__(self) -> str:');
  lines.push('        return f"TypeScale(fs={self.font_size}, fw={self.font_weight}, lh={self.line_height})"');

  for (const group of ['heading', 'subheading', 'body'] as const) {
    const entries = data.typography.typeScale[group];
    if (!entries || Object.keys(entries).length === 0) continue;
    const cls = `_BTechTypeScale${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`\n\nclass ${cls}:`);
    lines.push(`    """${group} type-scale entries."""`);
    for (const [name, entry] of Object.entries(entries)) {
      lines.push(
        `    ${pyName(name)}: _BTechTypeScaleEntry = _BTechTypeScaleEntry(` +
        `font_size=${entry.fontSize}, font_weight=${entry.fontWeight}, line_height=${entry.lineHeightPx})`
      );
    }
  }

  lines.push('\n\nclass BTechTypography:');
  lines.push('    """Static dot-access to all resolved typography tokens."""');
  lines.push('    family: _BTechFontFamily = _BTechFontFamily()');
  for (const group of ['heading', 'subheading', 'body'] as const) {
    const entries = data.typography.typeScale[group];
    if (!entries || Object.keys(entries).length === 0) continue;
    const cls = `_BTechTypeScale${group.charAt(0).toUpperCase()}${group.slice(1)}`;
    lines.push(`    ${group}: ${cls} = ${cls}()`);
  }

  return lines.join('\n') + '\n';
}


function genInit(): string {
  // Note: no backticks inside this string to avoid premature template-literal closure.
  const body = [
    HEADER,
    '"""',
    'btech_tokens -- BTech Design System token package for Python / Streamlit.',
    '',
    'Usage',
    '-----',
    'from btech_tokens import token, BTechColor, BTechSpacing, BTechRadius, BTechStroke, BTechShadow, BTechTypography',
    '',
    '# Dot-access (resolved values)',
    "bg     = BTechColor.bg.primary              # '#ffffff'",
    "brand  = BTechColor.brand.primarydefault    # '#4f46e5'",
    "sp_md  = BTechSpacing.md                   # 12  (int px)",
    "rad_md = BTechRadius.md                    # 12  (int px)",
    "stroke = BTechStroke.xs                    # 1   (int px)",
    "shadow = BTechShadow.elevation.md          # 'CSS box-shadow string'",
    "font   = BTechTypography.family.sans       # 'Inter, system-ui, sans-serif'",
    '',
    '# Path-based lookup',
    "bg = token('color.bg.primary')             # '#ffffff'",
    "sp = token('spacing.md')                   # '12px'",
    '"""',
    'from __future__ import annotations',
    'from ._tokens      import TOKENS',
    'from .color        import BTechColor',
    'from .spacing      import BTechSpacing',
    'from .radius       import BTechRadius',
    'from .stroke       import BTechStroke',
    'from .shadow       import BTechShadow',
    'from .typography   import BTechTypography',
    '',
    '__all__ = [',
    "    'token',",
    "    'BTechColor',",
    "    'BTechSpacing',",
    "    'BTechRadius',",
    "    'BTechStroke',",
    "    'BTechShadow',",
    "    'BTechTypography',",
    "    'TOKENS',",
    ']',
    '',
    "__version__ = '0.0.1'",
    '',
    '',
    'def token(path: str, fallback: str = "") -> str:',
    '    """',
    '    Return the resolved value for a token path.',
    '',
    '    Parameters',
    '    ----------',
    '    path : str',
    "        Dot-separated token path, e.g. 'color.bg.primary',",
    "        'spacing.md', 'shadow.elevation.md'.",
    '    fallback : str',
    '        Value to return when the path is not found (default: empty string).',
    '',
    '    Returns',
    '    -------',
    '    str',
    "        The resolved value, e.g. '#ffffff', '12px'.",
    '    """',
    '    return TOKENS.get(path, fallback)',
    '',
  ];
  return body.join('\n');
}


// ── Shadow loader (reads directly from source JSON) ───────────────────────────

function loadShadows(): Record<string, string> {
  const shadowFile = `${ROOT}/sources/shadow/shadow.json`;
  const primFile   = `${ROOT}/sources/primitives/color.json`;

  let shadowJson: Record<string, unknown>;
  let colorPrim: Record<string, Record<string, Record<string, { $value: string }>>>;

  try {
    shadowJson = JSON.parse(readFileSync(shadowFile, 'utf-8'));
    colorPrim  = JSON.parse(readFileSync(primFile,   'utf-8')).color ?? {};
  } catch {
    return {};
  }

  // Build color primitive map for resolving shadow colors
  const colorMap: Record<string, string> = {};
  for (const [group, shades] of Object.entries(colorPrim)) {
    for (const [shade, token] of Object.entries(shades)) {
      if (!shade.startsWith('$')) colorMap[`color.${group}.${shade}`] = token.$value;
    }
  }

  function resolveColor(val: string): string {
    const m = val.match(/^\{(.+)\}$/);
    return m ? (colorMap[m[1]] ?? val) : val;
  }

  const result: Record<string, string> = {};

  function walk(obj: Record<string, unknown>, prefix: string): void {
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith('$')) continue;
      const path = prefix ? `${prefix}.${k}` : k;
      if (v && typeof v === 'object' && '$value' in (v as object)) {
        const rawVal = (v as Record<string, unknown>).$value;
        // Resolve any color references inside shadow objects
        if (Array.isArray(rawVal)) {
          const resolved = rawVal.map(s => {
            const entry = s as Record<string, unknown>;
            return { ...entry, color: resolveColor(String(entry.color ?? '')) };
          });
          result[path] = shadowToCss(resolved);
        } else if (rawVal && typeof rawVal === 'object') {
          const entry = rawVal as Record<string, unknown>;
          result[path] = shadowToCss({ ...entry, color: resolveColor(String(entry.color ?? '')) });
        }
      } else if (v && typeof v === 'object') {
        walk(v as Record<string, unknown>, path);
      }
    }
  }

  walk(shadowJson as Record<string, unknown>, '');
  return result;
}


// ── Shared exports (used by python-tenant-format.ts) ──────────────────────────

/**
 * Convert all keys of a flat string map to valid Python identifiers using
 * the same `pyName` rules applied across this generator (digits prefixed
 * with "s", hyphens → underscores). Used by the tenant format generator to
 * normalise field names before passing them downstream.
 */
export function snakeKeyed(fields: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(fields)) {
    out[pyName(k)] = v;
  }
  return out;
}

/**
 * Write the full set of Python module files for one package into `moduleDir`.
 * Called by both the base generator and the per-tenant generator; the caller
 * supplies an already-resolved `data` (tenant overrides applied) so the same
 * internal generators (`genColor`, `genSimple`, …) produce the correct output
 * for both cases.
 *
 * `lightColors` and `darkColors` are accepted for interface compatibility but
 * the actual output is derived from `data.semanticColors` (already tenant-
 * specific) via the shared internal generators.
 */
export function generatePythonPackageContents(
  moduleDir: string,
  data: ResolvedTokenMap,
  _lightColors: Record<string, Record<string, string>>,
  _darkColors:  Record<string, Record<string, string>>,
): void {
  const shadows = loadShadows();
  // data.radius is a flat Record<string,string> from token-loader; spread it
  // directly (the base generator has a legacy .core/.semantic split that is a
  // no-op — this is the correct form for all new callers).
  const radius = data.radius as unknown as Record<string, string>;

  writeFileSync(`${moduleDir}/_tokens.py`,    genTokensFlat(data, shadows), 'utf-8');
  writeFileSync(`${moduleDir}/color.py`,      genColor(data),               'utf-8');
  writeFileSync(`${moduleDir}/spacing.py`,    genSimple('spacing', 'BTechSpacing', data.spacing), 'utf-8');
  writeFileSync(`${moduleDir}/radius.py`,     genSimple('radius',  'BTechRadius',  radius),       'utf-8');
  writeFileSync(`${moduleDir}/typography.py`, genTypography(data),          'utf-8');
  writeFileSync(`${moduleDir}/shadow.py`,     genShadow(shadows),           'utf-8');
  writeFileSync(`${moduleDir}/__init__.py`,   genInit(),                    'utf-8');

  try {
    const strokeJson = JSON.parse(readFileSync(`${ROOT}/sources/stroke/stroke.json`, 'utf-8'));
    const strokeEntries: Record<string, string> = {};
    for (const [k, v] of Object.entries(strokeJson.stroke as Record<string, { $value: string }>)) {
      if (!k.startsWith('$')) strokeEntries[k] = v.$value;
    }
    writeFileSync(`${moduleDir}/stroke.py`, genSimple('stroke', 'BTechStroke', strokeEntries), 'utf-8');
  } catch {
    writeFileSync(`${moduleDir}/stroke.py`, `${HEADER}\nclass BTechStroke:\n    pass\n`, 'utf-8');
  }
}

// ── Main export ────────────────────────────────────────────────────────────────

export function generatePythonFiles(data: ResolvedTokenMap): void {
  mkdirSync(PYTHON_OUT, { recursive: true });

  const shadows = loadShadows();
  const radius  = { ...data.radius.core, ...data.radius.semantic };

  writeFileSync(`${PYTHON_OUT}/_tokens.py`,    genTokensFlat(data, shadows), 'utf-8');
  writeFileSync(`${PYTHON_OUT}/color.py`,      genColor(data),               'utf-8');
  writeFileSync(`${PYTHON_OUT}/spacing.py`,    genSimple('spacing', 'BTechSpacing', data.spacing), 'utf-8');
  writeFileSync(`${PYTHON_OUT}/radius.py`,     genSimple('radius',  'BTechRadius',  radius),       'utf-8');
  writeFileSync(`${PYTHON_OUT}/typography.py`, genTypography(data),          'utf-8');
  writeFileSync(`${PYTHON_OUT}/shadow.py`,     genShadow(shadows),           'utf-8');
  writeFileSync(`${PYTHON_OUT}/__init__.py`,   genInit(),                    'utf-8');

  // Stroke — load directly from source
  try {
    const strokeJson = JSON.parse(readFileSync(`${ROOT}/sources/stroke/stroke.json`, 'utf-8'));
    const strokeEntries: Record<string, string> = {};
    for (const [k, v] of Object.entries(strokeJson.stroke as Record<string, { $value: string }>)) {
      if (!k.startsWith('$')) strokeEntries[k] = v.$value;
    }
    writeFileSync(`${PYTHON_OUT}/stroke.py`, genSimple('stroke', 'BTechStroke', strokeEntries), 'utf-8');
  } catch {
    writeFileSync(`${PYTHON_OUT}/stroke.py`, `${HEADER}\nclass BTechStroke:\n    pass\n`, 'utf-8');
  }

  console.log(`  Python   — btech_tokens package generated at platforms/python/btech_tokens/`);
}
