# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.

"""Pure data dicts. No logic. Imported by color.py / spacing.py / etc."""
from __future__ import annotations

COLOR_LIGHT: dict[str, dict[str, str]] = {
    'text': {
        'primary': '#181c20',
        'secondary': '#64748b',
        'tertiary': '#98a2b0',
        'inverse': '#ffffff',
        'disabled': '#c1c6cd',
        'link': '#0d766c',
        'success': '#0a632f',
        'error': '#991515',
        'warning': '#885a0d',
        'info': '#0f5e81',
    },
    'icon': {
        'primary': '#181c20',
        'secondary': '#64748b',
        'tertiary': '#98a2b0',
        'inverse': '#ffffff',
        'disabled': '#c1c6cd',
        'link': '#0d766c',
        'success': '#0a632f',
        'error': '#991515',
        'warning': '#885a0d',
        'info': '#0f5e81',
    },
    'border': {
        'primary': '#dbdde1',
        'secondary': '#98a2b0',
        'tertiary': '#c1c6cd',
        'inverse': '#292f37',
        'disabled': '#c1c6cd',
    },
    'bg': {
        'primary': '#145bc3',
        'secondary': '#8a59c2',
        'tertiary': '#6e479b',
        'inverse': '#ffffff',
        'subtle': '#f3eef9',
        'subtler': '#e7eff9',
        'subtlest': '#d1d5db',
        'overlay': '#181c20cc',
    },
    'brand': {
        'primary_subtle': '#e7eff9',
        'primary': '#145bc3',
        'primary_bold': '#10499c',
        'secondary_subtle': '#f3eef9',
        'secondary': '#8a59c2',
        'secondary_bold': '#6e479b',
    },
    'ext': {
        'success_subtler': '#e2f3e9',
        'success_subtle': '#c5ead5',
        'success': '#08a94c',
        'success_bold': '#0a853e',
        'info_subtler': '#e7f0f4',
        'info_subtle': '#d0e4ed',
        'info': '#0ea5e9',
        'info_bold': '#0f81b4',
        'warning_subtler': '#f5f0e7',
        'warning_subtle': '#efe3d0',
        'warning': '#f59e0b',
        'warning_bold': '#bd7c0c',
        'error_subtler': '#f6eaea',
        'error_subtle': '#f0d9d9',
        'error': '#ef4444',
        'error_bold': '#d81818',
    },
}

COLOR_DARK: dict[str, dict[str, str]] = {
    'text': {
        'primary': '#ecedee',
        'secondary': '#98a2b0',
        'tertiary': '#64748b',
        'inverse': '#181c20',
        'disabled': '#505c6d',
        'link': '#0d9488',
        'success': '#94e2b5',
        'error': '#ebbdbd',
        'warning': '#e9d2ab',
        'info': '#aad4e7',
    },
    'icon': {
        'primary': '#ecedee',
        'secondary': '#98a2b0',
        'tertiary': '#64748b',
        'inverse': '#181c20',
        'disabled': '#505c6d',
        'link': '#0d9488',
        'success': '#94e2b5',
        'error': '#ebbdbd',
        'warning': '#e9d2ab',
        'info': '#aad4e7',
    },
    'border': {
        'primary': '#505c6d',
        'secondary': '#64748b',
        'tertiary': '#dbdde1',
        'inverse': '#ecedee',
        'disabled': '#3c4450',
    },
    'bg': {
        'primary': '#145bc3',
        'secondary': '#8a59c2',
        'tertiary': '#6e479b',
        'inverse': '#ffffff',
        'subtle': '#f3eef9',
        'subtler': '#e7eff9',
        'subtlest': '#d1d5db',
        'overlay': '#181c20cc',
    },
    'brand': {
        'primary_subtle': '#e7eff9',
        'primary': '#145bc3',
        'primary_bold': '#10499c',
        'secondary_subtle': '#f3eef9',
        'secondary': '#8a59c2',
        'secondary_bold': '#6e479b',
    },
    'ext': {
        'success_subtler': '#08a94c',
        'success_subtle': '#0a632f',
        'success': '#41e084',
        'success_bold': '#f0f8f4',
        'info_subtler': '#0ea5e9',
        'info_subtle': '#0f5e81',
        'info': '#69bee4',
        'info_bold': '#f1f6f9',
        'warning_subtler': '#f59e0b',
        'warning_subtle': '#885a0d',
        'warning': '#e8ba6c',
        'warning_bold': '#f9f6f1',
        'error_subtler': '#ef4444',
        'error_subtle': '#991515',
        'error': '#e88d8d',
        'error_bold': '#f9f2f2',
    },
}

SPACING: dict[str, float] = {
    's2xs': 2.0,
    'xs': 4.0,
    'sm': 8.0,
    'md': 12.0,
    'lg': 16.0,
    'xl': 24.0,
    's2xl': 32.0,
    's3xl': 48.0,
}

RADIUS: dict[str, float] = {
    's2xs': 2.0,
    'xs': 4.0,
    'sm': 6.0,
    'md': 8.0,
    'lg': 16.0,
    'xl': 24.0,
    's2xl': 32.0,
    'rd': 9999.0,
}

STROKE: dict[str, float] = {
    'xs': 1.0,
    'sm': 2.0,
    'md': 3.0,
    'lg': 4.0,
    'xl': 5.0,
}

FONT_FAMILIES: dict[str, str] = {
    'sans': 'Rubik Storm, system-ui',
    'mono': '\'JetBrains Mono\', \'Fira Code\', monospace',
}

FONT_SIZES: dict[str, float] = {
    's3xs': 8.0,
    's2xs': 10.0,
    'xs': 12.0,
    'sm': 14.0,
    'md': 16.0,
    'lg': 18.0,
    'xl': 20.0,
    's2xl': 24.0,
    's3xl': 28.0,
    's4xl': 32.0,
    's5xl': 40.0,
}

FONT_WEIGHTS: dict[str, int] = {
    'regular': 400,
    'medium': 500,
    'semibold': 600,
    'bold': 700,
}

LINE_HEIGHTS: dict[str, float] = {
    's2xs': 12.0,
    'xs': 16.0,
    'sm': 20.0,
    'md': 24.0,
    'lg': 28.0,
    'xl': 32.0,
    's2xl': 36.0,
    's3xl': 40.0,
    's4xl': 48.0,
}
