# AUTO-GENERATED by @btech/design-system — do not edit by hand.
# Run `pnpm exec tsx packages/tokens/sd.config.ts` to regenerate.
from typing import Literal

# Mutated by btech_tokens.set_mode(). Read by color.py accessor properties.
_mode: Literal['light', 'dark'] = 'light'
