# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run `pnpm generate` to regenerate from packages/tokens/sources/.

from __future__ import annotations


class BTechRadius:
    """Static dot-access to resolved radius tokens (int px values)."""
    s2xs: int = 2
    xs: int = 4
    sm: int = 6
    md: int = 8
    lg: int = 16
    xl: int = 24
    s2xl: int = 32
    rd: int = 9999
