import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { toPascalCase, toYaml, dartSafeName, pathToCssVar } from '../utils.js';
import type { ResolvedTokenMap } from '../token-loader.js';
import { generateTsSemanticColorGroup } from './web-color.js';
import { generateTokensMeta } from '../flutter/flutter-color.js';

/** Generate all TypeScript token files into outDir (packages/tokens-web/src/). */
export function generateTsFiles(data: ResolvedTokenMap, outDir: string): void {
  const HEADER = '// AUTO-GENERATED by @btech/design-system — do not edit manually.\n// Run `pnpm generate` to regenerate from tokens/.\n';

  // ── color/ ────────────────────────────────────────────────────────────────
  const colorDir = `${outDir}/color`;
  mkdirSync(colorDir, { recursive: true });

  // shades.color.ts
  {
    const L = [HEADER];
    for (const [group, shades] of Object.entries(data.coreColors)) {
      const className = `BTechShades${toPascalCase(group)}Color`;
      const entries = Object.entries(shades).sort((a, b) => Number(a[0]) - Number(b[0]));
      L.push(`export class ${className} {`);
      for (const [shade, hex] of entries) {
        L.push(`  readonly s${shade} = '${hex}' as const;`);
      }
      L.push('}\n');
    }
    L.push('export class BTechShadesColor {');
    for (const group of Object.keys(data.coreColors)) {
      const className = `BTechShades${toPascalCase(group)}Color`;
      L.push(`  readonly ${group} = new ${className}();`);
    }
    L.push('}\n');
    writeFileSync(`${colorDir}/shades.color.ts`, L.join('\n') + '\n');
  }

  // Per-group color files (text, icon, border, bg, brand, ext)
  const semanticGroups = Object.keys(data.semanticColors);
  for (const groupName of semanticGroups) {
    generateTsSemanticColorGroup(colorDir, groupName, data.semanticColors[groupName], HEADER);
  }

  // color.token.ts — dynamic, driven by semanticGroups
  {
    const L = [HEADER];
    for (const g of semanticGroups) {
      const cls = `BTech${toPascalCase(g)}Color`;
      L.push(`import { ${cls} } from './${g}.color';`);
    }
    L.push("import { BTechShadesColor } from './shades.color';\n");
    L.push('export const BTechColor = {');
    for (const g of semanticGroups) {
      const cls = `BTech${toPascalCase(g)}Color`;
      L.push(`  ${g}: new ${cls}(),`);
    }
    L.push('  shades: new BTechShadesColor(),');
    L.push('} as const;\n');
    writeFileSync(`${colorDir}/color.token.ts`, L.join('\n') + '\n');
  }

  // index.ts (barrel)
  {
    const exports = [
      ...semanticGroups.map(g => `export * from './${g}.color';`),
      "export * from './shades.color';",
      "export { BTechColor } from './color.token';",
      '',
    ];
    writeFileSync(`${colorDir}/index.ts`, exports.join('\n'));
  }

  // tokens.meta.yaml
  generateTokensMeta(colorDir, 'color', data.semanticColors);

  // ── spacing/ ──────────────────────────────────────────────────────────────
  const spacingDir = `${outDir}/spacing`;
  mkdirSync(spacingDir, { recursive: true });

  {
    const L = [HEADER];
    L.push('export const BTechSpacing = {');
    for (const [name, value] of Object.entries(data.spacing)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  ${safeName}: ${parseFloat(String(value).replace('px', ''))},`);
    }
    L.push('} as const;\n');
    writeFileSync(`${spacingDir}/spacing.token.ts`, L.join('\n') + '\n');
  }
  writeFileSync(`${spacingDir}/index.ts`, "export { BTechSpacing } from './spacing.token';\n");
  {
    const meta = {
      category: 'spacing',
      figma: {
        collection: 'BTech/Spacing',
        tokens: Object.keys(data.spacing).map(name => ({
          path: `spacing.${name}`,
          figmaVariable: `Spacing/${toPascalCase(name)}`,
        })),
      },
    };
    writeFileSync(`${spacingDir}/tokens.meta.yaml`, toYaml(meta) + '\n');
  }

  // ── stroke/ ───────────────────────────────────────────────────────────────
  const strokeDir = `${outDir}/stroke`;
  mkdirSync(strokeDir, { recursive: true });

  {
    const L = [HEADER];
    L.push('export const BTechStroke = {');
    for (const [name, value] of Object.entries(data.stroke)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  ${safeName}: ${parseFloat(String(value).replace('px', ''))},`);
    }
    L.push('} as const;\n');
    writeFileSync(`${strokeDir}/stroke.token.ts`, L.join('\n') + '\n');
  }
  writeFileSync(`${strokeDir}/index.ts`, "export { BTechStroke } from './stroke.token';\n");
  {
    const meta = {
      category: 'stroke',
      figma: {
        collection: 'BTech/Stroke',
        tokens: Object.keys(data.stroke).map(name => ({
          path: `stroke.${name}`,
          figmaVariable: `Stroke/${toPascalCase(name)}`,
        })),
      },
    };
    writeFileSync(`${strokeDir}/tokens.meta.yaml`, toYaml(meta) + '\n');
  }

  // ── shadow/ ───────────────────────────────────────────────────────────
  const shadowDir = `${outDir}/shadow`;
  mkdirSync(shadowDir, { recursive: true });

  {
    function layerToCss(l: { color: string; offsetX: number; offsetY: number; blur: number; spread: number; inset: boolean }): string {
      const inset = l.inset ? 'inset ' : '';
      return `${inset}${l.offsetX}px ${l.offsetY}px ${l.blur}px ${l.spread}px ${l.color}`;
    }
    const L = [HEADER];
    L.push('export const BTechShadow = {');
    for (const [name, layers] of Object.entries(data.shadow)) {
      const css = layers.map(layerToCss).join(', ');
      L.push(`  ${name}: '${css}',`);
    }
    L.push('} as const;\n');
    writeFileSync(`${shadowDir}/shadow.token.ts`, L.join('\n') + '\n');
  }
  writeFileSync(`${shadowDir}/index.ts`, "export { BTechShadow } from './shadow.token';\n");

  // ── radius/ ───────────────────────────────────────────────────────────────
  const radiusDir = `${outDir}/radius`;
  mkdirSync(radiusDir, { recursive: true });

  {
    const L = [HEADER];
    L.push('export const BTechRadius = {');
    for (const [name, value] of Object.entries(data.radius)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  ${safeName}: ${parseFloat(String(value).replace('px', ''))},`);
    }
    L.push('} as const;\n');
    writeFileSync(`${radiusDir}/radius.token.ts`, L.join('\n') + '\n');
  }
  writeFileSync(`${radiusDir}/index.ts`, "export { BTechRadius } from './radius.token';\n");
  {
    const meta = {
      category: 'radius',
      figma: {
        collection: 'BTech/Radius',
        tokens: Object.keys(data.radius).map(name => ({
          path: `radius.${name}`,
          figmaVariable: `Radius/${toPascalCase(name)}`,
        })),
      },
    };
    writeFileSync(`${radiusDir}/tokens.meta.yaml`, toYaml(meta) + '\n');
  }

  // ── typography/ ───────────────────────────────────────────────────────────
  const typoDir = `${outDir}/typography`;
  mkdirSync(typoDir, { recursive: true });

  {
    const L = [HEADER];
    // Primitive font data
    // BTechFontFamily — returns CSS var strings so tenant font overrides cascade automatically.
    // e.g. BTechFontFamily.sans === 'var(--btech-font-family-sans)'
    L.push('export const BTechFontFamily = {');
    for (const [name] of Object.entries(data.typography.fontFamilies)) {
      const cssVar = pathToCssVar(['typography', 'fontFamily', name]);
      L.push(`  ${name}: 'var(${cssVar})',`);
    }
    L.push('} as const;\n');

    L.push('export const BTechFontSize = {');
    for (const [name, value] of Object.entries(data.typography.fontSizes)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  ${safeName}: ${parseFloat(String(value).replace('px', ''))},`);
    }
    L.push('} as const;\n');

    L.push('export const BTechFontWeight = {');
    for (const [name, value] of Object.entries(data.typography.fontWeights)) {
      L.push(`  ${name}: ${Number(value)},`);
    }
    L.push('} as const;\n');

    L.push('export const BTechLineHeight = {');
    for (const [name, value] of Object.entries(data.typography.lineHeights)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  ${safeName}: ${parseFloat(String(value).replace('px', ''))},`);
    }
    L.push('} as const;\n');

    // BTechFont namespace
    L.push('export const BTechFont = {');
    L.push('  heading: {');
    const heading = data.typography.semantic.heading;
    if (heading) {
      if (heading.fontFamily) L.push(`    fontFamily: 'var(${pathToCssVar(['typography', 'fontFamily', 'sans'])})',`);
      if (heading.fontWeight) L.push(`    fontWeight: ${Number(heading.fontWeight)},`);
      if (heading.lineHeight) L.push(`    lineHeight: ${Number(heading.lineHeight)},`);
    }
    L.push('  },');
    L.push('  body: {');
    const body = data.typography.semantic.body;
    if (body) {
      if (body.fontFamily) L.push(`    fontFamily: 'var(${pathToCssVar(['typography', 'fontFamily', 'sans'])})',`);
      if (body.fontSize) L.push(`    fontSize: ${parseFloat(String(body.fontSize).replace('px', ''))},`);
      if (body.fontWeight) L.push(`    fontWeight: ${Number(body.fontWeight)},`);
      if (body.lineHeight) L.push(`    lineHeight: ${Number(body.lineHeight)},`);
    }
    L.push('  },');
    L.push('} as const;\n');

    writeFileSync(`${typoDir}/font.token.ts`, L.join('\n') + '\n');
  }
  writeFileSync(`${typoDir}/index.ts`, [
    "export * from './font.token';",
    "export * from './font-registry';",
    '',
  ].join('\n'));
  {
    const tokens: Array<{ path: string; figmaVariable: string }> = [];
    for (const [group, props] of Object.entries(data.typography.semantic)) {
      for (const prop of Object.keys(props)) {
        tokens.push({
          path: `typography.${group}.${prop}`,
          figmaVariable: `Typography/${toPascalCase(group)}/${toPascalCase(prop)}`,
        });
      }
    }
    const meta = {
      category: 'typography',
      figma: { collection: 'BTech/Typography', tokens },
    };
    writeFileSync(`${typoDir}/tokens.meta.yaml`, toYaml(meta) + '\n');
  }

  // ── Root index.ts — barrel ────────────────────────────────────────────────
  // Preserve existing index.ts (TokenProvider/tokenPlugin) and append exports
  const existingIndex = existsSync(`${outDir}/index.ts`)
    ? readFileSync(`${outDir}/index.ts`, 'utf-8')
    : '';

  const newExports = [
    "export * from './color/index';",
    "export * from './spacing/index';",
    "export * from './shadow/index';",
    "export * from './stroke/index';",
    "export * from './radius/index';",
    "export * from './typography/index';",
  ];

  const missingExports = newExports.filter(e => !existingIndex.includes(e));
  if (missingExports.length > 0) {
    const updatedIndex = existingIndex.trimEnd() + '\n\n// Token exports (auto-generated)\n' + missingExports.join('\n') + '\n';
    writeFileSync(`${outDir}/index.ts`, updatedIndex);
  }
}
