import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import {
  ROOT,
  flattenDTCG,
  resolveRef,
  pathToCssVarStem,
} from '../utils.js';

/**
 * Generates a standalone :root {} CSS file for a single tenant.
 * Merges base resolved token map with tenant overrides.
 * Output: packages/tokens-{tenantId}/dist/styles.css
 *
 * @param tenantId   e.g. 'bspace'
 * @param baseMap    fully resolved base token map from loadTokenData().baseMap
 */
export function generateTenantIsolatedCss(
  tenantId: string,
  baseMap: Record<string, string>,
): void {
  const overridePath = `${ROOT}/sources/tenants/${tenantId}/overrides.json`;
  if (!existsSync(overridePath)) {
    throw new Error(
      `[tenant-isolated] No overrides.json found for tenant "${tenantId}" at ${overridePath}`,
    );
  }

  // Load + flatten tenant overrides
  const rawOverrides = flattenDTCG(
    JSON.parse(readFileSync(overridePath, 'utf-8')),
  );

  // Resolve tenant override refs against base map
  const resolvedOverrides: Record<string, string> = {};
  for (const [k, v] of Object.entries(rawOverrides)) {
    resolvedOverrides[k] = resolveRef(v, baseMap);
  }

  // Merge: base map patched with tenant overrides
  const mergedMap: Record<string, string> = { ...baseMap };
  for (const [path, value] of Object.entries(resolvedOverrides)) {
    // Strip trailing .default from override path for matching
    const cleanPath = path.replace(/\.default$/, '');
    // Update both the exact key and any .default variant
    mergedMap[cleanPath] = value;
    mergedMap[`${cleanPath}.default`] = value;
  }

  // Build CSS lines from merged map — emit only semantic tokens (skip primitives)
  const SKIP_PREFIXES = [
    'color.blue', 'color.red', 'color.green', 'color.orange',
    'color.neutral', 'color.pink', 'color.purple', 'color.teal',
    'color.slate', 'color.yellow',
  ];

  const lines: string[] = [
    '/* AUTO-GENERATED by @btech/design-system — do not edit manually. */',
    `/* Tenant: ${tenantId} — generated from sources/tenants/${tenantId}/overrides.json */`,
    `/* Run \`pnpm generate --tenant ${tenantId}\` to regenerate. */`,
    '',
    ':root {',
  ];

  for (const [path, value] of Object.entries(mergedMap)) {
    if (SKIP_PREFIXES.some(p => path.startsWith(p))) continue;
    // Skip internal refs that weren't resolved
    if (value.startsWith('{')) continue;

    const cleanPath = path.replace(/\.default$/, '');
    const parts = cleanPath.split('.');
    const stem = pathToCssVarStem(parts)
      .replace(/([A-Z])/g, m => `-${m.toLowerCase()}`);
    const cssVar = `--btech-${stem}`;
    lines.push(`  ${cssVar}: ${value};`);
  }

  lines.push('}', '');

  // Deduplicate lines (same cssVar may appear from both .default and plain path)
  const seen = new Set<string>();
  const deduped = lines.filter(line => {
    if (!line.startsWith('  --')) return true;
    if (seen.has(line)) return false;
    seen.add(line);
    return true;
  });

  // Write to packages/tokens-{id}/dist/styles.css
  // ROOT = packages/tokens/, so resolve up two levels to reach monorepo root
  const MONOREPO_ROOT = resolve(ROOT, '../..');
  const outDir = resolve(MONOREPO_ROOT, 'packages', `tokens-${tenantId}`, 'dist');
  mkdirSync(outDir, { recursive: true });

  writeFileSync(resolve(outDir, 'styles.css'), deduped.join('\n'), 'utf-8');
  console.log(`  Tenant CSS  — packages/tokens-${tenantId}/dist/styles.css`);
}
