// Generates per-tenant CSS-only npm packages under packages/tokens/platforms/web/{id}/.
//
// Each package contains:
//   dist/styles.css  — Standalone CSS: starts from the base styles.css, applies
//                      tenant override values into :root in-place, then appends
//                      a [data-mode="dark"] block with tenant-aware dark values.
//                      No JS, no TypeScript, no dependency on @btech/tokens.
//   package.json     — name: "@btech/tokens-{id}", exports only ./styles.css.
//
// Consumer usage:
//   import '@btech/tokens-bspace/styles.css';     // all vars, bspace values in :root
//   import { token, setMode } from '@btech/tokens'; // JS from the base package
//
// Run by sd.config.ts in BASE mode (after appendDarkModeCss so base styles.css is complete).

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import {
  ROOT,
  flattenDTCG,
  resolveRef,
  pathToCssVarStem,
  pathToCssVar,
} from '../utils.js';
import {
  buildColorTree,
  buildDarkResolvedBaseMap,
  buildResolvedBaseMap,
} from '../flutter/flutter-theme-generator.js';

const HEADER = '/* AUTO-GENERATED by @btech/design-system — do not edit manually.\n * Run `pnpm generate` to regenerate from tokens/. */\n';

/** Escape special regex chars in a CSS var name for safe use in RegExp. */
function escapeRegex(s: string): string {
  return s.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
}

/**
 * Generates per-tenant CSS-only npm packages for all tenants in sources/tenants/.
 * Output: packages/tokens/platforms/web/{id}/
 */
export function generateWebTenantPackages(): void {
  const tenantsDir = `${ROOT}/sources/tenants`;
  if (!existsSync(tenantsDir)) return;

  const tenantIds = readdirSync(tenantsDir)
    .filter((d: string) => d !== 'default' && existsSync(`${tenantsDir}/${d}/overrides.json`))
    .sort();

  const lightBaseMap = buildResolvedBaseMap();
  const darkBaseMap  = buildDarkResolvedBaseMap();

  for (const tenantId of tenantIds) {
    generateWebTenantPackage(tenantId, lightBaseMap, darkBaseMap);
  }
}

function generateWebTenantPackage(
  tenantId: string,
  lightBaseMap: Record<string, string>,
  darkBaseMap:  Record<string, string>,
): void {
  const overridePath = `${ROOT}/sources/tenants/${tenantId}/overrides.json`;
  const baseCssPath  = `${ROOT}/platforms/web/token/dist/styles.css`;
  const outDir  = `${ROOT}/platforms/web/${tenantId}`;
  const distDir = `${outDir}/dist`;

  mkdirSync(distDir, { recursive: true });

  // ── Resolve tenant overrides → CSS var override map ───────────────────────
  const rawOverrides = flattenDTCG(
    JSON.parse(readFileSync(overridePath, 'utf-8')),
  );

  const cssVarOverrides: Record<string, string> = {};
  for (const [tokenPath, rawVal] of Object.entries(rawOverrides)) {
    const cleanPath = tokenPath.replace(/\.default$/, '');
    const resolved  = resolveRef(rawVal, lightBaseMap);
    const stem      = pathToCssVarStem(cleanPath.split('.'))
      .replace(/([A-Z])/g, (m: string) => `-${m.toLowerCase()}`);
    cssVarOverrides[`--${stem}`] = resolved;
  }

  // ── styles.css ────────────────────────────────────────────────────────────
  // Start from the fully-built base styles.css (has :root + dark mode block),
  // then replace each overridden var's value inside :root.
  let tenantCss = [
    HEADER,
    `/* Tenant: ${tenantId} — standalone CSS (no import of base package required) */`,
    `/* Overrides: ${Object.keys(cssVarOverrides).join(', ')} */`,
    '',
    readFileSync(baseCssPath, 'utf-8').trim(),
    '',
  ].join('\n');

  for (const [cssVar, overrideValue] of Object.entries(cssVarOverrides)) {
    const varRegex = new RegExp(`(${escapeRegex(cssVar)}:\\s*)([^;]+)(;)`, 'g');
    tenantCss = tenantCss.replace(varRegex, `$1${overrideValue}$3`);
  }

  // ── Replace base [data-mode="dark"] with tenant-aware dark block ─────────
  // Remove the generic dark block written by appendDarkModeCss, then append
  // a fresh one that merges tenant overrides on top of dark base values.
  tenantCss = tenantCss.replace(
    /\/\* ── Dark mode[\s\S]*?\[data-mode="dark"\][\s\S]*?\}\n?/,
    '',
  ).trimEnd();

  const mergedDark: Record<string, string> = { ...darkBaseMap };
  for (const [tokenPath, rawVal] of Object.entries(rawOverrides)) {
    const cleanPath = tokenPath.replace(/\.default$/, '');
    mergedDark[cleanPath] = resolveRef(rawVal, lightBaseMap);
  }

  const colorTree = buildColorTree();
  const darkLines: string[] = [
    '',
    `/* ── Dark mode — ${tenantId} ──────────────────────────────────────────────── */`,
    `[data-mode="dark"] {`,
  ];
  for (const [category, fields] of Object.entries(colorTree)) {
    for (const field of fields) {
      const dotPath = `color.${category}.${field}`;
      const value   = mergedDark[dotPath];
      if (value) {
        const cssVar = pathToCssVar(['color', category, field]);
        darkLines.push(`  ${cssVar}: ${value};`);
      }
    }
  }
  darkLines.push('}', '');

  tenantCss += '\n' + darkLines.join('\n');
  writeFileSync(`${distDir}/styles.css`, tenantCss, 'utf-8');

  // ── package.json (CSS-only — always rewrite to keep in sync) ─────────────
  const pkgJsonPath = `${outDir}/package.json`;

  // Read current version from base package to stay in sync.
  // Exception: when base is an rc.* pre-release, tenants DON'T follow — they
  // only ship on stable releases. Preserve the tenant's existing version.
  const basePkgPath = `${ROOT}/platforms/web/token/package.json`;
  const baseVersion = existsSync(basePkgPath)
    ? JSON.parse(readFileSync(basePkgPath, 'utf-8')).version ?? '1.0.0'
    : '1.0.0';

  let version = baseVersion;
  if (/-rc\./.test(baseVersion) && existsSync(pkgJsonPath)) {
    const existing = JSON.parse(readFileSync(pkgJsonPath, 'utf-8'));
    if (existing.version) version = existing.version;
  }

  const pkgJson = {
    name:        `@btech/tokens-${tenantId}`,
    version,
    description: `BTech design tokens for ${tenantId} — auto-generated, do not edit`,
    exports: {
      './styles.css': './dist/styles.css',
    },
    files: ['dist'],
    publishConfig: {
      registry: 'https://buma.pkgs.visualstudio.com/_packaging/btech/npm/registry/',
    },
  };
  writeFileSync(pkgJsonPath, JSON.stringify(pkgJson, null, 2) + '\n', 'utf-8');

  console.log(`  Web tenant  — platforms/web/${tenantId}/  (@btech/tokens-${tenantId})`);
}
