// Generates per-tenant npm packages under packages/tokens/platforms/web/{id}/.
//
// Each package is a SUPERSET of @btech/tokens — re-exports the entire base
// API and applies its own tenant CSS as a side-effect on import. Developers
// install one package and import once.
//
// Each package contains:
//   src/index.ts     — Re-export from @btech/tokens + side-effect import of
//                      this tenant's styles.css. Compiled to dist/ via tsup.
//   dist/styles.css  — Standalone CSS: starts from the base styles.css, applies
//                      tenant override values into :root in-place, then appends
//                      a [data-mode="dark"] block with tenant-aware dark values.
//   dist/index.{js,mjs,d.ts} — Built by tsup from src/index.ts.
//   package.json     — name: "@btech/tokens-{id}". Has main/module/types,
//                      exports both . (entry) and ./styles.css (CSS-only entry).
//                      Lists @btech/tokens as a regular dependency (not peer)
//                      so consumers don't need a separate install.
//
// Consumer usage (single import):
//   import { token, setMode, BTechSpacing } from '@btech/tokens-bspace';
//   // CSS auto-loaded as side-effect — bspace tenant values active in :root.
//
// Advanced (CSS-only, e.g. for SSR or non-JS tenants):
//   import '@btech/tokens-bspace/styles.css';
//
// Run by sd.config.ts in BASE mode (after appendDarkModeCss so base styles.css is complete).

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import {
  ROOT,
  flattenDTCG,
  resolveRef,
  pathToCssVarStem,
  pathToCssVar,
} from '../utils.js';
import {
  buildColorTree,
  buildDarkResolvedBaseMap,
  buildResolvedBaseMap,
} from '../flutter/flutter-theme-generator.js';

const HEADER = '/* AUTO-GENERATED by @btech/design-system — do not edit manually.\n * Run `pnpm generate` to regenerate from tokens/. */\n';

/** Escape special regex chars in a CSS var name for safe use in RegExp. */
function escapeRegex(s: string): string {
  return s.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
}

/**
 * Generates per-tenant CSS-only npm packages for all tenants in sources/tenants/.
 * Output: packages/tokens/platforms/web/{id}/
 */
export function generateWebTenantPackages(): void {
  const tenantsDir = `${ROOT}/sources/tenants`;
  if (!existsSync(tenantsDir)) return;

  const tenantIds = readdirSync(tenantsDir)
    .filter((d: string) => d !== 'default' && existsSync(`${tenantsDir}/${d}/overrides.json`))
    .sort();

  const lightBaseMap = buildResolvedBaseMap();
  const darkBaseMap  = buildDarkResolvedBaseMap();

  for (const tenantId of tenantIds) {
    generateWebTenantPackage(tenantId, lightBaseMap, darkBaseMap);
  }
}

function generateWebTenantPackage(
  tenantId: string,
  lightBaseMap: Record<string, string>,
  darkBaseMap:  Record<string, string>,
): void {
  const overridePath = `${ROOT}/sources/tenants/${tenantId}/overrides.json`;
  const baseCssPath  = `${ROOT}/platforms/web/token/dist/styles.css`;
  const outDir  = `${ROOT}/platforms/web/${tenantId}`;
  const srcDir  = `${outDir}/src`;
  const distDir = `${outDir}/dist`;

  mkdirSync(srcDir,  { recursive: true });
  mkdirSync(distDir, { recursive: true });

  // ── Resolve tenant overrides → CSS var override map ───────────────────────
  const rawOverrides = flattenDTCG(
    JSON.parse(readFileSync(overridePath, 'utf-8')),
  );

  const cssVarOverrides: Record<string, string> = {};
  for (const [tokenPath, rawVal] of Object.entries(rawOverrides)) {
    const cleanPath = tokenPath.replace(/\.default$/, '');
    const resolved  = resolveRef(rawVal, lightBaseMap);
    const stem      = pathToCssVarStem(cleanPath.split('.'))
      .replace(/([A-Z])/g, (m: string) => `-${m.toLowerCase()}`);
    cssVarOverrides[`--${stem}`] = resolved;
  }

  // ── styles.css ────────────────────────────────────────────────────────────
  // Start from the fully-built base styles.css (has :root + dark mode block),
  // then replace each overridden var's value inside :root.
  let tenantCss = [
    HEADER,
    `/* Tenant: ${tenantId} — standalone CSS (no import of base package required) */`,
    `/* Overrides: ${Object.keys(cssVarOverrides).join(', ')} */`,
    '',
    readFileSync(baseCssPath, 'utf-8').trim(),
    '',
  ].join('\n');

  for (const [cssVar, overrideValue] of Object.entries(cssVarOverrides)) {
    const varRegex = new RegExp(`(${escapeRegex(cssVar)}:\\s*)([^;]+)(;)`, 'g');
    tenantCss = tenantCss.replace(varRegex, `$1${overrideValue}$3`);
  }

  // ── Replace base [data-mode="dark"] with tenant-aware dark block ─────────
  // Remove the generic dark block written by appendDarkModeCss, then append
  // a fresh one that merges tenant overrides on top of dark base values.
  tenantCss = tenantCss.replace(
    /\/\* ── Dark mode[\s\S]*?\[data-mode="dark"\][\s\S]*?\}\n?/,
    '',
  ).trimEnd();

  const mergedDark: Record<string, string> = { ...darkBaseMap };
  for (const [tokenPath, rawVal] of Object.entries(rawOverrides)) {
    const cleanPath = tokenPath.replace(/\.default$/, '');
    mergedDark[cleanPath] = resolveRef(rawVal, lightBaseMap);
  }

  const colorTree = buildColorTree();
  const darkLines: string[] = [
    '',
    `/* ── Dark mode — ${tenantId} ──────────────────────────────────────────────── */`,
    `[data-mode="dark"] {`,
  ];
  for (const [category, fields] of Object.entries(colorTree)) {
    for (const field of fields) {
      const dotPath = `color.${category}.${field}`;
      const value   = mergedDark[dotPath];
      if (value) {
        const cssVar = pathToCssVar(['color', category, field]);
        darkLines.push(`  ${cssVar}: ${value};`);
      }
    }
  }
  darkLines.push('}', '');

  tenantCss += '\n' + darkLines.join('\n');
  writeFileSync(`${distDir}/styles.css`, tenantCss, 'utf-8');

  // ── src/index.ts — single-import re-export entrypoint ────────────────────
  // Side-effect import of styles.css applies tenant CSS variables to :root.
  // Re-export from @btech/tokens gives consumers the full TS API (BTechColor,
  // setMode, BTechSpacing, token(), …) without a second install.
  const tenantIndexTs = [
    '// AUTO-GENERATED by @btech/design-system — do not edit manually.',
    '// Run `pnpm generate` to regenerate.',
    '',
    `// Side-effect: load this tenant's CSS variables into :root.`,
    `import './styles.css';`,
    '',
    `// Re-export the entire base @btech/tokens API.`,
    `// Consumers import once: \`import { token, setMode, BTechColor } from '@btech/tokens-${tenantId}'\`.`,
    `export * from '@btech/tokens';`,
    '',
  ].join('\n');
  writeFileSync(`${srcDir}/index.ts`, tenantIndexTs, 'utf-8');

  // ── tsconfig.json (used by tsup at build time) ────────────────────────────
  const tsconfigPath = `${outDir}/tsconfig.json`;
  if (!existsSync(tsconfigPath)) {
    const tsconfig = {
      extends: '../../../../../tsconfig.base.json',
      compilerOptions: {
        outDir: './dist',
        rootDir: './src',
      },
      include: ['src/**/*'],
    };
    writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + '\n', 'utf-8');
  }

  // ── tsup.config.ts ────────────────────────────────────────────────────────
  // Mark `./styles.css` as external so tsup/esbuild leaves the import statement
  // untouched in dist/index.{js,mjs}. At consume-time, bundlers (Vite, webpack,
  // Rollup) resolve the relative import against dist/ and find the standalone
  // styles.css that this generator wrote — preserving the side-effect contract.
  // Always rewrite to keep the build config in sync with generator changes.
  const tsupConfig = [
    '// AUTO-GENERATED by @btech/design-system — do not edit manually.',
    `import { defineConfig } from 'tsup';`,
    '',
    'export default defineConfig({',
    `  entry:    ['src/index.ts'],`,
    `  format:   ['cjs', 'esm'],`,
    '  dts:      true,',
    '  clean:    false,',
    '  // styles.css lives in dist/ already (written by the token generator);',
    '  // marking it external preserves the side-effect import in the output.',
    `  external: [/\\.css$/],`,
    '});',
    '',
  ].join('\n');
  writeFileSync(`${outDir}/tsup.config.ts`, tsupConfig, 'utf-8');

  // ── package.json — full re-export package (always rewrite to keep in sync)
  const pkgJsonPath = `${outDir}/package.json`;

  // Hybrid versioning contract:
  //   * tenant `version` is preserved across regenerations — tenant only
  //     bumps when its own source changes (or when an explicit scope=all
  //     bump is used).
  //   * `dependencies['@btech/tokens']` is fixed at `workspace:^`. At publish
  //     time pnpm replaces this with `^<resolved-version>` (e.g. `^1.0.0-rc.11`),
  //     which translates to `>=1.0.0-rc.11 <2.0.0` — the same shape the previous
  //     hand-written ranges used, but now derived automatically from the actual
  //     workspace base version. During local dev pnpm resolves it to the in-repo
  //     workspace package, so frozen-lockfile installs in CI no longer go stale
  //     when the tenant lockfile entry doesn't match a freshly-written range.
  //
  // Seed source: the repo-root package.json holds the canonical platform
  // version (single source of truth). Reading from root rather than from
  // the web base package keeps the seed platform-agnostic — the same
  // number is used to seed Flutter and Python tenants.
  const rootPkgPath = `${ROOT}/../../package.json`; // packages/tokens/ → repo root
  const baseVersion: string = existsSync(rootPkgPath)
    ? JSON.parse(readFileSync(rootPkgPath, 'utf-8')).version ?? '1.0.0'
    : '1.0.0';

  const existingPkg = existsSync(pkgJsonPath)
    ? JSON.parse(readFileSync(pkgJsonPath, 'utf-8'))
    : null;

  const version: string = existingPkg?.version ?? baseVersion;
  const baseDepRange = 'workspace:^';

  const pkgJson = {
    name:        `@btech/tokens-${tenantId}`,
    version,
    description: `BTech design tokens for ${tenantId} — single-import superset of @btech/tokens`,
    main:    './dist/index.js',
    module:  './dist/index.mjs',
    types:   './dist/index.d.ts',
    exports: {
      '.': {
        types:   './dist/index.d.ts',
        import:  './dist/index.mjs',
        require: './dist/index.js',
      },
      './styles.css': './dist/styles.css',
    },
    // styles.css side-effect MUST NOT be tree-shaken away by bundlers.
    sideEffects: ['./dist/styles.css', './dist/index.mjs', './dist/index.js'],
    files: ['dist'],
    scripts: {
      // tsup compiles src/index.ts → dist/{index.js,index.mjs,index.d.ts}.
      // styles.css is written separately by this generator and lives alongside.
      // We mark `./styles.css` as external so tsup leaves the import statement
      // untouched in the output — at consume-time, bundlers resolve it relative
      // to dist/, finding the standalone styles.css we wrote here.
      build: 'tsup --config tsup.config.ts',
      // Runs automatically before `pnpm publish`. Ensures dist/index.{js,mjs,d.ts}
      // are built by tsup before the tarball is packed — `pnpm generate` only writes
      // styles.css + src/index.ts; without this hook the published package ships
      // without JS/TS files (the rc.12 regression).
      prepublishOnly: 'tsup --config tsup.config.ts',
    },
    // @btech/tokens is a runtime dep — consumers should NOT need to install it
    // separately. Range is preserved across regenerations; bump deliberately.
    dependencies: {
      '@btech/tokens': baseDepRange,
    },
    devDependencies: {
      tsup:       '^8.0.2',
      typescript: '^5.4.5',
    },
    publishConfig: {
      registry: 'https://buma.pkgs.visualstudio.com/_packaging/btech/npm/registry/',
    },
  };
  writeFileSync(pkgJsonPath, JSON.stringify(pkgJson, null, 2) + '\n', 'utf-8');

  console.log(`  Web tenant  — platforms/web/${tenantId}/  (@btech/tokens-${tenantId})`);
}
