import { readFileSync, readdirSync, existsSync, writeFileSync } from 'fs';
import { ROOT, flattenDTCG, pathToCssVarStem } from '../utils.js';

/** Generate token.ts — TokenPath union type + token() and cssVar() helpers. */
export function generateTokenTypes(webSrcPath: string): void {
  const dirs = [
    `${ROOT}/sources/core`,
    `${ROOT}/sources/semantic`,
    `${ROOT}/sources/components`,
  ];

  const allPaths = new Set<string>();
  for (const dir of dirs) {
    if (!existsSync(dir)) continue;
    for (const file of readdirSync(dir)) {
      if (!file.endsWith('.json')) continue;
      const flat = flattenDTCG(JSON.parse(readFileSync(`${dir}/${file}`, 'utf-8')));
      for (const rawPath of Object.keys(flat)) {
        allPaths.add(rawPath.replace(/\.default$/, ''));
      }
    }
  }

  // Add composite typography token paths (font shorthand vars).
  // These are generated by web-generator.ts from typeScale JSON entries
  // and map to CSS custom properties like --typography-heading-h1.
  const typoJson = JSON.parse(
    readFileSync(`${ROOT}/sources/semantic/typography.json`, 'utf-8')
  ) as { typography?: { typeScale?: Record<string, Record<string, unknown>> } };
  const typeScale = typoJson.typography?.typeScale ?? {};
  for (const [category, entries] of Object.entries(typeScale)) {
    for (const name of Object.keys(entries)) {
      allPaths.add(`typography.${category}.${name}`);
    }
  }

  const sorted = [...allPaths].sort();
  const unionLines = sorted.map(p => `  | '${p}'`).join('\n');

  const out = [
    `// AUTO-GENERATED by @btech/design-system — do not edit manually.`,
    `// Run \`pnpm generate\` to regenerate from tokens/.`,
    ``,
    `/**`,
    ` * All valid BTech design token paths.`,
    ` * Grammar: [category].[property].[role].[emphasis].[state]`,
    ` *`,
    ` * @example`,
    ` * 'color.bg.primary'                — primary background color`,
    ` * 'color.text.secondary'           — secondary text color`,
    ` * 'spacing.md'                      — medium spacing (12px)`,
    ` * 'radius.sm'                       — small border radius (8px)`,
    ` */`,
    `export type TokenPath =`,
    unionLines,
    ``,
    `// =============================================================================`,
    `// CSS variable naming (no vendor prefix)`,
    `// =============================================================================`,
    `// styles.css defines every token as a CSS custom property:`,
    `//   :root {`,
    `//     --bg-primary: #...;                  (color — category dropped)`,
    `//     --space-md: 16px;                    (spacing → space)`,
    `//     --typography-font-family-sans: ...;  (typography — category kept)`,
    `//     --border-neutral: #...;              (color.stroke → border)`,
    `//     --duration-fast: 100ms;              (motion — category dropped)`,
    `//     --z-modal: 400;                      (zIndex → z)`,
    `//   }`,
    `//`,
    `// token() returns the identical var() — same as writing it by hand in CSS.`,
    `// Dark mode via [data-mode="dark"] works automatically for both.`,
    `// =============================================================================`,
    ``,
    `// Internal: same logic as pathToCssVarStem() in config/generators/utils.ts`,
    `const PRIMITIVE_COLORS = new Set(['blue','red','green','orange','neutral','yellow','pink','purple','teal','slate']);`,
    `function _pathToVarName(dotPath: string): string {`,
    `  const [cat, ...rest] = dotPath.split('.');`,
    `  let stem: string;`,
    `  switch (cat) {`,
    `    case 'color': {`,
    `      const sub = rest[0];`,
    `      if (PRIMITIVE_COLORS.has(sub)) { stem = ['color', ...rest].join('-'); break; }`,
    `      if (sub === 'stroke')          { stem = ['border', ...rest.slice(1)].join('-'); break; }`,
    `      stem = rest.join('-'); break;`,
    `    }`,
    `    case 'spacing': stem = ['space', ...rest].join('-'); break;`,
    `    case 'typography': stem = [cat, ...rest].join('-'); break;`,
    `    case 'zIndex': stem = ['z', ...rest].join('-'); break;`,
    `    case 'motion': stem = rest.join('-'); break;`,
    `    default: stem = [cat, ...rest].join('-');`,
    `  }`,
    `  return stem.replace(/([A-Z])/g, m => \`-\${m.toLowerCase()}\`);`,
    `}`,
    ``,
    `/**`,
    ` * Returns the CSS custom property reference for any design token.`,
    ` * Atlassian-aligned: category is dropped from the var name.`,
    ` *`,
    ` * ── Color ────────────────────────────────────────────────────────────────────`,
    ` * token('color.bg.primary')           → var(--bg-primary)`,
    ` * token('color.text.primary')         → var(--text-primary)`,
    ` * token('color.icon.success')         → var(--icon-success)`,
    ` * token('color.border.primary')       → var(--border-primary)`,
    ` * token('color.brand.primary')        → var(--brand-primary)`,
    ` * token('color.ext.success-subtler')  → var(--ext-success-subtler)`,
    ` * token('color.blue.500')             → var(--color-blue-500)`,
    ` *`,
    ` * ── Spacing ─────────────────────────────────────────────────────────────────`,
    ` * token('spacing.xs')   → var(--space-xs)`,
    ` * token('spacing.md')   → var(--space-md)`,
    ` *`,
    ` * ── Radius / Shadow ─────────────────────────────────────────────────────────`,
    ` * token('radius.sm')              → var(--radius-sm)`,
    ` * token('shadow.elevation.md')    → var(--shadow-elevation-md)`,
    ` *`,
    ` * ── Typography ─────────────────────────────────────────────────────────────`,
    ` * token('typography.fontFamily.sans')     → var(--typography-font-family-sans)`,
    ` * token('typography.fontSize.sm')         → var(--typography-font-size-sm)`,
    ` * token('typography.heading.h1')          → var(--typography-heading-h1)`,
    ` * token('typography.body.regular')        → var(--typography-body-regular)`,
    ` *`,
    ` * ── Motion / Z-Index ───────────────────────────────────────────────────────`,
    ` * token('motion.duration.fast')  → var(--duration-fast)`,
    ` * token('motion.easing.ease')    → var(--easing-ease)`,
    ` * token('zIndex.modal')          → var(--z-modal)`,
    ` *`,
    ` * ── With fallback ───────────────────────────────────────────────────────────`,
    ` * token('color.bg.primary', '#fff') → var(--bg-primary, #fff)`,
    ` */`,
    `export function token(path: TokenPath, fallback?: string): string {`,
    `  const varName = \`--\${_pathToVarName(path)}\`;`,
    `  return fallback ? \`var(\${varName}, \${fallback})\` : \`var(\${varName})\`;`,
    `}`,
    ``,
    `/**`,
    ` * Raw CSS variable name — no var() wrapper.`,
    ` * Use for setProperty(), CSS-in-JS that wraps var() itself, or calc().`,
    ` *`,
    ` * cssVar('color.bg.primary')              → '--bg-primary'`,
    ` * cssVar('typography.fontFamily.sans')    → '--typography-font-family-sans'`,
    ` * element.style.setProperty(cssVar('color.bg.primary'), '#0057b7');`,
    ` */`,
    `export function cssVar(path: TokenPath): string {`,
    `  return \`--\${_pathToVarName(path)}\`;`,
    `}`,
    ``,
    `/**`,
    ` * Wraps a token in calc().`,
    ` *`,
    ` * tokenCalc('spacing.md', '* 2')    → 'calc(var(--space-md) * 2)'`,
    ` * tokenCalc('spacing.sm', '+ 4px')  → 'calc(var(--space-sm) + 4px)'`,
    ` */`,
    `export function tokenCalc(path: TokenPath, expression: string): string {`,
    `  return \`calc(\${token(path)} \${expression})\`;`,
    `}`,
    ``,
  ].join('\n');

  writeFileSync(`${webSrcPath}token.ts`, out, 'utf-8');
}
