// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'font.theme.dart';

/// Body text styles.
/// Instance itself IS the regular (14px/w400) style.
/// Font family is tenant-aware — driven by BTechTypography.fontFamily.
///
/// ```dart
/// Text('Body',  style: BTechTypography.body.regular)
/// Text('Bold',  style: BTechTypography.body.regularB)
/// Text('Small', style: BTechTypography.body.small)
/// ```
class BTechTypographyBody extends TextStyle {
  BTechTypographyBody()
      : super(
          fontFamily: BTechTypography.fontFamily,
          fontSize: 14,
          fontWeight: FontWeight.w400,
          height: 16 / 14,
        );

  /// large — 16px · w400 · lineHeight: 20/16 = 1.250
  final TextStyle large = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 16, fontWeight: FontWeight.w400, height: 20 / 16);

  /// regular — 14px · w400 · lineHeight: 16/14 = 1.143
  final TextStyle regular = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 14, fontWeight: FontWeight.w400, height: 16 / 14);

  /// small — 12px · w400 · lineHeight: 16/12 = 1.333
  final TextStyle small = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 12, fontWeight: FontWeight.w400, height: 16 / 12);

  /// xtrasmall — 10px · w400 · lineHeight: 16/10 = 1.600
  final TextStyle xtrasmall = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 10, fontWeight: FontWeight.w400, height: 16 / 10);

  /// micro — 8px · w400 · lineHeight: 12/8 = 1.500
  final TextStyle micro = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 8, fontWeight: FontWeight.w400, height: 12 / 8);

  /// largeB — 16px · w700 · lineHeight: 20/16 = 1.250
  final TextStyle largeB = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 16, fontWeight: FontWeight.w700, height: 20 / 16);

  /// regularB — 14px · w700 · lineHeight: 16/14 = 1.143
  final TextStyle regularB = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 14, fontWeight: FontWeight.w700, height: 16 / 14);

  /// smallB — 12px · w700 · lineHeight: 16/12 = 1.333
  final TextStyle smallB = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 12, fontWeight: FontWeight.w700, height: 16 / 12);

  /// xtrasmallB — 10px · w700 · lineHeight: 16/10 = 1.600
  final TextStyle xtrasmallB = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 10, fontWeight: FontWeight.w700, height: 16 / 10);

  /// microB — 8px · w700 · lineHeight: 12/8 = 1.500
  final TextStyle microB = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 8, fontWeight: FontWeight.w700, height: 12 / 8);

}

