// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'heading.dart';
import 'subheading.dart';
import 'body.dart';

/// Primitive font family tokens.
abstract class BTechFontFamily {
  static const String sans = 'Inter';
  static const String mono = 'JetBrains Mono';
}

/// Primitive font size tokens.
abstract class BTechFontSize {
  static const double s3xs = 8;
  static const double s2xs = 10;
  static const double xs = 12;
  static const double sm = 14;
  static const double md = 16;
  static const double lg = 18;
  static const double xl = 20;
  static const double s2xl = 24;
  static const double s3xl = 28;
  static const double s4xl = 32;
  static const double s5xl = 40;
}

/// Primitive font weight tokens.
abstract class BTechFontWeight {
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight semibold = FontWeight.w600;
  static const FontWeight bold = FontWeight.w700;
}

/// Primitive line height tokens (pixels).
abstract class BTechLineHeight {
  static const double s2xs = 12;
  static const double xs = 16;
  static const double sm = 20;
  static const double md = 24;
  static const double lg = 28;
  static const double xl = 32;
  static const double s2xl = 36;
  static const double s3xl = 40;
  static const double s4xl = 48;
}

/// Root static font namespace — always uses the default sans font family.
/// For tenant-aware fonts in widgets, prefer [context.btechFont].
abstract class BTechFont {
  static final BTechFontHeading    heading    = BTechFontHeading();
  static final BTechFontSubHeading subheading = BTechFontSubHeading();
  static final BTechFontBody       body       = BTechFontBody();
}

