// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'heading.dart';
import 'subheading.dart';
import 'body.dart';

/// Font-family data class — holds the active sans-serif family name.
class BTechFontFamily {
  const BTechFontFamily({required this.sans});
  final String sans;
}

class BTechFontTheme extends ThemeExtension<BTechFontTheme> {
  const BTechFontTheme({required this.family});
  final BTechFontFamily family;

  BTechFontTheme copyWith({BTechFontFamily? family}) =>
      BTechFontTheme(family: family ?? this.family);

  @override
  BTechFontTheme lerp(covariant ThemeExtension<BTechFontTheme>? other, double t) => this;
}

/// Static access to the active font theme.
/// - BTechFont.family.sans         — active sans-serif family name (tenant-switchable)
/// - BTechFont.heading.h1          — TextStyle (always uses active font family)
/// - BTechFont.body.medium         — TextStyle
/// For reactive dark/light font colours in widgets, prefer context.btechFont.
abstract class BTechFont {
  static BTechFontTheme _active = const BTechFontTheme(
    family: BTechFontFamily(sans: 'Inter'),
  );

  static BTechFontFamily get family => _active.family;

  /// Semantic typography scale — TextStyle instances derived from the active font.
  static final BTechFontHeading    heading    = BTechFontHeading();
  static final BTechFontSubHeading subheading = BTechFontSubHeading();
  static final BTechFontBody       body       = BTechFontBody();

  static void activate(BTechFontTheme t) => _active = t;
}
