// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechFontFamily {
  const BTechFontFamily({required this.sans});
  final String sans;
}

class BTechFontTheme extends ThemeExtension<BTechFontTheme> {
  const BTechFontTheme({required this.family});
  final BTechFontFamily family;

  @override
  BTechFontTheme copyWith({BTechFontFamily? family}) =>
      BTechFontTheme(family: family ?? this.family);

  @override
  BTechFontTheme lerp(ThemeExtension<BTechFontTheme>? other, double t) => this;
}

/// Static access to the active font theme.
abstract class BTechFont {
  static BTechFontTheme _active = const BTechFontTheme(
    family: BTechFontFamily(sans: 'Inter'),
  );

  static BTechFontFamily get family => _active.family;

  static void activate(BTechFontTheme t) => _active = t;
}
