// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechBackgroundSurfaceColor extends Color {
  const BTechBackgroundSurfaceColor()
    : subtle = const Color(0xFFECEDEE),
      raised = const Color(0xFFFFFFFF),
      subtler = const Color(0xFFDBDDE1),
      tertiary = const Color(0xFF64748B),
      inverse = const Color(0xFF181C20),
      overlay = const Color(0xFFRGBA(24,28,32,0.8)),
      super(0xFFF4F5F6);
  final Color subtle;
  final Color raised;
  final Color subtler;
  final Color tertiary;
  final Color inverse;
  final Color overlay;
}

class BTechBackgroundPrimaryColor extends Color {
  const BTechBackgroundPrimaryColor()
    : hover = const Color(0xFF0A853E),
      pressed = const Color(0xFF0A632F),
      disable = const Color(0xFFDBDDE1),
      subtle = const Color(0xFFF0F8F4),
      bolder = const Color(0xFF0A853E),
      super(0xFF08A94C);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundSecondaryColor extends Color {
  const BTechBackgroundSecondaryColor()
    : hover = const Color(0xFFE2F3E9),
      pressed = const Color(0xFFC5EAD5),
      disable = const Color(0xFFECEDEE),
      subtle = const Color(0xFFF4F5F6),
      bolder = const Color(0xFFC5EAD5),
      super(0xFFF0F8F4);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundDangerColor extends Color {
  const BTechBackgroundDangerColor()
    : hover = const Color(0xFFD81818),
      pressed = const Color(0xFF991515),
      disable = const Color(0xFFDBDDE1),
      subtle = const Color(0xFFF9F2F2),
      bolder = const Color(0xFF991515),
      super(0xFFEF4444);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundSuccessColor extends Color {
  const BTechBackgroundSuccessColor()
    : hover = const Color(0xFF0A853E),
      pressed = const Color(0xFF0A632F),
      disable = const Color(0xFFDBDDE1),
      subtle = const Color(0xFFF0F8F4),
      bolder = const Color(0xFF0A632F),
      super(0xFF08A94C);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundWarningColor extends Color {
  const BTechBackgroundWarningColor()
    : hover = const Color(0xFFBD7C0C),
      pressed = const Color(0xFF885A0D),
      disable = const Color(0xFFDBDDE1),
      subtle = const Color(0xFFF9F6F1),
      bolder = const Color(0xFF885A0D),
      super(0xFFF59E0B);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundInfoColor extends Color {
  const BTechBackgroundInfoColor()
    : hover = const Color(0xFF0F81B4),
      pressed = const Color(0xFF0F5E81),
      disable = const Color(0xFFDBDDE1),
      subtle = const Color(0xFFF1F6F9),
      bolder = const Color(0xFF0F5E81),
      super(0xFF0EA5E9);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundNeutralColor extends Color {
  const BTechBackgroundNeutralColor()
    : subtle = const Color(0xFFF4F5F6),
      bolder = const Color(0xFFDBDDE1),
      super(0xFFECEDEE);
  final Color subtle;
  final Color bolder;
}

/// Semantic background color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechBackgroundColor.surface → Color
class BTechBackgroundColor {
  const BTechBackgroundColor()
    : surface = const BTechBackgroundSurfaceColor(),
      primary = const BTechBackgroundPrimaryColor(),
      secondary = const BTechBackgroundSecondaryColor(),
      danger = const BTechBackgroundDangerColor(),
      success = const BTechBackgroundSuccessColor(),
      warning = const BTechBackgroundWarningColor(),
      info = const BTechBackgroundInfoColor(),
      neutral = const BTechBackgroundNeutralColor();
  final BTechBackgroundSurfaceColor surface;
  final BTechBackgroundPrimaryColor primary;
  final BTechBackgroundSecondaryColor secondary;
  final BTechBackgroundDangerColor danger;
  final BTechBackgroundSuccessColor success;
  final BTechBackgroundWarningColor warning;
  final BTechBackgroundInfoColor info;
  final BTechBackgroundNeutralColor neutral;
}

