// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// A [Color] that also exposes named variants (hover, pressed, etc.).
/// Every leaf in the color token tree IS a [Color] (default value)
/// and additionally exposes named variant [Color]s. Variants that do not
/// exist in the source token fall back to the default color value.
class BTechColorVariants extends Color {
  const BTechColorVariants(
    super.value, {
    required this.hover,
    required this.pressed,
    required this.subtle,
    required this.raised,
    required this.disable,
    required this.bolder,
    required this.inverse,
    required this.strong,
    required this.disabled,
  });

  final Color hover, pressed, subtle, raised, disable, bolder, inverse, strong, disabled;
}

class BTechColorBackground {
  const BTechColorBackground({
    required this.surface,
    required this.primary,
    required this.secondary,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.neutral,
  });

  final BTechColorVariants surface;
  final BTechColorVariants primary;
  final BTechColorVariants secondary;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants neutral;
}

class BTechColorText {
  const BTechColorText({
    required this.neutral,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorIcon {
  const BTechColorIcon({
    required this.neutral,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorStroke {
  const BTechColorStroke({
    required this.neutral,
    required this.primary,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants primary;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorTheme extends ThemeExtension<BTechColorTheme> {
  const BTechColorTheme({
    required this.background,
    required this.text,
    required this.icon,
    required this.stroke,
  });

  final BTechColorBackground background;
  final BTechColorText       text;
  final BTechColorIcon       icon;
  final BTechColorStroke     stroke;

  BTechColorTheme copyWith({
    BTechColorBackground? background,
    BTechColorText? text,
    BTechColorIcon? icon,
    BTechColorStroke? stroke,
  }) =>
      BTechColorTheme(
        background: background ?? this.background,
        text:       text       ?? this.text,
        icon:       icon       ?? this.icon,
        stroke:     stroke     ?? this.stroke,
      );

  @override
  BTechColorTheme lerp(covariant ThemeExtension<BTechColorTheme>? other, double t) {
    if (other is! BTechColorTheme) return this;
    return this;
  }
}

// ── Default light theme (resolved from semantic/color.json) ─────
const BTechColorTheme _defaultLight = BTechColorTheme(
  background: BTechColorBackground(
    surface: BTechColorVariants(0xFFF9FAFB,
      hover: Color(0xFFF9FAFB),
      pressed: Color(0xFFF9FAFB),
      subtle: Color(0xFFF3F4F6),
      raised: Color(0xFFFFFFFF),
      disable: Color(0xFFF9FAFB),
      bolder: Color(0xFFF9FAFB),
      inverse: Color(0xFFF9FAFB),
      strong: Color(0xFFF9FAFB),
      disabled: Color(0xFFF9FAFB),
    ),
    primary: BTechColorVariants(0xFF15803D,
      hover: Color(0xFF166534),
      pressed: Color(0xFF14532D),
      subtle: Color(0xFFF0FDF4),
      raised: Color(0xFF15803D),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFF166534),
      inverse: Color(0xFF15803D),
      strong: Color(0xFF15803D),
      disabled: Color(0xFF15803D),
    ),
    secondary: BTechColorVariants(0xFFF0FDF4,
      hover: Color(0xFFDCFCE7),
      pressed: Color(0xFFBBF7D0),
      subtle: Color(0xFFF9FAFB),
      raised: Color(0xFFF0FDF4),
      disable: Color(0xFFF3F4F6),
      bolder: Color(0xFFBBF7D0),
      inverse: Color(0xFFF0FDF4),
      strong: Color(0xFFF0FDF4),
      disabled: Color(0xFFF0FDF4),
    ),
    danger: BTechColorVariants(0xFFDC2626,
      hover: Color(0xFFB91C1C),
      pressed: Color(0xFF991B1B),
      subtle: Color(0xFFFEF2F2),
      raised: Color(0xFFDC2626),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFF991B1B),
      inverse: Color(0xFFDC2626),
      strong: Color(0xFFDC2626),
      disabled: Color(0xFFDC2626),
    ),
    success: BTechColorVariants(0xFF22C55E,
      hover: Color(0xFF16A34A),
      pressed: Color(0xFF15803D),
      subtle: Color(0xFFF0FDF4),
      raised: Color(0xFF22C55E),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFF15803D),
      inverse: Color(0xFF22C55E),
      strong: Color(0xFF22C55E),
      disabled: Color(0xFF22C55E),
    ),
    warning: BTechColorVariants(0xFFFB923C,
      hover: Color(0xFFF97316),
      pressed: Color(0xFFEA580C),
      subtle: Color(0xFFFFF7ED),
      raised: Color(0xFFFB923C),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFFEA580C),
      inverse: Color(0xFFFB923C),
      strong: Color(0xFFFB923C),
      disabled: Color(0xFFFB923C),
    ),
    info: BTechColorVariants(0xFF2563EB,
      hover: Color(0xFF1D4ED8),
      pressed: Color(0xFF1E40AF),
      subtle: Color(0xFFEFF6FF),
      raised: Color(0xFF2563EB),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFF1E40AF),
      inverse: Color(0xFF2563EB),
      strong: Color(0xFF2563EB),
      disabled: Color(0xFF2563EB),
    ),
    neutral: BTechColorVariants(0xFFF3F4F6,
      hover: Color(0xFFF3F4F6),
      pressed: Color(0xFFF3F4F6),
      subtle: Color(0xFFF9FAFB),
      raised: Color(0xFFF3F4F6),
      disable: Color(0xFFF3F4F6),
      bolder: Color(0xFFE5E7EB),
      inverse: Color(0xFFF3F4F6),
      strong: Color(0xFFF3F4F6),
      disabled: Color(0xFFF3F4F6),
    ),
  ),
  text: BTechColorText(
    neutral: BTechColorVariants(0xFF111827,
      hover: Color(0xFF111827),
      pressed: Color(0xFF111827),
      subtle: Color(0xFF6B7280),
      raised: Color(0xFF111827),
      disable: Color(0xFF111827),
      bolder: Color(0xFF111827),
      inverse: Color(0xFFF9FAFB),
      strong: Color(0xFF111827),
      disabled: Color(0xFFD1D5DB),
    ),
    danger: BTechColorVariants(0xFFDC2626,
      hover: Color(0xFFDC2626),
      pressed: Color(0xFFDC2626),
      subtle: Color(0xFFDC2626),
      raised: Color(0xFFDC2626),
      disable: Color(0xFFDC2626),
      bolder: Color(0xFF991B1B),
      inverse: Color(0xFFDC2626),
      strong: Color(0xFFDC2626),
      disabled: Color(0xFFDC2626),
    ),
    success: BTechColorVariants(0xFF16A34A,
      hover: Color(0xFF16A34A),
      pressed: Color(0xFF16A34A),
      subtle: Color(0xFF16A34A),
      raised: Color(0xFF16A34A),
      disable: Color(0xFF16A34A),
      bolder: Color(0xFF166534),
      inverse: Color(0xFF16A34A),
      strong: Color(0xFF16A34A),
      disabled: Color(0xFF16A34A),
    ),
    warning: BTechColorVariants(0xFFEA580C,
      hover: Color(0xFFEA580C),
      pressed: Color(0xFFEA580C),
      subtle: Color(0xFFEA580C),
      raised: Color(0xFFEA580C),
      disable: Color(0xFFEA580C),
      bolder: Color(0xFF9A3412),
      inverse: Color(0xFFEA580C),
      strong: Color(0xFFEA580C),
      disabled: Color(0xFFEA580C),
    ),
    info: BTechColorVariants(0xFF2563EB,
      hover: Color(0xFF2563EB),
      pressed: Color(0xFF2563EB),
      subtle: Color(0xFF2563EB),
      raised: Color(0xFF2563EB),
      disable: Color(0xFF2563EB),
      bolder: Color(0xFF1E40AF),
      inverse: Color(0xFF2563EB),
      strong: Color(0xFF2563EB),
      disabled: Color(0xFF2563EB),
    ),
    secondary: BTechColorVariants(0xFF9333EA,
      hover: Color(0xFF9333EA),
      pressed: Color(0xFF9333EA),
      subtle: Color(0xFF9333EA),
      raised: Color(0xFF9333EA),
      disable: Color(0xFF9333EA),
      bolder: Color(0xFF6B21A8),
      inverse: Color(0xFF9333EA),
      strong: Color(0xFF9333EA),
      disabled: Color(0xFF9333EA),
    ),
  ),
  icon: BTechColorIcon(
    neutral: BTechColorVariants(0xFF374151,
      hover: Color(0xFF374151),
      pressed: Color(0xFF374151),
      subtle: Color(0xFF9CA3AF),
      raised: Color(0xFF374151),
      disable: Color(0xFF374151),
      bolder: Color(0xFF374151),
      inverse: Color(0xFFFFFFFF),
      strong: Color(0xFF374151),
      disabled: Color(0xFFD1D5DB),
    ),
    danger: BTechColorVariants(0xFFDC2626,
      hover: Color(0xFFDC2626),
      pressed: Color(0xFFDC2626),
      subtle: Color(0xFFDC2626),
      raised: Color(0xFFDC2626),
      disable: Color(0xFFDC2626),
      bolder: Color(0xFF991B1B),
      inverse: Color(0xFFDC2626),
      strong: Color(0xFFDC2626),
      disabled: Color(0xFFDC2626),
    ),
    success: BTechColorVariants(0xFF16A34A,
      hover: Color(0xFF16A34A),
      pressed: Color(0xFF16A34A),
      subtle: Color(0xFF16A34A),
      raised: Color(0xFF16A34A),
      disable: Color(0xFF16A34A),
      bolder: Color(0xFF166534),
      inverse: Color(0xFF16A34A),
      strong: Color(0xFF16A34A),
      disabled: Color(0xFF16A34A),
    ),
    warning: BTechColorVariants(0xFFF97316,
      hover: Color(0xFFF97316),
      pressed: Color(0xFFF97316),
      subtle: Color(0xFFF97316),
      raised: Color(0xFFF97316),
      disable: Color(0xFFF97316),
      bolder: Color(0xFFC2410C),
      inverse: Color(0xFFF97316),
      strong: Color(0xFFF97316),
      disabled: Color(0xFFF97316),
    ),
    info: BTechColorVariants(0xFF2563EB,
      hover: Color(0xFF2563EB),
      pressed: Color(0xFF2563EB),
      subtle: Color(0xFF2563EB),
      raised: Color(0xFF2563EB),
      disable: Color(0xFF2563EB),
      bolder: Color(0xFF1E40AF),
      inverse: Color(0xFF2563EB),
      strong: Color(0xFF2563EB),
      disabled: Color(0xFF2563EB),
    ),
    secondary: BTechColorVariants(0xFF9333EA,
      hover: Color(0xFF9333EA),
      pressed: Color(0xFF9333EA),
      subtle: Color(0xFF9333EA),
      raised: Color(0xFF9333EA),
      disable: Color(0xFF9333EA),
      bolder: Color(0xFF6B21A8),
      inverse: Color(0xFF9333EA),
      strong: Color(0xFF9333EA),
      disabled: Color(0xFF9333EA),
    ),
  ),
  stroke: BTechColorStroke(
    neutral: BTechColorVariants(0xFFE5E7EB,
      hover: Color(0xFFE5E7EB),
      pressed: Color(0xFFE5E7EB),
      subtle: Color(0xFFF3F4F6),
      raised: Color(0xFFE5E7EB),
      disable: Color(0xFFE5E7EB),
      bolder: Color(0xFFE5E7EB),
      inverse: Color(0xFFE5E7EB),
      strong: Color(0xFF9CA3AF),
      disabled: Color(0xFFE5E7EB),
    ),
    primary: BTechColorVariants(0xFF15803D,
      hover: Color(0xFF15803D),
      pressed: Color(0xFF15803D),
      subtle: Color(0xFF15803D),
      raised: Color(0xFF15803D),
      disable: Color(0xFF15803D),
      bolder: Color(0xFF14532D),
      inverse: Color(0xFF15803D),
      strong: Color(0xFF15803D),
      disabled: Color(0xFF15803D),
    ),
    danger: BTechColorVariants(0xFFDC2626,
      hover: Color(0xFFDC2626),
      pressed: Color(0xFFDC2626),
      subtle: Color(0xFFDC2626),
      raised: Color(0xFFDC2626),
      disable: Color(0xFFDC2626),
      bolder: Color(0xFF991B1B),
      inverse: Color(0xFFDC2626),
      strong: Color(0xFFDC2626),
      disabled: Color(0xFFDC2626),
    ),
    success: BTechColorVariants(0xFF22C55E,
      hover: Color(0xFF22C55E),
      pressed: Color(0xFF22C55E),
      subtle: Color(0xFF22C55E),
      raised: Color(0xFF22C55E),
      disable: Color(0xFF22C55E),
      bolder: Color(0xFF15803D),
      inverse: Color(0xFF22C55E),
      strong: Color(0xFF22C55E),
      disabled: Color(0xFF22C55E),
    ),
    warning: BTechColorVariants(0xFFFB923C,
      hover: Color(0xFFFB923C),
      pressed: Color(0xFFFB923C),
      subtle: Color(0xFFFB923C),
      raised: Color(0xFFFB923C),
      disable: Color(0xFFFB923C),
      bolder: Color(0xFFEA580C),
      inverse: Color(0xFFFB923C),
      strong: Color(0xFFFB923C),
      disabled: Color(0xFFFB923C),
    ),
    info: BTechColorVariants(0xFF3B82F6,
      hover: Color(0xFF3B82F6),
      pressed: Color(0xFF3B82F6),
      subtle: Color(0xFF3B82F6),
      raised: Color(0xFF3B82F6),
      disable: Color(0xFF3B82F6),
      bolder: Color(0xFF1D4ED8),
      inverse: Color(0xFF3B82F6),
      strong: Color(0xFF3B82F6),
      disabled: Color(0xFF3B82F6),
    ),
    secondary: BTechColorVariants(0xFFA855F7,
      hover: Color(0xFFA855F7),
      pressed: Color(0xFFA855F7),
      subtle: Color(0xFFA855F7),
      raised: Color(0xFFA855F7),
      disable: Color(0xFFA855F7),
      bolder: Color(0xFF7E22CE),
      inverse: Color(0xFFA855F7),
      strong: Color(0xFFA855F7),
      disabled: Color(0xFFA855F7),
    ),
  ),
);

/// Static access to the active color theme (always light values).
/// For reactive light/dark switching, use `context.btechColor` instead.
abstract class BTechColor {
  static BTechColorTheme _light = _defaultLight;
  // Dark defaults to same as light until dark tokens exist.
  // ignore: unused_field
  static BTechColorTheme _dark  = _defaultLight;

  static BTechColorBackground get background => _light.background;
  static BTechColorText       get text       => _light.text;
  static BTechColorIcon       get icon       => _light.icon;
  static BTechColorStroke     get stroke     => _light.stroke;

  /// Called by [buildBtechTheme] — do not call directly.
  static void activateBoth(BTechColorTheme light, BTechColorTheme dark) {
    _light = light;
    _dark  = dark;
  }
}
