// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'shades.color.dart';

class BTechColorText {
  const BTechColorText({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.inverse,
    required this.disabled,
    required this.link,
    required this.success,
    required this.error,
    required this.warning,
    required this.info,
  });

  final Color primary;
  final Color secondary;
  final Color tertiary;
  final Color inverse;
  final Color disabled;
  final Color link;
  final Color success;
  final Color error;
  final Color warning;
  final Color info;
}

class BTechColorIcon {
  const BTechColorIcon({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.inverse,
    required this.disabled,
    required this.link,
    required this.success,
    required this.error,
    required this.warning,
    required this.info,
  });

  final Color primary;
  final Color secondary;
  final Color tertiary;
  final Color inverse;
  final Color disabled;
  final Color link;
  final Color success;
  final Color error;
  final Color warning;
  final Color info;
}

class BTechColorBorder {
  const BTechColorBorder({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.inverse,
    required this.disabled,
  });

  final Color primary;
  final Color secondary;
  final Color tertiary;
  final Color inverse;
  final Color disabled;
}

class BTechColorBg {
  const BTechColorBg({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.inverse,
    required this.subtle,
    required this.subtler,
    required this.subtlest,
    required this.overlay,
  });

  final Color primary;
  final Color secondary;
  final Color tertiary;
  final Color inverse;
  final Color subtle;
  final Color subtler;
  final Color subtlest;
  final Color overlay;
}

class BTechColorBrand {
  const BTechColorBrand({
    required this.primarySubtle,
    required this.primary,
    required this.primaryBold,
    required this.secondarySubtle,
    required this.secondary,
    required this.secondaryBold,
  });

  final Color primarySubtle;
  final Color primary;
  final Color primaryBold;
  final Color secondarySubtle;
  final Color secondary;
  final Color secondaryBold;
}

class BTechColorExt {
  const BTechColorExt({
    required this.successSubtler,
    required this.successSubtle,
    required this.success,
    required this.successBold,
    required this.infoSubtler,
    required this.infoSubtle,
    required this.info,
    required this.infoBold,
    required this.warningSubtler,
    required this.warningSubtle,
    required this.warning,
    required this.warningBold,
    required this.errorSubtler,
    required this.errorSubtle,
    required this.error,
    required this.errorBold,
  });

  final Color successSubtler;
  final Color successSubtle;
  final Color success;
  final Color successBold;
  final Color infoSubtler;
  final Color infoSubtle;
  final Color info;
  final Color infoBold;
  final Color warningSubtler;
  final Color warningSubtle;
  final Color warning;
  final Color warningBold;
  final Color errorSubtler;
  final Color errorSubtle;
  final Color error;
  final Color errorBold;
}

class BTechColorTheme extends ThemeExtension<BTechColorTheme> {
  const BTechColorTheme({
    required this.text,
    required this.icon,
    required this.border,
    required this.bg,
    required this.brand,
    required this.ext,
  });

  final BTechColorText text;
  final BTechColorIcon icon;
  final BTechColorBorder border;
  final BTechColorBg bg;
  final BTechColorBrand brand;
  final BTechColorExt ext;

  BTechColorTheme copyWith({
    BTechColorText? text,
    BTechColorIcon? icon,
    BTechColorBorder? border,
    BTechColorBg? bg,
    BTechColorBrand? brand,
    BTechColorExt? ext,
  }) =>
      BTechColorTheme(
        text: text ?? this.text,
        icon: icon ?? this.icon,
        border: border ?? this.border,
        bg: bg ?? this.bg,
        brand: brand ?? this.brand,
        ext: ext ?? this.ext,
      );

  @override
  BTechColorTheme lerp(covariant ThemeExtension<BTechColorTheme>? other, double t) {
    if (other is! BTechColorTheme) return this;
    return this;
  }
}

// ── Default light theme (resolved from semantic/color.json) ─────
const BTechColorTheme _defaultLight = BTechColorTheme(
  text: BTechColorText(
    primary: Color(0xFF181C20),
    secondary: Color(0xFF64748B),
    tertiary: Color(0xFF98A2B0),
    inverse: Color(0xFFFFFFFF),
    disabled: Color(0xFFC1C6CD),
    link: Color(0xFF0D766C),
    success: Color(0xFF0A632F),
    error: Color(0xFF991515),
    warning: Color(0xFF885A0D),
    info: Color(0xFF0F5E81),
  ),
  icon: BTechColorIcon(
    primary: Color(0xFF181C20),
    secondary: Color(0xFF64748B),
    tertiary: Color(0xFF98A2B0),
    inverse: Color(0xFFFFFFFF),
    disabled: Color(0xFFC1C6CD),
    link: Color(0xFF0D766C),
    success: Color(0xFF0A632F),
    error: Color(0xFF991515),
    warning: Color(0xFF885A0D),
    info: Color(0xFF0F5E81),
  ),
  border: BTechColorBorder(
    primary: Color(0xFFDBDDE1),
    secondary: Color(0xFF98A2B0),
    tertiary: Color(0xFFC1C6CD),
    inverse: Color(0xFF292F37),
    disabled: Color(0xFFC1C6CD),
  ),
  bg: BTechColorBg(
    primary: Color(0xFFFFFFFF),
    secondary: Color(0xFFECEDEE),
    tertiary: Color(0xFF64748B),
    inverse: Color(0xFF181C20),
    subtle: Color(0xFFF4F5F6),
    subtler: Color(0xFFDBDDE1),
    subtlest: Color(0xFFC1C6CD),
    overlay: Color(0xCC181C20),
  ),
  brand: BTechColorBrand(
    primarySubtle: Color(0xFFF0F8F4),
    primary: Color(0xFF08A94C),
    primaryBold: Color(0xFF0A853E),
    secondarySubtle: Color(0xFFF0F8F7),
    secondary: Color(0xFF0D9488),
    secondaryBold: Color(0xFF0D766C),
  ),
  ext: BTechColorExt(
    successSubtler: Color(0xFFE2F3E9),
    successSubtle: Color(0xFFC5EAD5),
    success: Color(0xFF08A94C),
    successBold: Color(0xFF0A853E),
    infoSubtler: Color(0xFFE7F0F4),
    infoSubtle: Color(0xFFD0E4ED),
    info: Color(0xFF0EA5E9),
    infoBold: Color(0xFF0F81B4),
    warningSubtler: Color(0xFFF5F0E7),
    warningSubtle: Color(0xFFEFE3D0),
    warning: Color(0xFFF59E0B),
    warningBold: Color(0xFFBD7C0C),
    errorSubtler: Color(0xFFF6EAEA),
    errorSubtle: Color(0xFFF0D9D9),
    error: Color(0xFFEF4444),
    errorBold: Color(0xFFD81818),
  ),
);

/// Static access to the active color theme (always light values).
/// For reactive light/dark switching, use `context.btechColor` instead.
abstract class BTechColor {
  static BTechColorTheme _light = _defaultLight;
  // ignore: unused_field
  static BTechColorTheme _dark  = _defaultLight;

  static BTechColorText get text => _light.text;
  static BTechColorIcon get icon => _light.icon;
  static BTechColorBorder get border => _light.border;
  static BTechColorBg get bg => _light.bg;
  static BTechColorBrand get brand => _light.brand;
  static BTechColorExt get ext => _light.ext;
  // Raw primitive color swatches — BTechColor.shades.green[500]
  static const BTechShadesColor shades = BTechShadesColor();

  /// Called by [buildBtechTheme] — do not call directly.
  static void activateBoth(BTechColorTheme light, BTechColorTheme dark) {
    _light = light;
    _dark  = dark;
  }
}
