// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// A [Color] that also exposes named variants (hover, pressed, etc.).
/// Every leaf in the color token tree IS a [Color] (default value)
/// and additionally exposes named variant [Color]s. Variants that do not
/// exist in the source token fall back to the default color value.
class BTechColorVariants extends Color {
  const BTechColorVariants(
    super.value, {
    required this.hover,
    required this.pressed,
    required this.subtle,
    required this.raised,
    required this.disable,
    required this.bolder,
    required this.inverse,
    required this.strong,
    required this.disabled,
  });

  final Color hover, pressed, subtle, raised, disable, bolder, inverse, strong, disabled;
}

class BTechColorBackground {
  const BTechColorBackground({
    required this.surface,
    required this.primary,
    required this.secondary,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.neutral,
  });

  final BTechColorVariants surface;
  final BTechColorVariants primary;
  final BTechColorVariants secondary;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants neutral;
}

class BTechColorText {
  const BTechColorText({
    required this.neutral,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorIcon {
  const BTechColorIcon({
    required this.neutral,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorStroke {
  const BTechColorStroke({
    required this.neutral,
    required this.primary,
    required this.danger,
    required this.success,
    required this.warning,
    required this.info,
    required this.secondary,
  });

  final BTechColorVariants neutral;
  final BTechColorVariants primary;
  final BTechColorVariants danger;
  final BTechColorVariants success;
  final BTechColorVariants warning;
  final BTechColorVariants info;
  final BTechColorVariants secondary;
}

class BTechColorTheme extends ThemeExtension<BTechColorTheme> {
  const BTechColorTheme({
    required this.background,
    required this.text,
    required this.icon,
    required this.stroke,
  });

  final BTechColorBackground background;
  final BTechColorText       text;
  final BTechColorIcon       icon;
  final BTechColorStroke     stroke;

  BTechColorTheme copyWith({
    BTechColorBackground? background,
    BTechColorText? text,
    BTechColorIcon? icon,
    BTechColorStroke? stroke,
  }) =>
      BTechColorTheme(
        background: background ?? this.background,
        text:       text       ?? this.text,
        icon:       icon       ?? this.icon,
        stroke:     stroke     ?? this.stroke,
      );

  @override
  BTechColorTheme lerp(covariant ThemeExtension<BTechColorTheme>? other, double t) {
    if (other is! BTechColorTheme) return this;
    return this;
  }
}

// ── Default light theme (resolved from semantic/color.json) ─────
const BTechColorTheme _defaultLight = BTechColorTheme(
  background: BTechColorBackground(
    surface: BTechColorVariants(0xFF292F37,
      hover: Color(0xFF292F37),
      pressed: Color(0xFF292F37),
      subtle: Color(0xFF3C4450),
      raised: Color(0xFF181C20),
      disable: Color(0xFF292F37),
      bolder: Color(0xFF292F37),
      inverse: Color(0xFFECEDEE),
      strong: Color(0xFF292F37),
      disabled: Color(0xFF292F37),
    ),
    primary: BTechColorVariants(0xFF41E084,
      hover: Color(0xFF08A94C),
      pressed: Color(0xFF0A853E),
      subtle: Color(0xFF072D17),
      raised: Color(0xFF41E084),
      disable: Color(0xFFDBDDE1),
      bolder: Color(0xFF0A853E),
      inverse: Color(0xFF41E084),
      strong: Color(0xFF41E084),
      disabled: Color(0xFF41E084),
    ),
    secondary: BTechColorVariants(0xFFF0F8F4,
      hover: Color(0xFFE2F3E9),
      pressed: Color(0xFFC5EAD5),
      subtle: Color(0xFFF4F5F6),
      raised: Color(0xFFF0F8F4),
      disable: Color(0xFFECEDEE),
      bolder: Color(0xFFC5EAD5),
      inverse: Color(0xFFF0F8F4),
      strong: Color(0xFFF0F8F4),
      disabled: Color(0xFFF0F8F4),
    ),
    danger: BTechColorVariants(0xFFEF4444,
      hover: Color(0xFFD81818),
      pressed: Color(0xFF991515),
      subtle: Color(0xFFF9F2F2),
      raised: Color(0xFFEF4444),
      disable: Color(0xFFDBDDE1),
      bolder: Color(0xFF991515),
      inverse: Color(0xFFEF4444),
      strong: Color(0xFFEF4444),
      disabled: Color(0xFFEF4444),
    ),
    success: BTechColorVariants(0xFF08A94C,
      hover: Color(0xFF0A853E),
      pressed: Color(0xFF0A632F),
      subtle: Color(0xFFF0F8F4),
      raised: Color(0xFF08A94C),
      disable: Color(0xFFDBDDE1),
      bolder: Color(0xFF0A632F),
      inverse: Color(0xFF08A94C),
      strong: Color(0xFF08A94C),
      disabled: Color(0xFF08A94C),
    ),
    warning: BTechColorVariants(0xFFF59E0B,
      hover: Color(0xFFBD7C0C),
      pressed: Color(0xFF885A0D),
      subtle: Color(0xFFF9F6F1),
      raised: Color(0xFFF59E0B),
      disable: Color(0xFFDBDDE1),
      bolder: Color(0xFF885A0D),
      inverse: Color(0xFFF59E0B),
      strong: Color(0xFFF59E0B),
      disabled: Color(0xFFF59E0B),
    ),
    info: BTechColorVariants(0xFF0EA5E9,
      hover: Color(0xFF0F81B4),
      pressed: Color(0xFF0F5E81),
      subtle: Color(0xFFF1F6F9),
      raised: Color(0xFF0EA5E9),
      disable: Color(0xFFDBDDE1),
      bolder: Color(0xFF0F5E81),
      inverse: Color(0xFF0EA5E9),
      strong: Color(0xFF0EA5E9),
      disabled: Color(0xFF0EA5E9),
    ),
    neutral: BTechColorVariants(0xFFECEDEE,
      hover: Color(0xFFECEDEE),
      pressed: Color(0xFFECEDEE),
      subtle: Color(0xFFF4F5F6),
      raised: Color(0xFFECEDEE),
      disable: Color(0xFFECEDEE),
      bolder: Color(0xFFDBDDE1),
      inverse: Color(0xFFECEDEE),
      strong: Color(0xFFECEDEE),
      disabled: Color(0xFFECEDEE),
    ),
  ),
  text: BTechColorText(
    neutral: BTechColorVariants(0xFFECEDEE,
      hover: Color(0xFFECEDEE),
      pressed: Color(0xFFECEDEE),
      subtle: Color(0xFF98A2B0),
      raised: Color(0xFFECEDEE),
      disable: Color(0xFFECEDEE),
      bolder: Color(0xFFECEDEE),
      inverse: Color(0xFF181C20),
      strong: Color(0xFFECEDEE),
      disabled: Color(0xFF505C6D),
    ),
    danger: BTechColorVariants(0xFFEBBDBD,
      hover: Color(0xFFEBBDBD),
      pressed: Color(0xFFEBBDBD),
      subtle: Color(0xFFEBBDBD),
      raised: Color(0xFFEBBDBD),
      disable: Color(0xFFEBBDBD),
      bolder: Color(0xFFF0D9D9),
      inverse: Color(0xFFEBBDBD),
      strong: Color(0xFFEBBDBD),
      disabled: Color(0xFFEBBDBD),
    ),
    success: BTechColorVariants(0xFF94E2B5,
      hover: Color(0xFF94E2B5),
      pressed: Color(0xFF94E2B5),
      subtle: Color(0xFF94E2B5),
      raised: Color(0xFF94E2B5),
      disable: Color(0xFF94E2B5),
      bolder: Color(0xFFC5EAD5),
      inverse: Color(0xFF94E2B5),
      strong: Color(0xFF94E2B5),
      disabled: Color(0xFF94E2B5),
    ),
    warning: BTechColorVariants(0xFFE9D2AB,
      hover: Color(0xFFE9D2AB),
      pressed: Color(0xFFE9D2AB),
      subtle: Color(0xFFE9D2AB),
      raised: Color(0xFFE9D2AB),
      disable: Color(0xFFE9D2AB),
      bolder: Color(0xFFEFE3D0),
      inverse: Color(0xFFE9D2AB),
      strong: Color(0xFFE9D2AB),
      disabled: Color(0xFFE9D2AB),
    ),
    info: BTechColorVariants(0xFFAAD4E7,
      hover: Color(0xFFAAD4E7),
      pressed: Color(0xFFAAD4E7),
      subtle: Color(0xFFAAD4E7),
      raised: Color(0xFFAAD4E7),
      disable: Color(0xFFAAD4E7),
      bolder: Color(0xFFD0E4ED),
      inverse: Color(0xFFAAD4E7),
      strong: Color(0xFFAAD4E7),
      disabled: Color(0xFFAAD4E7),
    ),
    secondary: BTechColorVariants(0xFF6E479B,
      hover: Color(0xFF6E479B),
      pressed: Color(0xFF6E479B),
      subtle: Color(0xFF6E479B),
      raised: Color(0xFF6E479B),
      disable: Color(0xFF6E479B),
      bolder: Color(0xFF37244E),
      inverse: Color(0xFF6E479B),
      strong: Color(0xFF6E479B),
      disabled: Color(0xFF6E479B),
    ),
  ),
  icon: BTechColorIcon(
    neutral: BTechColorVariants(0xFFECEDEE,
      hover: Color(0xFFECEDEE),
      pressed: Color(0xFFECEDEE),
      subtle: Color(0xFF98A2B0),
      raised: Color(0xFFECEDEE),
      disable: Color(0xFFECEDEE),
      bolder: Color(0xFFECEDEE),
      inverse: Color(0xFF181C20),
      strong: Color(0xFFECEDEE),
      disabled: Color(0xFF505C6D),
    ),
    danger: BTechColorVariants(0xFFEBBDBD,
      hover: Color(0xFFEBBDBD),
      pressed: Color(0xFFEBBDBD),
      subtle: Color(0xFFEBBDBD),
      raised: Color(0xFFEBBDBD),
      disable: Color(0xFFEBBDBD),
      bolder: Color(0xFF631010),
      inverse: Color(0xFFEBBDBD),
      strong: Color(0xFFEBBDBD),
      disabled: Color(0xFFEBBDBD),
    ),
    success: BTechColorVariants(0xFF94E2B5,
      hover: Color(0xFF94E2B5),
      pressed: Color(0xFF94E2B5),
      subtle: Color(0xFF94E2B5),
      raised: Color(0xFF94E2B5),
      disable: Color(0xFF94E2B5),
      bolder: Color(0xFF094623),
      inverse: Color(0xFF94E2B5),
      strong: Color(0xFF94E2B5),
      disabled: Color(0xFF94E2B5),
    ),
    warning: BTechColorVariants(0xFFE9D2AB,
      hover: Color(0xFFE9D2AB),
      pressed: Color(0xFFE9D2AB),
      subtle: Color(0xFFE9D2AB),
      raised: Color(0xFFE9D2AB),
      disable: Color(0xFFE9D2AB),
      bolder: Color(0xFF5A3D0B),
      inverse: Color(0xFFE9D2AB),
      strong: Color(0xFFE9D2AB),
      disabled: Color(0xFFE9D2AB),
    ),
    info: BTechColorVariants(0xFFAAD4E7,
      hover: Color(0xFFAAD4E7),
      pressed: Color(0xFFAAD4E7),
      subtle: Color(0xFFAAD4E7),
      raised: Color(0xFFAAD4E7),
      disable: Color(0xFFAAD4E7),
      bolder: Color(0xFF0C3F57),
      inverse: Color(0xFFAAD4E7),
      strong: Color(0xFFAAD4E7),
      disabled: Color(0xFFAAD4E7),
    ),
    secondary: BTechColorVariants(0xFF6E479B,
      hover: Color(0xFF6E479B),
      pressed: Color(0xFF6E479B),
      subtle: Color(0xFF6E479B),
      raised: Color(0xFF6E479B),
      disable: Color(0xFF6E479B),
      bolder: Color(0xFF37244E),
      inverse: Color(0xFF6E479B),
      strong: Color(0xFF6E479B),
      disabled: Color(0xFF6E479B),
    ),
  ),
  stroke: BTechColorStroke(
    neutral: BTechColorVariants(0xFF505C6D,
      hover: Color(0xFF505C6D),
      pressed: Color(0xFF505C6D),
      subtle: Color(0xFF3C4450),
      raised: Color(0xFF505C6D),
      disable: Color(0xFF505C6D),
      bolder: Color(0xFF505C6D),
      inverse: Color(0xFFECEDEE),
      strong: Color(0xFF64748B),
      disabled: Color(0xFF3C4450),
    ),
    primary: BTechColorVariants(0xFF08A94C,
      hover: Color(0xFF08A94C),
      pressed: Color(0xFF08A94C),
      subtle: Color(0xFF08A94C),
      raised: Color(0xFF08A94C),
      disable: Color(0xFF08A94C),
      bolder: Color(0xFF0A632F),
      inverse: Color(0xFF08A94C),
      strong: Color(0xFF08A94C),
      disabled: Color(0xFF08A94C),
    ),
    danger: BTechColorVariants(0xFFEF4444,
      hover: Color(0xFFEF4444),
      pressed: Color(0xFFEF4444),
      subtle: Color(0xFFEF4444),
      raised: Color(0xFFEF4444),
      disable: Color(0xFFEF4444),
      bolder: Color(0xFF991515),
      inverse: Color(0xFFEF4444),
      strong: Color(0xFFEF4444),
      disabled: Color(0xFFEF4444),
    ),
    success: BTechColorVariants(0xFF08A94C,
      hover: Color(0xFF08A94C),
      pressed: Color(0xFF08A94C),
      subtle: Color(0xFF08A94C),
      raised: Color(0xFF08A94C),
      disable: Color(0xFF08A94C),
      bolder: Color(0xFF0A632F),
      inverse: Color(0xFF08A94C),
      strong: Color(0xFF08A94C),
      disabled: Color(0xFF08A94C),
    ),
    warning: BTechColorVariants(0xFFF59E0B,
      hover: Color(0xFFF59E0B),
      pressed: Color(0xFFF59E0B),
      subtle: Color(0xFFF59E0B),
      raised: Color(0xFFF59E0B),
      disable: Color(0xFFF59E0B),
      bolder: Color(0xFF885A0D),
      inverse: Color(0xFFF59E0B),
      strong: Color(0xFFF59E0B),
      disabled: Color(0xFFF59E0B),
    ),
    info: BTechColorVariants(0xFF0EA5E9,
      hover: Color(0xFF0EA5E9),
      pressed: Color(0xFF0EA5E9),
      subtle: Color(0xFF0EA5E9),
      raised: Color(0xFF0EA5E9),
      disable: Color(0xFF0EA5E9),
      bolder: Color(0xFF0F5E81),
      inverse: Color(0xFF0EA5E9),
      strong: Color(0xFF0EA5E9),
      disabled: Color(0xFF0EA5E9),
    ),
    secondary: BTechColorVariants(0xFF8A59C2,
      hover: Color(0xFF8A59C2),
      pressed: Color(0xFF8A59C2),
      subtle: Color(0xFF8A59C2),
      raised: Color(0xFF8A59C2),
      disable: Color(0xFF8A59C2),
      bolder: Color(0xFF533574),
      inverse: Color(0xFF8A59C2),
      strong: Color(0xFF8A59C2),
      disabled: Color(0xFF8A59C2),
    ),
  ),
);

/// Static access to the active color theme (always light values).
/// For reactive light/dark switching, use `context.btechColor` instead.
abstract class BTechColor {
  static BTechColorTheme _light = _defaultLight;
  // Dark defaults to same as light until dark tokens exist.
  // ignore: unused_field
  static BTechColorTheme _dark  = _defaultLight;

  static BTechColorBackground get background => _light.background;
  static BTechColorText       get text       => _light.text;
  static BTechColorIcon       get icon       => _light.icon;
  static BTechColorStroke     get stroke     => _light.stroke;

  /// Called by [buildBtechTheme] — do not call directly.
  static void activateBoth(BTechColorTheme light, BTechColorTheme dark) {
    _light = light;
    _dark  = dark;
  }
}
