// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechIconNeutralColor extends Color {
  const BTechIconNeutralColor()
    : subtle = const Color(0xFF64748B),
      tertiary = const Color(0xFF98A2B0),
      disabled = const Color(0xFFC1C6CD),
      inverse = const Color(0xFFFFFFFF),
      link = const Color(0xFF0D766C),
      super(0xFF181C20);
  final Color subtle;
  final Color tertiary;
  final Color disabled;
  final Color inverse;
  final Color link;
}

class BTechIconDangerColor extends Color {
  const BTechIconDangerColor()
    : bolder = const Color(0xFF631010),
      super(0xFF991515);
  final Color bolder;
}

class BTechIconSuccessColor extends Color {
  const BTechIconSuccessColor()
    : bolder = const Color(0xFF094623),
      super(0xFF0A632F);
  final Color bolder;
}

class BTechIconWarningColor extends Color {
  const BTechIconWarningColor()
    : bolder = const Color(0xFF5A3D0B),
      super(0xFF885A0D);
  final Color bolder;
}

class BTechIconInfoColor extends Color {
  const BTechIconInfoColor()
    : bolder = const Color(0xFF0C3F57),
      super(0xFF0F5E81);
  final Color bolder;
}

class BTechIconSecondaryColor extends Color {
  const BTechIconSecondaryColor()
    : bolder = const Color(0xFF37244E),
      super(0xFF6E479B);
  final Color bolder;
}

/// Semantic icon color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechIconColor.neutral → Color
class BTechIconColor {
  const BTechIconColor()
    : neutral = const BTechIconNeutralColor(),
      danger = const BTechIconDangerColor(),
      success = const BTechIconSuccessColor(),
      warning = const BTechIconWarningColor(),
      info = const BTechIconInfoColor(),
      secondary = const BTechIconSecondaryColor();
  final BTechIconNeutralColor neutral;
  final BTechIconDangerColor danger;
  final BTechIconSuccessColor success;
  final BTechIconWarningColor warning;
  final BTechIconInfoColor info;
  final BTechIconSecondaryColor secondary;
}

