// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechStrokeNeutralColor extends Color {
  const BTechStrokeNeutralColor()
    : strong = const Color(0xFF98A2B0),
      subtle = const Color(0xFFECEDEE),
      tertiary = const Color(0xFFC1C6CD),
      inverse = const Color(0xFF292F37),
      disabled = const Color(0xFFC1C6CD),
      super(0xFFDBDDE1);
  final Color strong;
  final Color subtle;
  final Color tertiary;
  final Color inverse;
  final Color disabled;
}

class BTechStrokePrimaryColor extends Color {
  const BTechStrokePrimaryColor()
    : bolder = const Color(0xFF0A632F),
      super(0xFF08A94C);
  final Color bolder;
}

class BTechStrokeDangerColor extends Color {
  const BTechStrokeDangerColor()
    : bolder = const Color(0xFF991515),
      super(0xFFEF4444);
  final Color bolder;
}

class BTechStrokeSuccessColor extends Color {
  const BTechStrokeSuccessColor()
    : bolder = const Color(0xFF0A632F),
      super(0xFF08A94C);
  final Color bolder;
}

class BTechStrokeWarningColor extends Color {
  const BTechStrokeWarningColor()
    : bolder = const Color(0xFF885A0D),
      super(0xFFF59E0B);
  final Color bolder;
}

class BTechStrokeInfoColor extends Color {
  const BTechStrokeInfoColor()
    : bolder = const Color(0xFF0F5E81),
      super(0xFF0EA5E9);
  final Color bolder;
}

class BTechStrokeSecondaryColor extends Color {
  const BTechStrokeSecondaryColor()
    : bolder = const Color(0xFF533574),
      super(0xFF8A59C2);
  final Color bolder;
}

/// Semantic stroke color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechStrokeColor.neutral → Color
class BTechStrokeColor {
  const BTechStrokeColor()
    : neutral = const BTechStrokeNeutralColor(),
      primary = const BTechStrokePrimaryColor(),
      danger = const BTechStrokeDangerColor(),
      success = const BTechStrokeSuccessColor(),
      warning = const BTechStrokeWarningColor(),
      info = const BTechStrokeInfoColor(),
      secondary = const BTechStrokeSecondaryColor();
  final BTechStrokeNeutralColor neutral;
  final BTechStrokePrimaryColor primary;
  final BTechStrokeDangerColor danger;
  final BTechStrokeSuccessColor success;
  final BTechStrokeWarningColor warning;
  final BTechStrokeInfoColor info;
  final BTechStrokeSecondaryColor secondary;
}

