// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechTextNeutralColor extends Color {
  const BTechTextNeutralColor()
    : subtle = const Color(0xFF64748B),
      tertiary = const Color(0xFF98A2B0),
      disabled = const Color(0xFFC1C6CD),
      inverse = const Color(0xFFFFFFFF),
      link = const Color(0xFF0D766C),
      super(0xFF181C20);
  final Color subtle;
  final Color tertiary;
  final Color disabled;
  final Color inverse;
  final Color link;
}

class BTechTextDangerColor extends Color {
  const BTechTextDangerColor()
    : bolder = const Color(0xFF631010),
      super(0xFF991515);
  final Color bolder;
}

class BTechTextSuccessColor extends Color {
  const BTechTextSuccessColor()
    : bolder = const Color(0xFF094623),
      super(0xFF0A632F);
  final Color bolder;
}

class BTechTextWarningColor extends Color {
  const BTechTextWarningColor()
    : bolder = const Color(0xFF5A3D0B),
      super(0xFF885A0D);
  final Color bolder;
}

class BTechTextInfoColor extends Color {
  const BTechTextInfoColor()
    : bolder = const Color(0xFF0C3F57),
      super(0xFF0F5E81);
  final Color bolder;
}

class BTechTextSecondaryColor extends Color {
  const BTechTextSecondaryColor()
    : bolder = const Color(0xFF37244E),
      super(0xFF6E479B);
  final Color bolder;
}

/// Semantic text color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechTextColor.neutral → Color
class BTechTextColor {
  const BTechTextColor()
    : neutral = const BTechTextNeutralColor(),
      danger = const BTechTextDangerColor(),
      success = const BTechTextSuccessColor(),
      warning = const BTechTextWarningColor(),
      info = const BTechTextInfoColor(),
      secondary = const BTechTextSecondaryColor();
  final BTechTextNeutralColor neutral;
  final BTechTextDangerColor danger;
  final BTechTextSuccessColor success;
  final BTechTextWarningColor warning;
  final BTechTextInfoColor info;
  final BTechTextSecondaryColor secondary;
}

