import { writeFileSync, mkdirSync } from 'fs';
import { ROOT, hexToArgb } from '../utils.js';

// =============================================================================
// Token path → Dart getter name
//   color.background.primary.default → backgroundPrimary
//   color.stroke.primary.hover       → strokePrimaryHover
//   radius.interactive               → radiusInteractive
//   typography.fontFamily.sans       → fontFamilySans
// =============================================================================
function tokenPathToGetter(path: string): string {
  let p = path;
  // Drop leading category prefixes — keep semantic name only
  if (p.startsWith('color.'))      p = p.slice('color.'.length);
  if (p.startsWith('typography.')) p = p.slice('typography.'.length);
  // Drop trailing '.default' — implied
  if (p.endsWith('.default')) p = p.slice(0, -'.default'.length);
  // camelCase: split by '.', capitalize each segment after the first
  const parts = p.split('.');
  return parts[0] + parts.slice(1).map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}

// =============================================================================
// Value → typed Dart literal
// =============================================================================
export type DartTokenType = 'Color' | 'double' | 'String';

export function dartType(value: string): DartTokenType {
  if (/^#[0-9A-Fa-f]{3,8}$/.test(value.trim())) return 'Color';
  if (/^[0-9]+(\.[0-9]+)?(px|rem|em|%)$/.test(value.trim())) return 'double';
  return 'String';
}

export function dartLiteral(value: string, type: DartTokenType): string {
  const v = value.trim();
  if (type === 'Color') return `Color(${hexToArgb(v)})`;
  if (type === 'double') return `${parseFloat(v)}`; // strips 'px'/'rem'/etc.
  // String — take only the first font family, strip quotes
  const first = v.split(',')[0].trim().replace(/['"]/g, '');
  return `'${first}'`;
}

// =============================================================================
// Overridable token paths (must match schema/token.schema.json)
// These become getters on BtechToken base class.
// =============================================================================
const OVERRIDABLE_PREFIXES = [
  'color.background.primary',
  'color.background.secondary',
  'color.stroke.primary',
  'color.text.primary',
  'color.icon.primary',
  'typography.fontFamily',
  'radius.interactive',
  'radius.card',
  'radius.pill',
];

function isOverridable(path: string): boolean {
  return OVERRIDABLE_PREFIXES.some(p => path === p || path.startsWith(p + '.'));
}

// =============================================================================
// generateFlutterBaseToken
// Writes packages/tokens/platforms/flutter/lib/src/btech_token.dart
// =============================================================================
export function generateFlutterBaseToken(resolvedBaseMap: Record<string, string>): void {
  const outDir = `${ROOT}/platforms/flutter/lib/src`;
  mkdirSync(outDir, { recursive: true });

  const lines: string[] = [
    '// AUTO-GENERATED by @btech/design-system — do not edit manually.',
    '// Run `pnpm generate` to regenerate.',
    '//',
    '// ignore_for_file: lines_longer_than_80_chars',
    '',
    "import 'package:flutter/material.dart';",
    '',
    '/// Base design token values for all BTech tenants.',
    '///',
    '/// Tenant packages extend this class and override only the tokens',
    '/// that differ from the defaults. All other tokens are inherited.',
    '///',
    '/// Usage in consuming app (after installing a tenant package e.g. btech_tokens_bspace):',
    '///   import \'package:btech_tokens_bspace/btech_tokens_bspace.dart\';',
    '///   final token = BTechToken.instance;',
    '///   token.backgroundPrimary          // Color(0xFF0066CC)',
    '///   token.radiusInteractive          // 6.0',
    'class BTechToken {',
    '  const BTechToken();',
    '',
    '  /// Singleton — access tokens without constructing directly.',
    '  /// In tenant packages this is overridden with the tenant\'s own const instance.',
    '  static const BTechToken instance = BTechToken();',
    '',
  ];

  // Group by category for readability
  const categories: Record<string, Array<{ getter: string; type: DartTokenType; value: string }>> = {};

  for (const [path, value] of Object.entries(resolvedBaseMap)) {
    if (!isOverridable(path)) continue;
    if (value.startsWith('{')) continue; // unresolved ref — skip
    const cleanPath = path.replace(/\.default$/, '');
    const getter = tokenPathToGetter(cleanPath);
    const type   = dartType(value);

    // category = first segment of clean path (after removing 'color.')
    let cat = cleanPath.split('.')[0];
    if (cat === 'color') cat = cleanPath.split('.')[1] ?? 'color';

    if (!categories[cat]) categories[cat] = [];
    // Deduplicate (plain path vs .default path may both appear)
    if (!categories[cat].some(e => e.getter === getter)) {
      categories[cat].push({ getter, type, value });
    }
  }

  for (const [cat, entries] of Object.entries(categories)) {
    lines.push(`  // ── ${cat} ${'─'.repeat(Math.max(0, 55 - cat.length))}`);
    for (const { getter, type, value } of entries) {
      // 'const' only applies to Color — String and double use plain literals
    const constPrefix = type === 'Color' ? 'const ' : '';
    lines.push(`  ${type} get ${getter} => ${constPrefix}${dartLiteral(value, type)};`);
    }
    lines.push('');
  }

  lines.push('}', '');

  writeFileSync(`${outDir}/btech_token.dart`, lines.join('\n'), 'utf-8');
  console.log('  Flutter base  — packages/tokens/platforms/flutter/lib/src/btech_token.dart');
}

// Export path helper for use in tenant generator
export { tokenPathToGetter };
