import { existsSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from 'fs';
import { ROOT, hexToArgb, toPascalCase, toYaml } from '../utils.js';
import type { ResolvedTokenMap, TypeScaleEntry } from '../token-loader.js';
import { generateTokensMeta } from './flutter-color.js';
import { generateFlutterThemeFiles } from './flutter-theme-generator.js';

const HEADER = '// AUTO-GENERATED by @btech/design-system — do not edit manually.\n// Run `pnpm generate` to regenerate from tokens/.\n\n// ignore_for_file: lines_longer_than_80_chars\n';

/** Emit a plain TextStyle(...) field using the active BTechTypography.fontFamily.
 *  No google_fonts dependency — fontFamily is resolved at runtime from the static field. */
function dartTextStyle(entry: TypeScaleEntry, varName: string): string[] {
  const lines: string[] = [];
  const extras: string[] = [];
  if (entry.fontStyle === 'italic')         extras.push(`      fontStyle: FontStyle.italic,`);
  if (entry.textDecoration === 'underline') extras.push(`      decoration: TextDecoration.underline,`);

  if (extras.length === 0) {
    lines.push(
      `  final TextStyle ${varName} = TextStyle(`,
      `      fontFamily: BTechTypography.fontFamily,`,
      `      fontSize: ${entry.fontSize}, fontWeight: FontWeight.w${entry.fontWeight}, height: ${entry.lineHeightPx} / ${entry.fontSize});`,
    );
  } else {
    lines.push(`  final TextStyle ${varName} = TextStyle(`);
    lines.push(`      fontFamily: BTechTypography.fontFamily,`);
    lines.push(`      fontSize: ${entry.fontSize}, fontWeight: FontWeight.w${entry.fontWeight}, height: ${entry.lineHeightPx} / ${entry.fontSize},`);
    const last = extras.pop()!.replace(/,$/, ');');
    lines.push(...extras, last);
  }
  return lines;
}

export function generateFlutterFiles(data: ResolvedTokenMap): void {
  const DART_SRC = `${ROOT}/platforms/flutter/lib/src`;
  const DART_LIB = `${ROOT}/platforms/flutter/lib`;

  // ── color/ ─────────────────────────────────────────────────────────────────
  const colorDir = `${DART_SRC}/color`;
  // Clean up stale *.dart files before regenerating so removed categories don't persist.
  if (existsSync(colorDir)) {
    for (const f of readdirSync(colorDir).filter(f => f.endsWith('.dart'))) {
      unlinkSync(`${colorDir}/${f}`);
    }
  }
  mkdirSync(colorDir, { recursive: true });

  // shades.color.dart — uses MaterialColor so Flutter theming works natively.
  // Access: BTechColor.shades.blue          → primary swatch color (500)
  //         BTechColor.shades.blue[400]     → specific shade via MaterialColor
  //         BTechColor.shades.blue.shade700 → via MaterialColor getter
  {
    const L = [HEADER, "import 'package:flutter/material.dart';\n"];
    const groupNames: string[] = [];

    for (const [group, shades] of Object.entries(data.coreColors)) {
      groupNames.push(group);
      const entries = Object.entries(shades)
        .filter(([k]) => k !== '0') // key 0 (white) is excluded from MaterialColor map
        .sort((a, b) => Number(a[0]) - Number(b[0]));

      // Pick the 500 shade as the MaterialColor primary; fall back to the middle entry
      const primaryHex = (shades['500'] ?? shades[Object.keys(shades).sort((a, b) => Number(a) - Number(b))[Math.floor(Object.keys(shades).length / 2)]]) as string;

      const mapEntries = entries.map(([shade, hex]) =>
        `      ${shade}: Color(${hexToArgb(hex)}),`
      ).join('\n');

      L.push(`/// ${toPascalCase(group)} color swatch — BTechColor.shades.${group}[500]`);
      L.push(`final MaterialColor btechShades${toPascalCase(group)} = MaterialColor(`);
      L.push(`  ${hexToArgb(primaryHex)},`);
      L.push(`  <int, Color>{`);
      L.push(mapEntries);
      L.push(`  },`);
      L.push(`);\n`);
    }

    L.push('/// Primitive color palette as MaterialColor swatches.');
    L.push('/// Access: BTechColor.shades.blue        → primary 500');
    L.push('///         BTechColor.shades.blue[400]   → shade 400');
    L.push('///         BTechColor.shades.green.shade700');
    L.push('class BTechShadesColor {');
    L.push('  const BTechShadesColor();');
    for (const group of groupNames) {
      L.push(`  MaterialColor get ${group} => btechShades${toPascalCase(group)};`);
    }
    L.push('}\n');
    writeFileSync(`${colorDir}/shades.color.dart`, L.join('\n') + '\n');
  }

  // color.dart barrel — only shades (primitive swatches) + the theme-based classes.
  // Pattern A classes (text/icon/background/stroke *.color.dart) are removed;
  // BTechColor in color.theme.dart already provides both Pattern A static access
  // AND Pattern C reactive access.
  writeFileSync(`${colorDir}/color.dart`, [
    "export 'shades.color.dart';",
    "export 'color.theme.dart';",
    '',
  ].join('\n'));

  generateTokensMeta(colorDir, 'color', data.semanticColors);

  // ── spacing/ ────────────────────────────────────────────────────────────────
  const spacingDir = `${DART_SRC}/spacing`;
  mkdirSync(spacingDir, { recursive: true });

  const spacingLines = [HEADER, '/// Spacing tokens. Access: BTechSpacing.md', 'abstract class BTechSpacing {'];
  for (const [name, value] of Object.entries(data.spacing)) {
    const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
    spacingLines.push(`  static const double ${safeName} = ${parseFloat(String(value).replace('px', ''))};`);
  }
  spacingLines.push('}\n');
  writeFileSync(`${spacingDir}/spacing.token.dart`, spacingLines.join('\n') + '\n');
  writeFileSync(`${spacingDir}/spacing.dart`, "export 'spacing.token.dart';\n");
  writeFileSync(`${spacingDir}/tokens.meta.yaml`, toYaml({
    category: 'spacing',
    figma: {
      collection: 'BTech/Spacing',
      tokens: Object.keys(data.spacing).map(name => ({
        path: `spacing.${name}`,
        figmaVariable: `Spacing/${toPascalCase(name)}`,
      })),
    },
  }) + '\n');

  // ── stroke/ ─────────────────────────────────────────────────────────────────
  const strokeDir = `${DART_SRC}/stroke`;
  mkdirSync(strokeDir, { recursive: true });

  const strokeLines = [HEADER, '/// Stroke (border-width) tokens. Access: BTechStroke.md', 'abstract class BTechStroke {'];
  for (const [name, value] of Object.entries(data.stroke)) {
    const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
    strokeLines.push(`  static const double ${safeName} = ${parseFloat(String(value).replace('px', ''))};`);
  }
  strokeLines.push('}\n');
  writeFileSync(`${strokeDir}/stroke.token.dart`, strokeLines.join('\n') + '\n');
  writeFileSync(`${strokeDir}/stroke.dart`, "export 'stroke.token.dart';\n");
  writeFileSync(`${strokeDir}/tokens.meta.yaml`, toYaml({
    category: 'stroke',
    figma: {
      collection: 'BTech/Stroke',
      tokens: Object.keys(data.stroke).map(name => ({
        path: `stroke.${name}`,
        figmaVariable: `Stroke/${toPascalCase(name)}`,
      })),
    },
  }) + '\n');

  // ── radius/ ─────────────────────────────────────────────────────────────────
  const radiusDir = `${DART_SRC}/radius`;
  mkdirSync(radiusDir, { recursive: true });

  const radiusLines = [HEADER, '/// Radius tokens. Access: BTechRadius.sm', 'abstract class BTechRadius {'];
  for (const [name, value] of Object.entries(data.radius)) {
    const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
    radiusLines.push(`  static const double ${safeName} = ${parseFloat(String(value).replace('px', ''))};`);
  }
  radiusLines.push('}\n');
  writeFileSync(`${radiusDir}/radius.token.dart`, radiusLines.join('\n') + '\n');
  writeFileSync(`${radiusDir}/radius.dart`, "export 'radius.token.dart';\n");
  writeFileSync(`${radiusDir}/tokens.meta.yaml`, toYaml({
    category: 'radius',
    figma: {
      collection: 'BTech/Radius',
      tokens: Object.keys(data.radius).map(name => ({ path: `radius.${name}`, figmaVariable: `Radius/${toPascalCase(name)}` })),
    },
  }) + '\n');

  // ── shadow/ ─────────────────────────────────────────────────────────────
  const shadowDir = `${DART_SRC}/shadow`;
  mkdirSync(shadowDir, { recursive: true });

  function rgbaToArgbHex(rgba: string): string {
    const m = rgba.match(/rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+))?\s*\)/);
    if (!m) return '0xFF000000';
    const r = Math.round(Number(m[1])).toString(16).padStart(2, '0').toUpperCase();
    const g = Math.round(Number(m[2])).toString(16).padStart(2, '0').toUpperCase();
    const b = Math.round(Number(m[3])).toString(16).padStart(2, '0').toUpperCase();
    const a = m[4] !== undefined
      ? Math.round(parseFloat(m[4]) * 255).toString(16).padStart(2, '0').toUpperCase()
      : 'FF';
    return `0x${a}${r}${g}${b}`;
  }

  // Helper: emit BoxShadow layers
  function emitLayers(lines: string[], layers: import('../token-loader.js').ShadowLayer[], indent: string): void {
    for (const l of layers) {
      const argb = rgbaToArgbHex(l.color);
      const blurStyle = l.inset ? `\n${indent}  blurStyle: BlurStyle.inner,` : '';
      lines.push(
        `${indent}BoxShadow(`,
        `${indent}  color: Color(${argb}),`,
        `${indent}  offset: Offset(${l.offsetX}, ${l.offsetY}),`,
        `${indent}  blurRadius: ${l.blur},`,
        `${indent}  spreadRadius: ${l.spread},${blurStyle}`,
        `${indent}),`,
      );
    }
  }

  const shadowLines = [
    HEADER,
    "import 'package:flutter/material.dart';\n",
    '/// Shadow tokens.',
    '/// Access: BTechShadow.button.pressed  BTechShadow.elevation.md',
    '/// Each getter returns List<BoxShadow> — use inside BoxDecoration.boxShadow.',
    '///',
    '/// ```dart',
    '/// Container(',
    "///   decoration: BoxDecoration(boxShadow: BTechShadow.elevation.md),",
    '/// )',
    '/// ```',
  ];

  // Emit one group class per top-level key (button, table, elevation, …)
  for (const [group, variants] of Object.entries(data.shadow)) {
    const className = `_BTechShadow${toPascalCase(group)}Group`;
    shadowLines.push(`class ${className} {`);
    shadowLines.push(`  const ${className}();\n`);
    for (const [variant, layers] of Object.entries(variants)) {
      shadowLines.push(`  List<BoxShadow> get ${variant} => const [`);
      emitLayers(shadowLines, layers, '    ');
      shadowLines.push('  ];\n');
    }
    shadowLines.push('}\n');
  }

  // Emit root BTechShadow class with one const field per group
  shadowLines.push('abstract class BTechShadow {');
  for (const group of Object.keys(data.shadow)) {
    const className = `_BTechShadow${toPascalCase(group)}Group`;
    shadowLines.push(`  static const ${group} = ${className}();`);
  }
  shadowLines.push('}\n');

  writeFileSync(`${shadowDir}/shadow.token.dart`, shadowLines.join('\n') + '\n');
  writeFileSync(`${shadowDir}/shadow.dart`, [
    "export 'shadow.token.dart';",
    "export 'inner_shadow.dart';",
    '',
  ].join('\n'));

  // ── typography/ ─────────────────────────────────────────────────────────────
  const typoDir = `${DART_SRC}/typography`;
  mkdirSync(typoDir, { recursive: true });

  // heading.dart
  {
    const scales = data.typography.typeScale.heading;
    const first = Object.values(scales)[0] ?? { fontSize: 40, fontWeight: 700, lineHeightPx: 48 };
    const L = [HEADER,
      "import 'package:flutter/material.dart';",
      "import 'font.theme.dart';\n",
      '/// Heading text styles (display, h1–h4).',
      '/// Font family is tenant-aware — driven by BTechTypography.fontFamily.',
      '///',
      '/// ```dart',
      `/// Text('Hero',  style: BTechTypography.heading.display)`,
      `/// Text('Title', style: BTechTypography.heading.h1)`,
      '/// ```',
      'class BTechTypographyHeading extends TextStyle {',
      `  BTechTypographyHeading()`,
      `      : super(`,
      `          fontFamily: BTechTypography.fontFamily,`,
      `          fontSize: ${first.fontSize},`,
      `          fontWeight: FontWeight.w${first.fontWeight},`,
      `          height: ${first.lineHeightPx} / ${first.fontSize},`,
      `        );\n`,
    ];
    for (const [name, entry] of Object.entries(scales)) {
      L.push(`  /// ${name.toUpperCase()} — ${entry.fontSize}px · w${entry.fontWeight} · lineHeight: ${entry.lineHeightPx}/${entry.fontSize} = ${(entry.lineHeightPx / entry.fontSize).toFixed(3)}`);
      L.push(...dartTextStyle(entry, name));
      L.push('');
    }
    L.push('}\n');
    writeFileSync(`${typoDir}/heading.dart`, L.join('\n') + '\n');
  }

  // subheading.dart
  {
    const scales = data.typography.typeScale.subheading;
    const first = Object.values(scales)[0] ?? { fontSize: 18, fontWeight: 600, lineHeightPx: 24 };
    const L = [HEADER,
      "import 'package:flutter/material.dart';",
      "import 'font.theme.dart';\n",
      '/// Subheading text styles (h5–h8).',
      '/// Font family is tenant-aware — driven by BTechTypography.fontFamily.',
      '///',
      '/// ```dart',
      `/// Text('Section', style: BTechTypography.subheading.h5)`,
      `/// Text('Label',   style: BTechTypography.subheading.h6)`,
      '/// ```',
      'class BTechTypographySubHeading extends TextStyle {',
      `  BTechTypographySubHeading()`,
      `      : super(`,
      `          fontFamily: BTechTypography.fontFamily,`,
      `          fontSize: ${first.fontSize},`,
      `          fontWeight: FontWeight.w${first.fontWeight},`,
      `          height: ${first.lineHeightPx} / ${first.fontSize},`,
      `        );\n`,
    ];
    for (const [name, entry] of Object.entries(scales)) {
      L.push(`  /// ${name.toUpperCase()} — ${entry.fontSize}px · w${entry.fontWeight} · lineHeight: ${entry.lineHeightPx}/${entry.fontSize} = ${(entry.lineHeightPx / entry.fontSize).toFixed(3)}`);
      L.push(...dartTextStyle(entry, name));
      L.push('');
    }
    L.push('}\n');
    writeFileSync(`${typoDir}/subheading.dart`, L.join('\n') + '\n');
  }

  // body.dart
  {
    const scales = data.typography.typeScale.body;
    // Default body = 'regular' (14px/400/16). Fall back to first entry.
    const regularEntry = scales['regular'] ?? Object.values(scales)[0] ?? { fontSize: 14, fontWeight: 400, lineHeightPx: 16 };
    const L = [HEADER,
      "import 'package:flutter/material.dart';",
      "import 'font.theme.dart';\n",
      '/// Body text styles.',
      '/// Instance itself IS the regular (14px/w400) style.',
      '/// Font family is tenant-aware — driven by BTechTypography.fontFamily.',
      '///',
      '/// ```dart',
      `/// Text('Body',  style: BTechTypography.body.regular)`,
      `/// Text('Bold',  style: BTechTypography.body.regularB)`,
      `/// Text('Small', style: BTechTypography.body.small)`,
      '/// ```',
      'class BTechTypographyBody extends TextStyle {',
      `  BTechTypographyBody()`,
      `      : super(`,
      `          fontFamily: BTechTypography.fontFamily,`,
      `          fontSize: ${regularEntry.fontSize},`,
      `          fontWeight: FontWeight.w${regularEntry.fontWeight},`,
      `          height: ${regularEntry.lineHeightPx} / ${regularEntry.fontSize},`,
      `        );\n`,
    ];
    for (const [name, entry] of Object.entries(scales)) {
      L.push(`  /// ${name} — ${entry.fontSize}px · w${entry.fontWeight} · lineHeight: ${entry.lineHeightPx}/${entry.fontSize} = ${(entry.lineHeightPx / entry.fontSize).toFixed(3)}`);
      L.push(...dartTextStyle(entry, name));
      L.push('');
    }
    L.push('}\n');
    writeFileSync(`${typoDir}/body.dart`, L.join('\n') + '\n');
  }

  // font.token.dart — primitive scale tokens (BTechFontSize, BTechFontWeight, BTechLineHeight).
  {
    const L = [HEADER, "import 'package:flutter/material.dart';\n"];

    L.push('/// Primitive font size tokens.');
    L.push('abstract class BTechFontSize {');
    for (const [name, value] of Object.entries(data.typography.fontSizes)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  static const double ${safeName} = ${parseFloat(String(value).replace('px', ''))};`);
    }
    L.push('}\n');

    L.push('/// Primitive font weight tokens.');
    L.push('abstract class BTechFontWeight {');
    for (const [name, value] of Object.entries(data.typography.fontWeights)) {
      L.push(`  static const FontWeight ${name} = FontWeight.w${Number(value)};`);
    }
    L.push('}\n');

    L.push('/// Primitive line height tokens (pixels).');
    L.push('abstract class BTechLineHeight {');
    for (const [name, value] of Object.entries(data.typography.lineHeights)) {
      const safeName = /^[0-9]/.test(name) ? `s${name}` : name;
      L.push(`  static const double ${safeName} = ${parseFloat(String(value).replace('px', ''))};`);
    }
    L.push('}\n');
    writeFileSync(`${typoDir}/font.token.dart`, L.join('\n') + '\n');
  }

  // typography.dart barrel — font.theme.dart (BTechTypography static class) generated by flutter-theme-generator.
  // font_registry.dart is removed — font loading is the consuming app's responsibility.
  writeFileSync(`${typoDir}/typography.dart`, [
    "export 'heading.dart';",
    "export 'subheading.dart';",
    "export 'body.dart';",
    "export 'font.token.dart';",
    "export 'font.theme.dart';",
    '',
  ].join('\n'));

  // tokens.meta.yaml
  const typoMetaTokens: Array<{ path: string; figmaVariable: string }> = [];
  for (const [group, props] of Object.entries(data.typography.semantic)) {
    for (const prop of Object.keys(props)) {
      typoMetaTokens.push({
        path: `typography.${group}.${prop}`,
        figmaVariable: `Typography/${toPascalCase(group)}/${toPascalCase(prop)}`,
      });
    }
  }
  writeFileSync(`${typoDir}/tokens.meta.yaml`, toYaml({ category: 'typography', figma: { collection: 'BTech/Typography', tokens: typoMetaTokens } }) + '\n');

  // ── btech_tokens.dart root barrel ───────────────────────────────────────────
  writeFileSync(`${DART_LIB}/btech_tokens.dart`, [
    '/// btech_tokens — Multi-tenant design tokens for Flutter (BTech Design System).',
    '///',
    '/// Setup with btechTheme() from your tenant package:',
    '///   MaterialApp(',
    '///     theme:     btechTheme(),',
    '///     darkTheme: btechTheme(brightness: Brightness.dark),',
    '///     themeMode: ThemeMode.system,',
    '///   )',
    '///',
    '/// Access tokens in widgets via context extensions (Pattern C — reactive):',
    "///   context.btechColor.background.primary   // Color",
    "///   context.btechColor.text.neutral.subtle  // Color",
    "///   context.btechRadius.interactive         // double",
    "///   context.btechFont.family.sans           // String",
    '///',
    '/// Or use static classes when context is unavailable (Pattern A — always light):',
    "///   BTechColor.background.primary           // Color",
    "///   BTechRadius.interactive                 // double",
    'library btech_tokens;',
    '',
    // color.dart re-exports shades.color.dart + color.theme.dart (BTechColor, BTechColorTheme, etc.)
    "export 'src/color/color.dart';",
    "export 'src/spacing/spacing.dart';",
    "export 'src/shadow/shadow.dart';",
    "export 'src/stroke/stroke.dart';",
    "export 'src/radius/radius.dart' hide BTechRadius;",
    "export 'src/radius/radius.theme.dart';",
    // All typography + font theme live under a single src/typography/ folder.
    "export 'src/typography/typography.dart';",
    // Default tokens — btechColor, btechRadius, btechFont, btechTheme() with base values.
    "export 'src/defaults.dart';",
    "export 'src/theme_builder.dart';",
    "export 'src/context.dart';",
    '',
  ].join('\n'));

  // Generate ThemeExtension classes, theme_builder.dart, and context.dart
  generateFlutterThemeFiles();
}
