// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Flutter theme generator: derives BTechColorTheme tree from source JSON and
// emits 5 Dart files under platforms/flutter/lib/src/.

import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync } from 'fs';
import { ROOT, flattenDTCG, resolveRef, hexToArgb } from '../utils.js';

// =============================================================================
// Types
// =============================================================================

export interface SubcategoryEntry {
  /** e.g. 'primary', 'neutral', 'danger' */
  name: string;
  /** which child key is the base Color value ('default' or 'base') */
  defaultKey: string;
  /** all other child keys (hover, pressed, subtle, raised, disable, bolder, inverse, strong, disabled) */
  variants: string[];
}

/** Dynamic map of category name → subcategory entries.
 *  Derived from the top-level keys of semantic/color.json (background, text, icon, stroke,
 *  brand, extended, …) so new groups auto-generate without code changes. */
export type ColorTree = Record<string, SubcategoryEntry[]>;

export interface RadiusField {
  /** e.g. 'interactive' */
  name: string;
  /** resolved px string, e.g. '8px' */
  value: string;
}

// =============================================================================
// Constants
// =============================================================================

const DEFAULT_KEYS = new Set(['default', 'base']);
/** The full list of variant field names on BTechColorVariants. */
const VARIANT_FIELDS = [
  'hover', 'pressed', 'subtle', 'raised',
  'disable', 'bolder', 'inverse', 'strong', 'disabled',
] as const;

const HEADER =
  '// AUTO-GENERATED by @btech/design-system — do not edit manually.\n' +
  '// Run `pnpm generate` to regenerate.\n' +
  '// ignore_for_file: lines_longer_than_80_chars\n';

// =============================================================================
// Tree derivation
// =============================================================================

/** Derive the color access tree from the semantic color JSON (structure only, no values).
 *  Iterates all top-level keys so new categories (brand, extended, …) are included
 *  automatically without changing this file. */
export function buildColorTree(): ColorTree {
  const colorJson = JSON.parse(
    readFileSync(`${ROOT}/sources/semantic/color.json`, 'utf-8'),
  ) as { color: Record<string, Record<string, Record<string, unknown>>> };

  const tree: ColorTree = {};

  for (const [category, categoryNode] of Object.entries(colorJson.color)) {
    tree[category] = [];
    for (const [subcatName, subcatNode] of Object.entries(categoryNode)) {
      const childKeys = Object.keys(subcatNode as object).filter(k => !k.startsWith('$'));
      const defaultKey = childKeys.find(k => DEFAULT_KEYS.has(k));
      if (!defaultKey) continue;
      const variants = childKeys.filter(k => k !== defaultKey);
      tree[category].push({ name: subcatName, defaultKey, variants });
    }
  }
  return tree;
}

/** Get resolved radius fields from the base map. */
export function buildRadiusFields(resolvedMap: Record<string, string>): RadiusField[] {
  const radiusJson = JSON.parse(
    readFileSync(`${ROOT}/sources/semantic/radius.json`, 'utf-8'),
  ) as { radius: Record<string, unknown> };
  const out: RadiusField[] = [];
  for (const name of Object.keys(radiusJson.radius)) {
    const key = `radius.${name}`;
    const resolved = resolvedMap[key] ?? '0px';
    out.push({ name, value: resolved });
  }
  return out;
}

/** Get resolved font family sans value (first family name, unquoted). */
export function buildFontSans(resolvedMap: Record<string, string>): string {
  const raw = resolvedMap['typography.fontFamily.sans'] ?? 'Inter';
  return raw.split(',')[0].trim().replace(/^['"]|['"]$/g, '');
}

// =============================================================================
// Helpers
// =============================================================================

/** Build full resolved base map from core + semantic sources (+ optional overlay files). */
function buildResolvedBaseMap(extraFiles: string[] = []): Record<string, string> {
  const rawMap: Record<string, string> = {};
  for (const dir of [`${ROOT}/sources/core`, `${ROOT}/sources/semantic`]) {
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter(f => f.endsWith('.json'))) {
      const parsed = JSON.parse(readFileSync(`${dir}/${f}`, 'utf-8'));
      Object.assign(rawMap, flattenDTCG(parsed));
    }
  }
  for (const file of extraFiles) {
    if (!existsSync(file)) continue;
    const parsed = JSON.parse(readFileSync(file, 'utf-8'));
    const flat = flattenDTCG(parsed);
    if (Object.keys(flat).length > 0) Object.assign(rawMap, flat);
  }
  const resolved: Record<string, string> = {};
  for (const [k, v] of Object.entries(rawMap)) resolved[k] = resolveRef(v, rawMap);
  // second pass for chained refs
  for (const [k, v] of Object.entries(resolved)) resolved[k] = resolveRef(v, resolved);
  return resolved;
}

/** Get resolved ARGB string for a color path; fall back to fallback if not present. */
function colorArgb(resolvedMap: Record<string, string>, path: string, fallback: string): string {
  const hex = resolvedMap[path];
  if (!hex) return fallback;
  if (hex.startsWith('#')) return hexToArgb(hex);
  return fallback;
}

/** Parse a px dimension string to a Dart double literal (e.g. '8px' → '8.0'). */
function pxToDouble(value: string): string {
  const n = parseFloat(String(value).replace('px', ''));
  if (Number.isNaN(n)) return '0.0';
  return Number.isInteger(n) ? `${n}.0` : String(n);
}

/** Format a category name to PascalCase for class names (background → Background). */
function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// =============================================================================
// Color theme dart emitter
// =============================================================================

function emitColorThemeDart(tree: ColorTree, resolvedMap: Record<string, string>): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'package:flutter/material.dart';");
  L.push("import 'shades.color.dart';\n");

  // ── BTechColorVariants ────────────────────────────────────────────────────
  L.push('/// A [Color] that also exposes named variants (hover, pressed, etc.).');
  L.push('/// Every leaf in the color token tree IS a [Color] (default value)');
  L.push('/// and additionally exposes named variant [Color]s. Variants that do not');
  L.push('/// exist in the source token fall back to the default color value.');
  L.push('class BTechColorVariants extends Color {');
  L.push('  const BTechColorVariants(');
  L.push('    super.value, {');
  for (const v of VARIANT_FIELDS) {
    L.push(`    required this.${v},`);
  }
  L.push('  });');
  L.push('');
  L.push(`  final Color ${VARIANT_FIELDS.join(', ')};`);
  L.push('}\n');

  // ── Per-category accessor classes ─────────────────────────────────────────
  const emitCategoryClass = (category: string) => {
    const subcats = tree[category];
    const className = `BTechColor${cap(category)}`;
    L.push(`class ${className} {`);
    L.push(`  const ${className}({`);
    for (const s of subcats) L.push(`    required this.${s.name},`);
    L.push('  });');
    L.push('');
    for (const s of subcats) L.push(`  final BTechColorVariants ${s.name};`);
    L.push('}\n');
  };

  for (const category of Object.keys(tree)) emitCategoryClass(category);

  // ── BTechColorTheme (ThemeExtension) ──────────────────────────────────────
  // All fields are derived dynamically from the color.json top-level keys.
  const categories = Object.keys(tree);
  L.push('class BTechColorTheme extends ThemeExtension<BTechColorTheme> {');
  L.push('  const BTechColorTheme({');
  for (const category of categories) L.push(`    required this.${category},`);
  L.push('  });');
  L.push('');
  for (const category of categories) {
    L.push(`  final BTechColor${cap(category)} ${category};`);
  }
  L.push('');
  L.push('  BTechColorTheme copyWith({');
  for (const category of categories) L.push(`    BTechColor${cap(category)}? ${category},`);
  L.push('  }) =>');
  L.push('      BTechColorTheme(');
  for (const category of categories) L.push(`        ${category}: ${category} ?? this.${category},`);
  L.push('      );');
  L.push('');
  L.push('  @override');
  L.push('  BTechColorTheme lerp(covariant ThemeExtension<BTechColorTheme>? other, double t) {');
  L.push('    if (other is! BTechColorTheme) return this;');
  L.push('    return this;');
  L.push('  }');
  L.push('}\n');

  // ── Emit default light values as nested const instances ──────────────────
  L.push('// ── Default light theme (resolved from semantic/color.json) ─────');
  L.push('const BTechColorTheme _defaultLight = BTechColorTheme(');
  for (const category of categories) {
    const className = `BTechColor${cap(category)}`;
    L.push(`  ${category}: ${className}(`);
    for (const sub of tree[category]) {
      const basePath = `color.${category}.${sub.name}.${sub.defaultKey}`;
      const baseArgb = colorArgb(resolvedMap, basePath, '0xFF000000');
      L.push(`    ${sub.name}: BTechColorVariants(${baseArgb},`);
      for (const field of VARIANT_FIELDS) {
        let argb: string;
        if (sub.variants.includes(field)) {
          argb = colorArgb(resolvedMap, `color.${category}.${sub.name}.${field}`, baseArgb);
        } else {
          argb = baseArgb;
        }
        L.push(`      ${field}: Color(${argb}),`);
      }
      L.push('    ),');
    }
    L.push('  ),');
  }
  L.push(');\n');

  // ── BTechColor static class ──────────────────────────────────────────────
  L.push('/// Static access to the active color theme (always light values).');
  L.push('/// For reactive light/dark switching, use `context.btechColor` instead.');
  L.push('abstract class BTechColor {');
  L.push('  static BTechColorTheme _light = _defaultLight;');
  L.push('  // Dark defaults to same as light until btechTheme(brightness: dark) activates it.');
  L.push('  // ignore: unused_field');
  L.push('  static BTechColorTheme _dark  = _defaultLight;');
  L.push('');
  for (const category of categories) {
    L.push(`  static BTechColor${cap(category)} get ${category} => _light.${category};`);
  }
  L.push('  // Raw primitive color swatches — BTechColor.shades.green[500]');
  L.push('  static const BTechShadesColor shades = BTechShadesColor();');
  L.push('');
  L.push('  /// Called by [buildBtechTheme] — do not call directly.');
  L.push('  static void activateBoth(BTechColorTheme light, BTechColorTheme dark) {');
  L.push('    _light = light;');
  L.push('    _dark  = dark;');
  L.push('  }');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// Radius theme dart emitter
// =============================================================================

function emitRadiusThemeDart(fields: RadiusField[]): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'dart:ui' show lerpDouble;");
  L.push("import 'package:flutter/material.dart';\n");

  L.push('class BTechRadiusTheme extends ThemeExtension<BTechRadiusTheme> {');
  L.push('  const BTechRadiusTheme({');
  for (const f of fields) L.push(`    required this.${f.name},`);
  L.push('  });');
  L.push('');
  for (const f of fields) L.push(`  final double ${f.name};`);
  L.push('');
  L.push('  BTechRadiusTheme copyWith({');
  for (const f of fields) L.push(`    double? ${f.name},`);
  L.push('  }) =>');
  L.push('      BTechRadiusTheme(');
  for (const f of fields) L.push(`        ${f.name}: ${f.name} ?? this.${f.name},`);
  L.push('      );');
  L.push('');
  L.push('  @override');
  L.push('  BTechRadiusTheme lerp(covariant ThemeExtension<BTechRadiusTheme>? other, double t) {');
  L.push('    if (other is! BTechRadiusTheme) return this;');
  L.push('    return BTechRadiusTheme(');
  for (const f of fields) L.push(`      ${f.name}: lerpDouble(${f.name}, other.${f.name}, t)!,`);
  L.push('    );');
  L.push('  }');
  L.push('}\n');

  L.push('/// Static access to the active radius theme.');
  L.push('abstract class BTechRadius {');
  L.push('  static BTechRadiusTheme _active = const BTechRadiusTheme(');
  for (const f of fields) L.push(`    ${f.name}: ${pxToDouble(f.value)},`);
  L.push('  );');
  L.push('');
  for (const f of fields) L.push(`  static double get ${f.name} => _active.${f.name};`);
  L.push('');
  L.push('  static void activate(BTechRadiusTheme t) => _active = t;');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// Font theme dart emitter
// =============================================================================

function emitFontThemeDart(sans: string): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'package:flutter/material.dart';\n");

  L.push('class BTechFontFamily {');
  L.push('  const BTechFontFamily({required this.sans});');
  L.push('  final String sans;');
  L.push('}\n');

  L.push('class BTechFontTheme extends ThemeExtension<BTechFontTheme> {');
  L.push('  const BTechFontTheme({required this.family});');
  L.push('  final BTechFontFamily family;');
  L.push('');
  L.push('  BTechFontTheme copyWith({BTechFontFamily? family}) =>');
  L.push('      BTechFontTheme(family: family ?? this.family);');
  L.push('');
  L.push('  @override');
  L.push('  BTechFontTheme lerp(covariant ThemeExtension<BTechFontTheme>? other, double t) => this;');
  L.push('}\n');

  L.push('/// Static access to the active font theme.');
  L.push('abstract class BTechFont {');
  L.push('  static BTechFontTheme _active = const BTechFontTheme(');
  L.push(`    family: BTechFontFamily(sans: '${sans.replace(/'/g, "\\'")}'),`);
  L.push('  );');
  L.push('');
  L.push('  static BTechFontFamily get family => _active.family;');
  L.push('');
  L.push('  static void activate(BTechFontTheme t) => _active = t;');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// theme_builder.dart + context.dart
// =============================================================================

function emitThemeBuilderDart(): string {
  return [
    HEADER,
    "import 'package:flutter/material.dart';",
    "import 'color/color.theme.dart';",
    "import 'radius/radius.theme.dart';",
    "import 'font/font.theme.dart';",
    '',
    '/// Builds a [ThemeData] with BTech design tokens registered as [ThemeExtension]s.',
    '///',
    "/// Call from each tenant's `btechTheme()` one-liner — logic lives here, not in the tenant.",
    '///',
    '/// ```dart',
    '/// MaterialApp(',
    '///   theme:     btechTheme(),',
    '///   darkTheme: btechTheme(brightness: Brightness.dark),',
    '/// )',
    '/// ```',
    'ThemeData buildBtechTheme(',
    '  BTechColorTheme colorLight,',
    '  BTechColorTheme colorDark,',
    '  BTechRadiusTheme radius,',
    '  BTechFontTheme font, {',
    '  Brightness brightness = Brightness.light,',
    '  ThemeData? base,',
    '}) {',
    '  BTechColor.activateBoth(colorLight, colorDark);',
    '  BTechRadius.activate(radius);',
    '  BTechFont.activate(font);',
    '  final activeColor = brightness == Brightness.dark ? colorDark : colorLight;',
    '  return (base ?? ThemeData(brightness: brightness))',
    '      .copyWith(extensions: [activeColor, radius, font]);',
    '}',
    '',
  ].join('\n');
}

function emitContextDart(): string {
  return [
    HEADER,
    "import 'package:flutter/material.dart';",
    "import 'color/color.theme.dart';",
    "import 'radius/radius.theme.dart';",
    "import 'font/font.theme.dart';",
    '',
    '/// Context extensions for reactive access to BTech design tokens.',
    '///',
    '/// [Theme.of(context)] returns the active ThemeData (light or dark),',
    '/// so [btechColor] automatically returns the correct theme for the current brightness.',
    '///',
    '/// Always use these in [btech_ui] components — reactive to both tenant AND light/dark mode.',
    'extension BTechContextExtension on BuildContext {',
    '  /// Active color theme — auto switches light/dark based on [ThemeMode].',
    '  BTechColorTheme  get btechColor  => Theme.of(this).extension<BTechColorTheme>()!;',
    '',
    '  /// Active radius theme.',
    '  BTechRadiusTheme get btechRadius => Theme.of(this).extension<BTechRadiusTheme>()!;',
    '',
    '  /// Active font theme.',
    '  BTechFontTheme   get btechFont   => Theme.of(this).extension<BTechFontTheme>()!;',
    '}',
    '',
  ].join('\n');
}

// =============================================================================
// Main entry
// =============================================================================

/**
 * Main entry — generates all 5 Dart files under platforms/flutter/lib/src/.
 * If resolvedBaseMap is not provided, one is built internally from core + semantic sources.
 */
export function generateFlutterThemeFiles(resolvedBaseMap?: Record<string, string>): void {
  const resolved = resolvedBaseMap ?? buildResolvedBaseMap([
    `${ROOT}/sources/semantic/color.dark.json`,
  ]);

  const tree = buildColorTree();
  const radiusFields = buildRadiusFields(resolved);
  const fontSans = buildFontSans(resolved);

  const DART_SRC = `${ROOT}/platforms/flutter/lib/src`;
  const colorDir = `${DART_SRC}/color`;
  const radiusDir = `${DART_SRC}/radius`;
  const fontDir = `${DART_SRC}/font`;
  mkdirSync(colorDir, { recursive: true });
  mkdirSync(radiusDir, { recursive: true });
  mkdirSync(fontDir, { recursive: true });

  writeFileSync(`${colorDir}/color.theme.dart`, emitColorThemeDart(tree, resolved));
  writeFileSync(`${radiusDir}/radius.theme.dart`, emitRadiusThemeDart(radiusFields));
  writeFileSync(`${fontDir}/font.theme.dart`, emitFontThemeDart(fontSans));
  writeFileSync(`${DART_SRC}/theme_builder.dart`, emitThemeBuilderDart());
  writeFileSync(`${DART_SRC}/context.dart`, emitContextDart());
}

// =============================================================================
// Standalone CLI entry — for quick testing (`pnpm exec tsx …flutter-theme-generator.ts`)
// =============================================================================

if (import.meta.url === `file://${process.argv[1]}`) {
  generateFlutterThemeFiles();
  // eslint-disable-next-line no-console
  console.log('[flutter-theme-generator] Generated 5 Dart files under platforms/flutter/lib/src/');
}
