import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { ROOT, flattenDTCG, resolveRef } from '../utils.js';
import { dartType, dartLiteral, tokenPathToGetter } from './flutter-base-token.js';

// =============================================================================
// generateFlutterTenantPackage
//
// Produces per-tenant Dart package at:
//   packages/platforms/flutter/tenants/{id}/
//     ├── pubspec.yaml
//     └── lib/
//         └── btech_tokens_{id}.dart   ← class BtechToken{Pascal} extends BtechToken
//
// Only override getters are emitted — everything else is inherited from BtechToken.
// =============================================================================
export function generateFlutterTenantPackage(
  tenantId: string,
  resolvedBaseMap: Record<string, string>,
): void {
  const overridePath = `${ROOT}/sources/tenants/${tenantId}/overrides.json`;
  if (!existsSync(overridePath)) {
    throw new Error(
      `[flutter-tenant] No overrides.json found for "${tenantId}" at ${overridePath}`,
    );
  }

  // Load + flatten tenant overrides
  const rawOverrides = flattenDTCG(JSON.parse(readFileSync(overridePath, 'utf-8')));

  // Resolve refs against base map
  const resolvedOverrides: Record<string, string> = {};
  for (const [k, v] of Object.entries(rawOverrides)) {
    resolvedOverrides[k] = resolveRef(v, resolvedBaseMap);
  }

  const pkgName = `btech_tokens_${tenantId.replace(/-/g, '_')}`;
  const libFile = `${pkgName}.dart`;
  // Class is always BtechToken — package name is the differentiator
  const className = 'BtechToken';

  // ── Build override getters ────────────────────────────────────────────────
  const seen = new Set<string>();
  const getters: string[] = [];

  for (const [path, value] of Object.entries(resolvedOverrides)) {
    if (value.startsWith('{')) continue; // unresolved ref
    const cleanPath = path.replace(/\.default$/, '');
    const getter    = tokenPathToGetter(cleanPath);

    if (seen.has(getter)) continue;
    seen.add(getter);

    // Only emit if value differs from base
    const baseValue = resolvedBaseMap[cleanPath] ?? resolvedBaseMap[`${cleanPath}.default`] ?? null;
    if (baseValue && baseValue.trim().toLowerCase() === value.trim().toLowerCase()) continue;

    const type        = dartType(value);
    const constPrefix = type === 'Color' ? 'const ' : '';
    getters.push(`  @override`);
    getters.push(`  ${type} get ${getter} => ${constPrefix}${dartLiteral(value, type)};`);
    getters.push('');
  }

  // ── Generate Dart file ────────────────────────────────────────────────────
  const dartLines: string[] = [
    `// AUTO-GENERATED by @btech/design-system — do not edit manually.`,
    `// Source: packages/tokens/sources/tenants/${tenantId}/overrides.json`,
    `// Run \`pnpm generate --tenant ${tenantId}\` to regenerate.`,
    `//`,
    `// ignore_for_file: lines_longer_than_80_chars`,
    ``,
    `library ${pkgName};`,
    ``,
    `import 'package:flutter/material.dart';`,
    `import 'package:btech_tokens/btech_tokens.dart' as base;`,
    ``,
    `/// Design tokens for the ${tenantId} tenant.`,
    `///`,
    `/// Extends [base.BtechToken] and overrides only the brand-specific values.`,
    `/// All non-overridden tokens are inherited from the base class.`,
    `///`,
    `/// Usage:`,
    `///   final token = BtechToken();`,
    `///   token.backgroundPrimary   // ${resolvedOverrides['color.background.primary.default'] ?? '(base value)'}`,
    `class ${className} extends base.BtechToken {`,
    `  const ${className}();`,
    ``,
  ];

  if (getters.length === 0) {
    dartLines.push(`  // No overrides — all values are identical to the base BtechToken.`);
    dartLines.push('');
  } else {
    dartLines.push(...getters);
  }

  dartLines.push('}', '');

  // ── Generate pubspec.yaml ─────────────────────────────────────────────────
  const pubspec = [
    `name: ${pkgName}`,
    `description: BTech design tokens for ${tenantId} tenant — generated by @btech/design-system`,
    `version: 1.0.0`,
    ``,
    `environment:`,
    `  sdk: '>=3.0.0 <4.0.0'`,
    `  flutter: '>=3.10.0'`,
    ``,
    `dependencies:`,
    `  flutter:`,
    `    sdk: flutter`,
    `  btech_tokens:`,
    `    path: ../../    # relative to packages/platforms/flutter/tenants/${tenantId}/`,
    ``,
  ].join('\n');

  // ── Write files ───────────────────────────────────────────────────────────
  const MONOREPO_ROOT = resolve(ROOT, '../..');
  const pkgDir = resolve(MONOREPO_ROOT, 'packages', 'platforms', 'flutter', 'tenants', tenantId);
  const libDir = resolve(pkgDir, 'lib');
  mkdirSync(libDir, { recursive: true });

  writeFileSync(resolve(pkgDir, 'pubspec.yaml'), pubspec, 'utf-8');
  writeFileSync(resolve(libDir, libFile), dartLines.join('\n'), 'utf-8');

  console.log(`  Flutter tenant — packages/platforms/flutter/tenants/${tenantId}/lib/${libFile}`);
}
