// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Flutter theme generator: derives BTechColorTheme tree from source JSON and
// emits 5 Dart files under platforms/flutter/lib/src/.

import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync } from 'fs';
import { ROOT, flattenDTCG, resolveRef, hexToArgb } from '../utils.js';

// =============================================================================
// Types
// =============================================================================

/** Dynamic map of category name → flat list of field names (dasherized, e.g. 'primary-subtle').
 *  Derived from the top-level keys of semantic/color.json (text, icon, border, bg, brand, ext).
 *  Each field name maps to a single Color — no sub-variants. */
export type ColorTree = Record<string, string[]>;

export interface RadiusField {
  /** e.g. 'interactive' */
  name: string;
  /** resolved px string, e.g. '8px' */
  value: string;
}

// =============================================================================
// Constants
// =============================================================================

const HEADER =
  '// AUTO-GENERATED by @btech/design-system — do not edit manually.\n' +
  '// Run `pnpm generate` to regenerate.\n' +
  '// ignore_for_file: lines_longer_than_80_chars\n';

// =============================================================================
// Tree derivation
// =============================================================================

/** Derive the color access tree from the semantic color JSON (structure only, no values).
 *  New flat model: each category (text, icon, border, bg, brand, ext) maps to a list
 *  of dasherized field names (e.g. 'primary-subtle'). Each field = one plain Color. */
export function buildColorTree(): ColorTree {
  const colorJson = JSON.parse(
    readFileSync(`${ROOT}/sources/semantic/color.json`, 'utf-8'),
  ) as { color: Record<string, Record<string, unknown>> };

  const tree: ColorTree = {};
  for (const [category, categoryNode] of Object.entries(colorJson.color)) {
    tree[category] = Object.keys(categoryNode).filter(k => !k.startsWith('$'));
  }
  return tree;
}

/** Get resolved radius fields from the base map. */
export function buildRadiusFields(resolvedMap: Record<string, string>): RadiusField[] {
  const radiusJson = JSON.parse(
    readFileSync(`${ROOT}/sources/semantic/radius.json`, 'utf-8'),
  ) as { radius: Record<string, unknown> };
  const out: RadiusField[] = [];
  for (const name of Object.keys(radiusJson.radius)) {
    const key = `radius.${name}`;
    const resolved = resolvedMap[key] ?? '0px';
    out.push({ name, value: resolved });
  }
  return out;
}

/** Get resolved font family sans value (first family name, unquoted). */
export function buildFontSans(resolvedMap: Record<string, string>): string {
  const raw = resolvedMap['typography.fontFamily.sans'] ?? 'Inter';
  return raw.split(',')[0].trim().replace(/^['"]|['"]$/g, '');
}

// =============================================================================
// Helpers
// =============================================================================

/** Resolve a raw flat map in two passes to handle chained references. */
function resolveMap(rawMap: Record<string, string>): Record<string, string> {
  const resolved: Record<string, string> = {};
  for (const [k, v] of Object.entries(rawMap)) resolved[k] = resolveRef(v, rawMap);
  for (const [k, v] of Object.entries(resolved)) resolved[k] = resolveRef(v, resolved);
  return resolved;
}

/**
 * Build the resolved LIGHT base map from core + semantic sources.
 * Dark-override files (*.dark.json) are intentionally excluded so this map
 * contains only light-mode values — use buildDarkResolvedBaseMap() for dark.
 */
function buildResolvedBaseMap(): Record<string, string> {
  const rawMap: Record<string, string> = {};
  for (const dir of [`${ROOT}/sources/core`, `${ROOT}/sources/semantic`]) {
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter(f => f.endsWith('.json') && !f.includes('.dark.'))) {
      Object.assign(rawMap, flattenDTCG(JSON.parse(readFileSync(`${dir}/${f}`, 'utf-8'))));
    }
  }
  return resolveMap(rawMap);
}

/**
 * Build the resolved DARK base map.
 * Starts from all light values, then applies semantic/color.dark.json overrides on top.
 * Exported so flutter-tenant-format.ts can use it for _btechColorDark.
 */
export function buildDarkResolvedBaseMap(): Record<string, string> {
  const rawMap: Record<string, string> = {};
  for (const dir of [`${ROOT}/sources/core`, `${ROOT}/sources/semantic`]) {
    if (!existsSync(dir)) continue;
    // Load all non-dark files first (establishes light base)
    for (const f of readdirSync(dir).filter(f => f.endsWith('.json') && !f.includes('.dark.'))) {
      Object.assign(rawMap, flattenDTCG(JSON.parse(readFileSync(`${dir}/${f}`, 'utf-8'))));
    }
  }
  // Apply dark overrides on top (keys that exist in dark file override the light values)
  const darkFile = `${ROOT}/sources/semantic/color.dark.json`;
  if (existsSync(darkFile)) {
    Object.assign(rawMap, flattenDTCG(JSON.parse(readFileSync(darkFile, 'utf-8'))));
  }
  return resolveMap(rawMap);
}

/** 'primary-subtle' → 'primarySubtle' */
export function dashToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** 'rgba(24,28,32,0.8)' → '0xCC181C20' */
export function rgbaToArgb(rgba: string): string {
  const m = rgba.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\s*\)/);
  if (!m) return '0xFF000000';
  const r = parseInt(m[1]).toString(16).padStart(2, '0').toUpperCase();
  const g = parseInt(m[2]).toString(16).padStart(2, '0').toUpperCase();
  const b = parseInt(m[3]).toString(16).padStart(2, '0').toUpperCase();
  const a = m[4] !== undefined
    ? Math.round(parseFloat(m[4]) * 255).toString(16).padStart(2, '0').toUpperCase()
    : 'FF';
  return `0x${a}${r}${g}${b}`;
}

/** Resolve a flat color path to a Dart ARGB literal, handling #hex and rgba(). */
function colorArgbFlat(resolvedMap: Record<string, string>, path: string, fallback: string): string {
  const val = resolvedMap[path];
  if (!val) return fallback;
  if (val.startsWith('rgba(') || val.startsWith('rgba (')) return rgbaToArgb(val);
  if (val.startsWith('#')) return hexToArgb(val);
  if (val.startsWith('0x')) return val;
  return fallback;
}

/** Parse a px dimension string to a Dart double literal (e.g. '8px' → '8.0'). */
function pxToDouble(value: string): string {
  const n = parseFloat(String(value).replace('px', ''));
  if (Number.isNaN(n)) return '0.0';
  return Number.isInteger(n) ? `${n}.0` : String(n);
}

/** Format a category name to PascalCase for class names (background → Background). */
function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// =============================================================================
// Color theme dart emitter
// =============================================================================

function emitColorThemeDart(tree: ColorTree, resolvedMap: Record<string, string>): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'package:flutter/material.dart';");
  L.push("import 'shades.color.dart';\n");

  // ── Per-category accessor classes — each field is a plain Color ──────────
  for (const [category, fields] of Object.entries(tree)) {
    const className = `BTechColor${cap(category)}`;
    L.push(`class ${className} {`);
    L.push(`  const ${className}({`);
    for (const f of fields) L.push(`    required this.${dashToCamel(f)},`);
    L.push('  });');
    L.push('');
    for (const f of fields) L.push(`  final Color ${dashToCamel(f)};`);
    L.push('}\n');
  }

  // ── BTechColorTheme (ThemeExtension) ──────────────────────────────────────
  const categories = Object.keys(tree);
  L.push('class BTechColorTheme extends ThemeExtension<BTechColorTheme> {');
  L.push('  const BTechColorTheme({');
  for (const cat of categories) L.push(`    required this.${cat},`);
  L.push('  });');
  L.push('');
  for (const cat of categories) L.push(`  final BTechColor${cap(cat)} ${cat};`);
  L.push('');
  L.push('  BTechColorTheme copyWith({');
  for (const cat of categories) L.push(`    BTechColor${cap(cat)}? ${cat},`);
  L.push('  }) =>');
  L.push('      BTechColorTheme(');
  for (const cat of categories) L.push(`        ${cat}: ${cat} ?? this.${cat},`);
  L.push('      );');
  L.push('');
  L.push('  @override');
  L.push('  BTechColorTheme lerp(covariant ThemeExtension<BTechColorTheme>? other, double t) {');
  L.push('    if (other is! BTechColorTheme) return this;');
  L.push('    return this;');
  L.push('  }');
  L.push('}\n');

  // ── Default light const instance ──────────────────────────────────────────
  L.push('// ── Default light theme (resolved from semantic/color.json) ─────');
  L.push('const BTechColorTheme _defaultLight = BTechColorTheme(');
  for (const [category, fields] of Object.entries(tree)) {
    const className = `BTechColor${cap(category)}`;
    L.push(`  ${category}: ${className}(`);
    for (const f of fields) {
      const argb = colorArgbFlat(resolvedMap, `color.${category}.${f}`, '0xFF000000');
      L.push(`    ${dashToCamel(f)}: Color(${argb}),`);
    }
    L.push('  ),');
  }
  L.push(');\n');

  // ── BTechColor static class ───────────────────────────────────────────────
  L.push('/// Static access to the active color theme (always light values).');
  L.push('/// For reactive light/dark switching, use `context.btechColor` instead.');
  L.push('abstract class BTechColor {');
  L.push('  static BTechColorTheme _light = _defaultLight;');
  L.push('  // ignore: unused_field');
  L.push('  static BTechColorTheme _dark  = _defaultLight;');
  L.push('');
  for (const cat of categories) {
    L.push(`  static BTechColor${cap(cat)} get ${cat} => _light.${cat};`);
  }
  L.push('  // Raw primitive color swatches — BTechColor.shades.green[500]');
  L.push('  static const BTechShadesColor shades = BTechShadesColor();');
  L.push('');
  L.push('  /// Called by [buildBtechTheme] — do not call directly.');
  L.push('  static void activateBoth(BTechColorTheme light, BTechColorTheme dark) {');
  L.push('    _light = light;');
  L.push('    _dark  = dark;');
  L.push('  }');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// Radius theme dart emitter
// =============================================================================

function emitRadiusThemeDart(fields: RadiusField[]): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'dart:ui' show lerpDouble;");
  L.push("import 'package:flutter/material.dart';\n");

  L.push('class BTechRadiusTheme extends ThemeExtension<BTechRadiusTheme> {');
  L.push('  const BTechRadiusTheme({');
  for (const f of fields) L.push(`    required this.${f.name},`);
  L.push('  });');
  L.push('');
  for (const f of fields) L.push(`  final double ${f.name};`);
  L.push('');
  L.push('  BTechRadiusTheme copyWith({');
  for (const f of fields) L.push(`    double? ${f.name},`);
  L.push('  }) =>');
  L.push('      BTechRadiusTheme(');
  for (const f of fields) L.push(`        ${f.name}: ${f.name} ?? this.${f.name},`);
  L.push('      );');
  L.push('');
  L.push('  @override');
  L.push('  BTechRadiusTheme lerp(covariant ThemeExtension<BTechRadiusTheme>? other, double t) {');
  L.push('    if (other is! BTechRadiusTheme) return this;');
  L.push('    return BTechRadiusTheme(');
  for (const f of fields) L.push(`      ${f.name}: lerpDouble(${f.name}, other.${f.name}, t)!,`);
  L.push('    );');
  L.push('  }');
  L.push('}\n');

  L.push('/// Static access to the active radius theme.');
  L.push('abstract class BTechRadius {');
  L.push('  static BTechRadiusTheme _active = const BTechRadiusTheme(');
  for (const f of fields) L.push(`    ${f.name}: ${pxToDouble(f.value)},`);
  L.push('  );');
  L.push('');
  for (const f of fields) L.push(`  static double get ${f.name} => _active.${f.name};`);
  L.push('');
  L.push('  static void activate(BTechRadiusTheme t) => _active = t;');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// Font theme dart emitter
// =============================================================================

function emitFontThemeDart(sans: string): string {
  const L: string[] = [];
  L.push(HEADER);
  L.push("import 'package:flutter/material.dart';");
  // Typography instances for BTechFont.heading / .subheading / .body
  L.push("import 'heading.dart';");
  L.push("import 'subheading.dart';");
  L.push("import 'body.dart';\n");

  L.push('/// Font-family data class — holds the active sans-serif family name.');
  L.push('class BTechFontFamily {');
  L.push('  const BTechFontFamily({required this.sans});');
  L.push('  final String sans;');
  L.push('}\n');

  L.push('class BTechFontTheme extends ThemeExtension<BTechFontTheme> {');
  L.push('  const BTechFontTheme({required this.family});');
  L.push('  final BTechFontFamily family;');
  L.push('');
  L.push('  BTechFontTheme copyWith({BTechFontFamily? family}) =>');
  L.push('      BTechFontTheme(family: family ?? this.family);');
  L.push('');
  L.push('  @override');
  L.push('  BTechFontTheme lerp(covariant ThemeExtension<BTechFontTheme>? other, double t) => this;');
  L.push('}\n');

  L.push('/// Static access to the active font theme.');
  L.push('/// - BTechFont.family.sans         — active sans-serif family name (tenant-switchable)');
  L.push('/// - BTechFont.heading.h1          — TextStyle (always uses active font family)');
  L.push('/// - BTechFont.body.medium         — TextStyle');
  L.push('/// For reactive dark/light font colours in widgets, prefer context.btechFont.');
  L.push('abstract class BTechFont {');
  L.push('  static BTechFontTheme _active = const BTechFontTheme(');
  L.push(`    family: BTechFontFamily(sans: '${sans.replace(/'/g, "\\'")}'),`);
  L.push('  );');
  L.push('');
  L.push('  static BTechFontFamily get family => _active.family;');
  L.push('');
  L.push('  /// Semantic typography scale — TextStyle instances derived from the active font.');
  L.push('  static final BTechFontHeading    heading    = BTechFontHeading();');
  L.push('  static final BTechFontSubHeading subheading = BTechFontSubHeading();');
  L.push('  static final BTechFontBody       body       = BTechFontBody();');
  L.push('');
  L.push('  static void activate(BTechFontTheme t) => _active = t;');
  L.push('}');
  L.push('');

  return L.join('\n');
}

// =============================================================================
// theme_builder.dart + context.dart
// =============================================================================

function emitThemeBuilderDart(): string {
  return [
    HEADER,
    "import 'package:flutter/material.dart';",
    "import 'color/color.theme.dart';",
    "import 'radius/radius.theme.dart';",
    "import 'typography/font.theme.dart';",
    '',
    '/// Builds a [ThemeData] with BTech design tokens registered as [ThemeExtension]s.',
    '///',
    "/// Call from each tenant's `btechTheme()` one-liner — logic lives here, not in the tenant.",
    '///',
    '/// ```dart',
    '/// MaterialApp(',
    '///   theme:     btechTheme(),',
    '///   darkTheme: btechTheme(brightness: Brightness.dark),',
    '/// )',
    '/// ```',
    'ThemeData buildBtechTheme(',
    '  BTechColorTheme colorLight,',
    '  BTechColorTheme colorDark,',
    '  BTechRadiusTheme radius,',
    '  BTechFontTheme font, {',
    '  Brightness brightness = Brightness.light,',
    '  ThemeData? base,',
    '}) {',
    '  BTechColor.activateBoth(colorLight, colorDark);',
    '  BTechRadius.activate(radius);',
    '  BTechFont.activate(font);',
    '  final activeColor = brightness == Brightness.dark ? colorDark : colorLight;',
    '  return (base ?? ThemeData(brightness: brightness))',
    '      .copyWith(extensions: [activeColor, radius, font]);',
    '}',
    '',
  ].join('\n');
}

function emitContextDart(): string {
  return [
    HEADER,
    "import 'package:flutter/material.dart';",
    "import 'color/color.theme.dart';",
    "import 'radius/radius.theme.dart';",
    "import 'typography/font.theme.dart';",
    '',
    '/// Context extensions for reactive access to BTech design tokens.',
    '///',
    '/// [Theme.of(context)] returns the active ThemeData (light or dark),',
    '/// so [btechColor] automatically returns the correct theme for the current brightness.',
    '///',
    '/// Always use these in [btech_ui] components — reactive to both tenant AND light/dark mode.',
    'extension BTechContextExtension on BuildContext {',
    '  /// Active color theme — auto switches light/dark based on [ThemeMode].',
    '  BTechColorTheme  get btechColor  => Theme.of(this).extension<BTechColorTheme>()!;',
    '',
    '  /// Active radius theme.',
    '  BTechRadiusTheme get btechRadius => Theme.of(this).extension<BTechRadiusTheme>()!;',
    '',
    '  /// Active font theme.',
    '  BTechFontTheme   get btechFont   => Theme.of(this).extension<BTechFontTheme>()!;',
    '}',
    '',
  ].join('\n');
}

// =============================================================================
// Main entry
// =============================================================================

/**
 * Main entry — generates all 5 Dart files under platforms/flutter/lib/src/.
 * If resolvedBaseMap is not provided, one is built internally from core + semantic sources.
 */
export function generateFlutterThemeFiles(resolvedBaseMap?: Record<string, string>): void {
  // Use pure light map — dark values are NOT merged here so _defaultLight stays light-only.
  const resolved = resolvedBaseMap ?? buildResolvedBaseMap();

  const tree = buildColorTree();
  const radiusFields = buildRadiusFields(resolved);
  const fontSans = buildFontSans(resolved);

  const DART_SRC = `${ROOT}/platforms/flutter/lib/src`;
  const colorDir = `${DART_SRC}/color`;
  const radiusDir = `${DART_SRC}/radius`;
  const typoDir  = `${DART_SRC}/typography`;
  mkdirSync(colorDir,  { recursive: true });
  mkdirSync(radiusDir, { recursive: true });
  mkdirSync(typoDir,   { recursive: true });

  writeFileSync(`${colorDir}/color.theme.dart`,   emitColorThemeDart(tree, resolved));
  writeFileSync(`${radiusDir}/radius.theme.dart`,  emitRadiusThemeDart(radiusFields));
  // font.theme.dart lives alongside the other typography files — single font folder.
  writeFileSync(`${typoDir}/font.theme.dart`,      emitFontThemeDart(fontSans));
  writeFileSync(`${DART_SRC}/theme_builder.dart`, emitThemeBuilderDart());
  writeFileSync(`${DART_SRC}/context.dart`, emitContextDart());
}

// =============================================================================
// Standalone CLI entry — for quick testing (`pnpm exec tsx …flutter-theme-generator.ts`)
// =============================================================================

if (import.meta.url === `file://${process.argv[1]}`) {
  generateFlutterThemeFiles();
  // eslint-disable-next-line no-console
  console.log('[flutter-theme-generator] Generated 5 Dart files under platforms/flutter/lib/src/');
}
