// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechBackgroundColor {
  readonly surface = '#f9fafb' as const;
  readonly surfaceSubtle = '#f3f4f6' as const;
  readonly surfaceRaised = '#ffffff' as const;
  readonly primary = '#15803d' as const;
  readonly primaryHover = '#166534' as const;
  readonly secondary = '#f0fdf4' as const;
  readonly secondaryHover = '#dcfce7' as const;
  readonly danger = '#dc2626' as const;
  readonly dangerHover = '#b91c1c' as const;
  readonly success = '#22c55e' as const;
  readonly successHover = '#16a34a' as const;
  readonly warning = '#fb923c' as const;
  readonly warningHover = '#f97316' as const;
}

