// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechShadesBlueColor {
  readonly s50 = '#eff6ff' as const;
  readonly s100 = '#dbeafe' as const;
  readonly s200 = '#bfdbfe' as const;
  readonly s300 = '#93c5fd' as const;
  readonly s400 = '#60a5fa' as const;
  readonly s500 = '#3b82f6' as const;
  readonly s600 = '#2563eb' as const;
  readonly s700 = '#1d4ed8' as const;
  readonly s800 = '#1e40af' as const;
  readonly s900 = '#1e3a8a' as const;
}

export class BTechShadesGreenColor {
  readonly s50 = '#f0fdf4' as const;
  readonly s100 = '#dcfce7' as const;
  readonly s200 = '#bbf7d0' as const;
  readonly s300 = '#86efac' as const;
  readonly s400 = '#4ade80' as const;
  readonly s500 = '#22c55e' as const;
  readonly s600 = '#16a34a' as const;
  readonly s700 = '#15803d' as const;
  readonly s800 = '#166534' as const;
  readonly s900 = '#14532d' as const;
}

export class BTechShadesOrangeColor {
  readonly s50 = '#fff7ed' as const;
  readonly s100 = '#ffedd5' as const;
  readonly s200 = '#fed7aa' as const;
  readonly s300 = '#fdba74' as const;
  readonly s400 = '#fb923c' as const;
  readonly s500 = '#f97316' as const;
  readonly s600 = '#ea580c' as const;
  readonly s700 = '#c2410c' as const;
  readonly s800 = '#9a3412' as const;
  readonly s900 = '#7c2d12' as const;
}

export class BTechShadesRedColor {
  readonly s50 = '#fef2f2' as const;
  readonly s100 = '#fee2e2' as const;
  readonly s200 = '#fecaca' as const;
  readonly s300 = '#fca5a5' as const;
  readonly s400 = '#f87171' as const;
  readonly s500 = '#ef4444' as const;
  readonly s600 = '#dc2626' as const;
  readonly s700 = '#b91c1c' as const;
  readonly s800 = '#991b1b' as const;
  readonly s900 = '#7f1d1d' as const;
}

export class BTechShadesYellowColor {
  readonly s50 = '#fefce8' as const;
  readonly s100 = '#fef9c3' as const;
  readonly s200 = '#fef08a' as const;
  readonly s300 = '#fde047' as const;
  readonly s400 = '#facc15' as const;
  readonly s500 = '#eab308' as const;
  readonly s600 = '#ca8a04' as const;
  readonly s700 = '#a16207' as const;
  readonly s800 = '#854d0e' as const;
  readonly s900 = '#713f12' as const;
}

export class BTechShadesPinkColor {
  readonly s50 = '#fdf2f8' as const;
  readonly s100 = '#fce7f3' as const;
  readonly s200 = '#fbcfe8' as const;
  readonly s300 = '#f9a8d4' as const;
  readonly s400 = '#f472b6' as const;
  readonly s500 = '#ec4899' as const;
  readonly s600 = '#db2777' as const;
  readonly s700 = '#be185d' as const;
  readonly s800 = '#9d174d' as const;
  readonly s900 = '#831843' as const;
}

export class BTechShadesPurpleColor {
  readonly s50 = '#faf5ff' as const;
  readonly s100 = '#f3e8ff' as const;
  readonly s200 = '#e9d5ff' as const;
  readonly s300 = '#d8b4fe' as const;
  readonly s400 = '#c084fc' as const;
  readonly s500 = '#a855f7' as const;
  readonly s600 = '#9333ea' as const;
  readonly s700 = '#7e22ce' as const;
  readonly s800 = '#6b21a8' as const;
  readonly s900 = '#581c87' as const;
}

export class BTechShadesTealColor {
  readonly s50 = '#f0fdfa' as const;
  readonly s100 = '#ccfbf1' as const;
  readonly s200 = '#99f6e4' as const;
  readonly s300 = '#5eead4' as const;
  readonly s400 = '#2dd4bf' as const;
  readonly s500 = '#14b8a6' as const;
  readonly s600 = '#0d9488' as const;
  readonly s700 = '#0f766e' as const;
  readonly s800 = '#115e59' as const;
  readonly s900 = '#134e4a' as const;
}

export class BTechShadesNeutralColor {
  readonly s0 = '#ffffff' as const;
  readonly s50 = '#f9fafb' as const;
  readonly s100 = '#f3f4f6' as const;
  readonly s200 = '#e5e7eb' as const;
  readonly s300 = '#d1d5db' as const;
  readonly s400 = '#9ca3af' as const;
  readonly s500 = '#6b7280' as const;
  readonly s600 = '#4b5563' as const;
  readonly s700 = '#374151' as const;
  readonly s800 = '#1f2937' as const;
  readonly s900 = '#111827' as const;
  readonly s1000 = '#000000' as const;
}

export class BTechShadesColor {
  readonly blue = new BTechShadesBlueColor();
  readonly green = new BTechShadesGreenColor();
  readonly orange = new BTechShadesOrangeColor();
  readonly red = new BTechShadesRedColor();
  readonly yellow = new BTechShadesYellowColor();
  readonly pink = new BTechShadesPinkColor();
  readonly purple = new BTechShadesPurpleColor();
  readonly teal = new BTechShadesTealColor();
  readonly neutral = new BTechShadesNeutralColor();
}

