// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechShadesBlueColor {
  readonly s50 = '#eff6ff' as const;
  readonly s100 = '#dbeafe' as const;
  readonly s200 = '#bfdbfe' as const;
  readonly s300 = '#93c5fd' as const;
  readonly s400 = '#60a5fa' as const;
  readonly s500 = '#3b82f6' as const;
  readonly s600 = '#2563eb' as const;
  readonly s700 = '#1d4ed8' as const;
  readonly s800 = '#1e40af' as const;
  readonly s900 = '#1e3a8a' as const;
}

export class BTechShadesGreenColor {
  readonly s50 = '#f0fdf4' as const;
  readonly s100 = '#dcfce7' as const;
  readonly s200 = '#bbf7d0' as const;
  readonly s300 = '#86efac' as const;
  readonly s400 = '#4ade80' as const;
  readonly s500 = '#22c55e' as const;
  readonly s600 = '#16a34a' as const;
  readonly s700 = '#15803d' as const;
  readonly s800 = '#166534' as const;
  readonly s900 = '#14532d' as const;
}

export class BTechShadesOrangeColor {
  readonly s50 = '#fff7ed' as const;
  readonly s100 = '#ffedd5' as const;
  readonly s200 = '#fed7aa' as const;
  readonly s300 = '#fdba74' as const;
  readonly s400 = '#fb923c' as const;
  readonly s500 = '#f97316' as const;
  readonly s600 = '#ea580c' as const;
  readonly s700 = '#c2410c' as const;
  readonly s800 = '#9a3412' as const;
  readonly s900 = '#7c2d12' as const;
}

export class BTechShadesRedColor {
  readonly s500 = '#ef4444' as const;
  readonly s600 = '#dc2626' as const;
  readonly s700 = '#b91c1c' as const;
  readonly s800 = '#991b1b' as const;
}

export class BTechShadesNeutralColor {
  readonly s0 = '#ffffff' as const;
  readonly s50 = '#f9fafb' as const;
  readonly s100 = '#f3f4f6' as const;
  readonly s200 = '#e5e7eb' as const;
  readonly s300 = '#d1d5db' as const;
  readonly s400 = '#9ca3af' as const;
  readonly s500 = '#6b7280' as const;
  readonly s600 = '#4b5563' as const;
  readonly s700 = '#374151' as const;
  readonly s800 = '#1f2937' as const;
  readonly s900 = '#111827' as const;
  readonly s1000 = '#000000' as const;
}

export class BTechShadesColor {
  readonly blue = new BTechShadesBlueColor();
  readonly green = new BTechShadesGreenColor();
  readonly orange = new BTechShadesOrangeColor();
  readonly red = new BTechShadesRedColor();
  readonly neutral = new BTechShadesNeutralColor();
}

