// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export const BTechFontFamily = {
  sans: 'Geist',
  mono: 'JetBrains Mono',
} as const;

export const BTechFontSize = {
  s3xs: 8,
  s2xs: 10,
  xs: 12,
  sm: 14,
  md: 16,
  lg: 18,
  xl: 20,
  s2xl: 24,
  s3xl: 28,
  s4xl: 32,
  s5xl: 40,
} as const;

export const BTechFontWeight = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
} as const;

export const BTechLineHeight = {
  s2xs: 12,
  xs: 16,
  sm: 20,
  md: 24,
  lg: 28,
  xl: 32,
  s2xl: 36,
  s3xl: 40,
  s4xl: 48,
} as const;

export const BTechFont = {
  heading: {
    fontFamily: 'Geist',
    fontWeight: 700,
    lineHeight: NaN,
  },
  body: {
    fontFamily: 'Geist',
    fontSize: 16,
    fontWeight: 400,
    lineHeight: NaN,
  },
} as const;

