// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

/**
 * All valid BTech design token paths.
 * Mirrors Atlassian's token naming approach — semantic, predictable, autocomplete-friendly.
 *
 * Grammar: [category].[property].[role].[emphasis].[state]
 *
 * @example
 * 'color.background.primary'        — primary brand background
 * 'color.text.neutral.subtle'       — secondary text color
 * 'color.stroke.neutral'            — default border/stroke
 * 'spacing.md'                      — medium spacing (16px)
 * 'radius.interactive'              — button/input border radius
 */
export type TokenPath =
  | 'button.danger.bg'
  | 'button.danger.bgHover'
  | 'button.danger.border'
  | 'button.danger.fg'
  | 'button.danger.radius'
  | 'button.primary.bg'
  | 'button.primary.bgHover'
  | 'button.primary.border'
  | 'button.primary.fg'
  | 'button.primary.radius'
  | 'button.secondary.bg'
  | 'button.secondary.bgHover'
  | 'button.secondary.border'
  | 'button.secondary.fg'
  | 'button.secondary.radius'
  | 'button.size.lg.fontSize'
  | 'button.size.lg.paddingX'
  | 'button.size.lg.paddingY'
  | 'button.size.md.fontSize'
  | 'button.size.md.paddingX'
  | 'button.size.md.paddingY'
  | 'button.size.sm.fontSize'
  | 'button.size.sm.paddingX'
  | 'button.size.sm.paddingY'
  | 'color.background.danger'
  | 'color.background.danger.hover'
  | 'color.background.primary'
  | 'color.background.primary.hover'
  | 'color.background.secondary'
  | 'color.background.secondary.hover'
  | 'color.background.success'
  | 'color.background.success.hover'
  | 'color.background.surface'
  | 'color.background.surface.raised'
  | 'color.background.surface.subtle'
  | 'color.background.warning'
  | 'color.background.warning.hover'
  | 'color.blue.100'
  | 'color.blue.200'
  | 'color.blue.300'
  | 'color.blue.400'
  | 'color.blue.50'
  | 'color.blue.500'
  | 'color.blue.600'
  | 'color.blue.700'
  | 'color.blue.800'
  | 'color.blue.900'
  | 'color.green.100'
  | 'color.green.200'
  | 'color.green.300'
  | 'color.green.400'
  | 'color.green.50'
  | 'color.green.500'
  | 'color.green.600'
  | 'color.green.700'
  | 'color.green.800'
  | 'color.green.900'
  | 'color.neutral.0'
  | 'color.neutral.100'
  | 'color.neutral.1000'
  | 'color.neutral.200'
  | 'color.neutral.300'
  | 'color.neutral.400'
  | 'color.neutral.50'
  | 'color.neutral.500'
  | 'color.neutral.600'
  | 'color.neutral.700'
  | 'color.neutral.800'
  | 'color.neutral.900'
  | 'color.orange.100'
  | 'color.orange.200'
  | 'color.orange.300'
  | 'color.orange.400'
  | 'color.orange.50'
  | 'color.orange.500'
  | 'color.orange.600'
  | 'color.orange.700'
  | 'color.orange.800'
  | 'color.orange.900'
  | 'color.red.500'
  | 'color.red.600'
  | 'color.red.700'
  | 'color.red.800'
  | 'color.stroke.danger'
  | 'color.stroke.neutral'
  | 'color.stroke.neutral.strong'
  | 'color.stroke.primary'
  | 'color.text.danger.base'
  | 'color.text.danger.bolder'
  | 'color.text.neutral'
  | 'color.text.neutral.disabled'
  | 'color.text.neutral.inverse'
  | 'color.text.neutral.subtle'
  | 'color.text.on.danger'
  | 'color.text.on.primary'
  | 'color.text.on.secondary'
  | 'color.text.success.base'
  | 'color.text.success.bolder'
  | 'color.text.warning.base'
  | 'color.text.warning.bolder'
  | 'motion.duration.fast'
  | 'motion.duration.normal'
  | 'motion.duration.slow'
  | 'motion.easing.ease'
  | 'motion.easing.easeIn'
  | 'motion.easing.easeOut'
  | 'motion.easing.linear'
  | 'radius.badge'
  | 'radius.card'
  | 'radius.full'
  | 'radius.interactive'
  | 'radius.lg'
  | 'radius.md'
  | 'radius.none'
  | 'radius.sm'
  | 'radius.tooltip'
  | 'radius.xl'
  | 'shadow.lg'
  | 'shadow.md'
  | 'shadow.none'
  | 'shadow.sm'
  | 'shadow.xl'
  | 'spacing.lg'
  | 'spacing.md'
  | 'spacing.sm'
  | 'spacing.xl'
  | 'spacing.xl2'
  | 'spacing.xl3'
  | 'spacing.xl4'
  | 'spacing.xs'
  | 'typography.body.fontFamily'
  | 'typography.body.fontSize'
  | 'typography.body.fontWeight'
  | 'typography.body.lineHeight'
  | 'typography.code.fontFamily'
  | 'typography.code.fontSize'
  | 'typography.fontFamily.mono'
  | 'typography.fontFamily.sans'
  | 'typography.fontSize.2xl'
  | 'typography.fontSize.3xl'
  | 'typography.fontSize.4xl'
  | 'typography.fontSize.base'
  | 'typography.fontSize.lg'
  | 'typography.fontSize.sm'
  | 'typography.fontSize.xl'
  | 'typography.fontSize.xs'
  | 'typography.fontWeight.bold'
  | 'typography.fontWeight.medium'
  | 'typography.fontWeight.regular'
  | 'typography.fontWeight.semibold'
  | 'typography.heading.fontFamily'
  | 'typography.heading.fontWeight'
  | 'typography.heading.lineHeight'
  | 'typography.label.fontFamily'
  | 'typography.label.fontSize'
  | 'typography.label.fontWeight'
  | 'typography.label.lineHeight'
  | 'typography.letterSpacing.normal'
  | 'typography.letterSpacing.tight'
  | 'typography.letterSpacing.wide'
  | 'typography.lineHeight.normal'
  | 'typography.lineHeight.relaxed'
  | 'typography.lineHeight.tight'
  | 'zIndex.base'
  | 'zIndex.dropdown'
  | 'zIndex.modal'
  | 'zIndex.overlay'
  | 'zIndex.raised'
  | 'zIndex.sticky'
  | 'zIndex.toast'
  | 'zIndex.tooltip'

/**
 * Returns the CSS custom property reference for a design token.
 * Type-safe wrapper — analogous to Atlassian's `token()` from `@atlaskit/tokens`.
 *
 * @example
 * import { token } from '@ramaMS06/tokens-web'
 *
 * // CSS-in-JS / inline style / Vue :style
 * const styles = {
 *   background:   token('color.background.primary'),
 *   color:        token('color.text.on-primary'),
 *   padding:      token('spacing.md'),
 *   borderRadius: token('radius.interactive'),
 * }
 *
 * // With CSS fallback
 * token('color.background.primary', '#15803d')
 * // → "var(--btech-color-background-primary, #15803d)"
 *
 * @param path     - A valid BTech token path (fully type-checked, autocomplete available)
 * @param fallback - Optional CSS fallback value if the variable is not defined
 * @returns CSS var() string ready for use in style objects or CSS-in-JS
 */
export function token(path: TokenPath, fallback?: string): string {
  const cssVar = `--btech-${path.replace(/\./g, '-')}`;
  return fallback ? `var(${cssVar}, ${fallback})` : `var(${cssVar})`;
}

/**
 * Returns the raw CSS variable name for a token (without var() wrapper).
 * Useful when composing CSS manually, in SCSS `#{}` interpolation,
 * or passing to third-party libraries that expect a variable name.
 *
 * @example
 * cssVar('color.background.primary')
 * // → '--btech-color-background-primary'
 *
 * @param path - A valid BTech token path
 */
export function cssVar(path: TokenPath): string {
  return `--btech-${path.replace(/\./g, '-')}`;
}
