// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Body typography tokens.
class BTechBodyFont {
  const BTechBodyFont();
  final String fontFamily = 'Inter';
  final double fontSize = 16;
  final FontWeight fontWeight = FontWeight.w400;
  final double lineHeight = 1.5;
}

