// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'heading.dart';
import 'subheading.dart';
import 'body.dart';

/// Primitive font family tokens.
abstract class BTechFontFamily {
  static const String sans = 'Inter';
  static const String mono = 'JetBrains Mono';
}

/// Primitive font size tokens.
abstract class BTechFontSize {
  static const double xs = 12;
  static const double sm = 14;
  static const double base = 16;
  static const double lg = 18;
  static const double xl = 20;
  static const double s2xl = 24;
  static const double s3xl = 30;
  static const double s4xl = 36;
}

/// Primitive font weight tokens.
abstract class BTechFontWeight {
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight semibold = FontWeight.w600;
  static const FontWeight bold = FontWeight.w700;
}

/// Primitive line height tokens (ratio, not pixels).
abstract class BTechLineHeight {
  static const double tight = 1.25;
  static const double normal = 1.5;
  static const double relaxed = 1.75;
}

/// Root static font namespace — always uses the default sans font family.
/// For tenant-aware fonts in widgets, prefer [context.btechFont].
abstract class BTechFont {
  static final BTechFontHeading    heading    = BTechFontHeading();
  static final BTechFontSubHeading subheading = BTechFontSubHeading();
  static final BTechFontBody       body       = BTechFontBody();
}

