// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/core/font-registry.json.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Font source registry — generated from tokens/core/font-registry.json.
///
/// Tells each platform how to load a font family:
///   google-fonts → use GoogleFonts.getFont() (downloaded on demand)
///   system       → use TextStyle(fontFamily:) (OS resolves natively)
///   asset        → use TextStyle(fontFamily:) (Flutter asset pipeline)
///
/// ```dart
/// import 'package:google_fonts/google_fonts.dart';
///
/// TextStyle _build(String family) =>
///   BTechFontRegistry.isGoogleFont(family)
///       ? GoogleFonts.getFont(family, fontSize: 16)
///       : TextStyle(fontFamily: family, fontSize: 16);
/// ```
abstract class BTechFontRegistry {

  /// Font families available via the google_fonts Flutter package.
  static const Set<String> googleFonts = {
    'Inter',
    'JetBrains Mono',
    'Roboto',
    'Poppins',
    'Nunito',
    'Noto Sans',
  };

  /// Font families pre-installed on the OS — no network fetch required.
  static const Set<String> systemFonts = {
    'Google Sans',
  };

  /// CSS-style fallback stacks for each registered family.
  static const Map<String, String> fallbacks = {
    'Inter': 'system-ui, -apple-system, sans-serif',
    'JetBrains Mono': 'Fira Code, Courier New, monospace',
    'Roboto': 'Arial, sans-serif',
    'Google Sans': 'Roboto, sans-serif',
    'Poppins': 'sans-serif',
    'Nunito': 'sans-serif',
    'Noto Sans': 'sans-serif',
  };

  /// Returns true if [family] can be loaded via the google_fonts package.
  static bool isGoogleFont(String family) => googleFonts.contains(family);

  /// Returns true if [family] is pre-installed on the OS.
  static bool isSystemFont(String family) => systemFonts.contains(family);

  /// Returns the CSS fallback stack for [family], or 'sans-serif' if unknown.
  static String fallbackFor(String family) => fallbacks[family] ?? 'sans-serif';
}

