// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Green color swatch — BTechColor.shades.green[500]
final MaterialColor btechShadesGreen = MaterialColor(
  0xFF08A94C,
  <int, Color>{
      50: Color(0xFFF0F8F4),
      100: Color(0xFFE2F3E9),
      200: Color(0xFFC5EAD5),
      300: Color(0xFF94E2B5),
      400: Color(0xFF41E084),
      500: Color(0xFF08A94C),
      600: Color(0xFF0A853E),
      700: Color(0xFF0A632F),
      800: Color(0xFF094623),
      900: Color(0xFF072D17),
  },
);

/// Lightblue color swatch — BTechColor.shades.lightblue[500]
final MaterialColor btechShadesLightblue = MaterialColor(
  0xFF30AEE1,
  <int, Color>{
      50: Color(0xFFF2F6F8),
      100: Color(0xFFE9F1F4),
      200: Color(0xFFD6E6ED),
      300: Color(0xFFB6D7E4),
      400: Color(0xFF80C3DE),
      500: Color(0xFF30AEE1),
      600: Color(0xFF1F8CB8),
      700: Color(0xFF1A6583),
      800: Color(0xFF134357),
      900: Color(0xFF0B2530),
  },
);

/// Orange color swatch — BTechColor.shades.orange[500]
final MaterialColor btechShadesOrange = MaterialColor(
  0xFFF8981D,
  <int, Color>{
      50: Color(0xFFF9F6F1),
      100: Color(0xFFF6EFE8),
      200: Color(0xFFF0E3D3),
      300: Color(0xFFEBD2B1),
      400: Color(0xFFEBB876),
      500: Color(0xFFF8981D),
      600: Color(0xFFCE790C),
      700: Color(0xFF93580C),
      800: Color(0xFF603B0A),
      900: Color(0xFF352107),
  },
);

/// Blue color swatch — BTechColor.shades.blue[500]
final MaterialColor btechShadesBlue = MaterialColor(
  0xFF145BC3,
  <int, Color>{
      50: Color(0xFFE7EFF9),
      100: Color(0xFFD0DEF3),
      200: Color(0xFFA1BDE7),
      300: Color(0xFF729DDB),
      400: Color(0xFF437CCF),
      500: Color(0xFF145BC3),
      600: Color(0xFF10499C),
      700: Color(0xFF0C3775),
      800: Color(0xFF08244E),
      900: Color(0xFF041227),
  },
);

/// Purple color swatch — BTechColor.shades.purple[500]
final MaterialColor btechShadesPurple = MaterialColor(
  0xFF8A59C2,
  <int, Color>{
      50: Color(0xFFF3EEF9),
      100: Color(0xFFE8DEF3),
      200: Color(0xFFD0BDE7),
      300: Color(0xFFB99BDA),
      400: Color(0xFFA17ACE),
      500: Color(0xFF8A59C2),
      600: Color(0xFF6E479B),
      700: Color(0xFF533574),
      800: Color(0xFF37244E),
      900: Color(0xFF1C1227),
  },
);

/// Teal color swatch — BTechColor.shades.teal[500]
final MaterialColor btechShadesTeal = MaterialColor(
  0xFF0D9488,
  <int, Color>{
      50: Color(0xFFF0F8F7),
      100: Color(0xFFE2F2F0),
      200: Color(0xFFC4E8E5),
      300: Color(0xFF93DDD7),
      400: Color(0xFF3ED8CA),
      500: Color(0xFF0D9488),
      600: Color(0xFF0D766C),
      700: Color(0xFF0C5852),
      800: Color(0xFF0A403B),
      900: Color(0xFF082A27),
  },
);

/// Indigo color swatch — BTechColor.shades.indigo[500]
final MaterialColor btechShadesIndigo = MaterialColor(
  0xFF6366F1,
  <int, Color>{
      50: Color(0xFFF3F3F9),
      100: Color(0xFFECECF6),
      200: Color(0xFFDEDEF2),
      300: Color(0xFFC7C7ED),
      400: Color(0xFF9FA0EB),
      500: Color(0xFF6366F1),
      600: Color(0xFF2328E6),
      700: Color(0xFF181BA7),
      800: Color(0xFF12146B),
      900: Color(0xFF0A0B36),
  },
);

/// Rose color swatch — BTechColor.shades.rose[500]
final MaterialColor btechShadesRose = MaterialColor(
  0xFFE11D48,
  <int, Color>{
      50: Color(0xFFF8F2F3),
      100: Color(0xFFF4E8EA),
      200: Color(0xFFECD3D8),
      300: Color(0xFFE3B0BB),
      400: Color(0xFFDE758C),
      500: Color(0xFFE11D48),
      600: Color(0xFFAE1B3B),
      700: Color(0xFF7D162D),
      800: Color(0xFF531120),
      900: Color(0xFF2F0B13),
  },
);

/// Neutral color swatch — BTechColor.shades.neutral[500]
final MaterialColor btechShadesNeutral = MaterialColor(
  0xFF64748B,
  <int, Color>{
      50: Color(0xFFF4F5F6),
      100: Color(0xFFECEDEE),
      200: Color(0xFFDBDDE1),
      300: Color(0xFFC1C6CD),
      400: Color(0xFF98A2B0),
      500: Color(0xFF64748B),
      600: Color(0xFF505C6D),
      700: Color(0xFF3C4450),
      800: Color(0xFF292F37),
      900: Color(0xFF181C20),
      1000: Color(0xFF000000),
  },
);

/// Red color swatch — BTechColor.shades.red[500]
final MaterialColor btechShadesRed = MaterialColor(
  0xFFEF4444,
  <int, Color>{
      50: Color(0xFFF9F2F2),
      100: Color(0xFFF6EAEA),
      200: Color(0xFFF0D9D9),
      300: Color(0xFFEBBDBD),
      400: Color(0xFFE88D8D),
      500: Color(0xFFEF4444),
      600: Color(0xFFD81818),
      700: Color(0xFF991515),
      800: Color(0xFF631010),
      900: Color(0xFF340A0A),
  },
);

/// Amber color swatch — BTechColor.shades.amber[500]
final MaterialColor btechShadesAmber = MaterialColor(
  0xFFF59E0B,
  <int, Color>{
      50: Color(0xFFF9F6F1),
      100: Color(0xFFF5F0E7),
      200: Color(0xFFEFE3D0),
      300: Color(0xFFE9D2AB),
      400: Color(0xFFE8BA6C),
      500: Color(0xFFF59E0B),
      600: Color(0xFFBD7C0C),
      700: Color(0xFF885A0D),
      800: Color(0xFF5A3D0B),
      900: Color(0xFF332307),
  },
);

/// Sky color swatch — BTechColor.shades.sky[500]
final MaterialColor btechShadesSky = MaterialColor(
  0xFF0EA5E9,
  <int, Color>{
      50: Color(0xFFF1F6F9),
      100: Color(0xFFE7F0F4),
      200: Color(0xFFD0E4ED),
      300: Color(0xFFAAD4E7),
      400: Color(0xFF69BEE4),
      500: Color(0xFF0EA5E9),
      600: Color(0xFF0F81B4),
      700: Color(0xFF0F5E81),
      800: Color(0xFF0C3F57),
      900: Color(0xFF082431),
  },
);

/// Primitive color palette as MaterialColor swatches.
/// Access: BTechColor.shades.blue        → primary 500
///         BTechColor.shades.blue[400]   → shade 400
///         BTechColor.shades.green.shade700
class BTechShadesColor {
  const BTechShadesColor();
  MaterialColor get green => btechShadesGreen;
  MaterialColor get lightblue => btechShadesLightblue;
  MaterialColor get orange => btechShadesOrange;
  MaterialColor get blue => btechShadesBlue;
  MaterialColor get purple => btechShadesPurple;
  MaterialColor get teal => btechShadesTeal;
  MaterialColor get indigo => btechShadesIndigo;
  MaterialColor get rose => btechShadesRose;
  MaterialColor get neutral => btechShadesNeutral;
  MaterialColor get red => btechShadesRed;
  MaterialColor get amber => btechShadesAmber;
  MaterialColor get sky => btechShadesSky;
}

