// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Source: packages/tokens/sources/tenants/bspace/overrides.json
// Run `pnpm generate --tenant bspace` to regenerate.
//
// ignore_for_file: lines_longer_than_80_chars

library btech_tokens_bspace;

import 'package:flutter/material.dart';
import 'package:btech_tokens/btech_tokens.dart' as base;

/// Design tokens for the bspace tenant.
///
/// Extends [base.BtechToken] and overrides only the brand-specific values.
/// All non-overridden tokens are inherited from the base class.
///
/// Usage:
///   final token = BtechToken();
///   token.backgroundPrimary   // #0066CC
class BtechToken extends base.BtechToken {
  const BtechToken();

  @override
  Color get backgroundPrimary => const Color(0xFF0066CC);

  @override
  Color get backgroundPrimaryHover => const Color(0xFF004EA3);

  @override
  Color get strokePrimary => const Color(0xFF0066CC);

  @override
  Color get textPrimary => const Color(0xFFFFFFFF);

  @override
  String get fontFamilySans => 'Inter';

  @override
  double get radiusInteractive => 6;

  @override
  double get radiusCard => 8;

}
