// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechBackgroundColor {
  readonly surface = '#f9fafb' as const;
  readonly surfaceSubtle = '#f3f4f6' as const;
  readonly surfaceRaised = '#ffffff' as const;
  readonly primary = '#15803d' as const;
  readonly primaryHover = '#166534' as const;
  readonly primaryPressed = '#14532d' as const;
  readonly primaryDisable = '#e5e7eb' as const;
  readonly primarySubtle = '#f0fdf4' as const;
  readonly primaryBolder = '#166534' as const;
  readonly secondary = '#f0fdf4' as const;
  readonly secondaryHover = '#dcfce7' as const;
  readonly secondaryPressed = '#bbf7d0' as const;
  readonly secondaryDisable = '#f3f4f6' as const;
  readonly secondarySubtle = '#f9fafb' as const;
  readonly secondaryBolder = '#bbf7d0' as const;
  readonly danger = '#dc2626' as const;
  readonly dangerHover = '#b91c1c' as const;
  readonly dangerPressed = '#991b1b' as const;
  readonly dangerDisable = '#e5e7eb' as const;
  readonly dangerSubtle = '#fef2f2' as const;
  readonly dangerBolder = '#991b1b' as const;
  readonly success = '#22c55e' as const;
  readonly successHover = '#16a34a' as const;
  readonly successPressed = '#15803d' as const;
  readonly successDisable = '#e5e7eb' as const;
  readonly successSubtle = '#f0fdf4' as const;
  readonly successBolder = '#15803d' as const;
  readonly warning = '#fb923c' as const;
  readonly warningHover = '#f97316' as const;
  readonly warningPressed = '#ea580c' as const;
  readonly warningDisable = '#e5e7eb' as const;
  readonly warningSubtle = '#fff7ed' as const;
  readonly warningBolder = '#ea580c' as const;
  readonly info = '#2563eb' as const;
  readonly infoHover = '#1d4ed8' as const;
  readonly infoPressed = '#1e40af' as const;
  readonly infoDisable = '#e5e7eb' as const;
  readonly infoSubtle = '#eff6ff' as const;
  readonly infoBolder = '#1e40af' as const;
  readonly neutral = '#f3f4f6' as const;
  readonly neutralSubtle = '#f9fafb' as const;
  readonly neutralBolder = '#e5e7eb' as const;
}

