// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechBgColor {
  readonly primary = '#ffffff' as const;
  readonly secondary = '#ecedee' as const;
  readonly tertiary = '#64748b' as const;
  readonly inverse = '#181c20' as const;
  readonly subtle = '#f4f5f6' as const;
  readonly subtler = '#dbdde1' as const;
  readonly subtlest = '#C1C6CD' as const;
  readonly overlay = 'rgba(24,28,32,0.8)' as const;
}

