// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechBorderColor {
  readonly primary = '#dbdde1' as const;
  readonly secondary = '#98a2b0' as const;
  readonly tertiary = '#c1c6cd' as const;
  readonly inverse = '#292f37' as const;
  readonly disabled = '#c1c6cd' as const;
}

