// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechExtColor {
  readonly successSubtler = '#e2f3e9' as const;
  readonly successSubtle = '#c5ead5' as const;
  readonly success = '#08a94c' as const;
  readonly successBold = '#0a853e' as const;
  readonly infoSubtler = '#e7f0f4' as const;
  readonly infoSubtle = '#d0e4ed' as const;
  readonly info = '#0ea5e9' as const;
  readonly infoBold = '#0f81b4' as const;
  readonly warningSubtler = '#f5f0e7' as const;
  readonly warningSubtle = '#efe3d0' as const;
  readonly warning = '#f59e0b' as const;
  readonly warningBold = '#bd7c0c' as const;
  readonly errorSubtler = '#f6eaea' as const;
  readonly errorSubtle = '#f0d9d9' as const;
  readonly error = '#ef4444' as const;
  readonly errorBold = '#d81818' as const;
}

