// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechTextColor {
  readonly neutral = '#181c20' as const;
  readonly neutralSubtle = '#64748b' as const;
  readonly neutralTertiary = '#98a2b0' as const;
  readonly neutralDisabled = '#c1c6cd' as const;
  readonly neutralInverse = '#ffffff' as const;
  readonly neutralLink = '#0d766c' as const;
  readonly danger = '#991515' as const;
  readonly dangerBolder = '#631010' as const;
  readonly success = '#0a632f' as const;
  readonly successBolder = '#094623' as const;
  readonly warning = '#885a0d' as const;
  readonly warningBolder = '#5a3d0b' as const;
  readonly info = '#0f5e81' as const;
  readonly infoBolder = '#0c3f57' as const;
  readonly secondary = '#6e479b' as const;
  readonly secondaryBolder = '#37244e' as const;
}

