// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechTextColor {
  readonly neutral = '#111827' as const;
  readonly neutralSubtle = '#6b7280' as const;
  readonly neutralDisabled = '#d1d5db' as const;
  readonly neutralInverse = '#f9fafb' as const;
  readonly danger = '#dc2626' as const;
  readonly dangerBolder = '#991b1b' as const;
  readonly success = '#16a34a' as const;
  readonly successBolder = '#166534' as const;
  readonly warning = '#ea580c' as const;
  readonly warningBolder = '#9a3412' as const;
  readonly info = '#2563eb' as const;
  readonly infoBolder = '#1e40af' as const;
  readonly secondary = '#9333ea' as const;
  readonly secondaryBolder = '#6b21a8' as const;
}

