// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// @btech/tokens-bspace — re-exports base @btech/tokens with tenant activate helper.
// Import this package's styles.css INSTEAD OF @btech/tokens/styles.css.

export * from '@btech/tokens';
import { activateTenant } from '@btech/tokens';

/**
 * Activates the bspace tenant. Only pass `mode` — tenant is pre-configured.
 * @example
 * import '@btech/tokens-bspace/styles.css';
 * activate({ mode: 'dark' });
 */
export function activate(opts?: { mode?: 'light' | 'dark'; root?: HTMLElement }) {
  return activateTenant({ tenant: 'bspace', mode: opts?.mode ?? 'light', root: opts?.root });
}
