// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export const BTechFontFamily = {
  sans: 'Inter',
  mono: 'JetBrains Mono',
} as const;

export const BTechFontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  s2xl: 24,
  s3xl: 30,
  s4xl: 36,
} as const;

export const BTechFontWeight = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
} as const;

export const BTechLineHeight = {
  tight: 1.25,
  normal: 1.5,
  relaxed: 1.75,
} as const;

export const BTechFont = {
  heading: {
    fontFamily: 'Inter',
    fontWeight: 700,
    lineHeight: 1.25,
  },
  body: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 1.5,
  },
} as const;

