// ── Framework-agnostic BTech design tokens ───────────────────────────────────
// BTechColor, BTechSpacing, BTechRadius, BTechFont are generated by pnpm generate.
// React and Vue packages re-export from here — no duplication.
// ─────────────────────────────────────────────────────────────────────────────

// Generated token namespaces
export * from './color/index';
export * from './spacing/index';
export * from './radius/index';
export * from './typography/index';

// ── Type-safe token() helper — analogous to Atlassian's @atlaskit/tokens ─────
export { token, cssVar, tokenCalc } from './token';
export type { TokenPath } from './token';

// ── Vanilla JS mode API ───────────────────────────────────────────────────────
// Tenant is activated by importing the tenant's CSS package statically:
//   import '@btech/tokens/styles.css';         // base (default) tenant
//   import '@btech/tokens-bspace/styles.css';  // bspace tenant
//
// Mode (light/dark) is controlled at runtime via setMode() or followSystemMode().

export type ColorMode = 'light' | 'dark';

/**
 * Sets the color mode (light or dark) on the root element.
 * CSS custom properties in styles.css switch via the [data-mode="dark"] block.
 *
 * @example
 * import { setMode } from '@btech/tokens';
 *
 * setMode('dark');                        // enable dark mode globally
 * setMode('light');                       // switch back to light
 * setMode('dark', document.getElementById('panel')); // scope to one element
 */
export function setMode(
  mode: ColorMode,
  root: HTMLElement = document.documentElement,
): void {
  root.dataset.mode = mode;
}

/**
 * Auto-syncs the color mode with the user's OS preference (prefers-color-scheme).
 * Calls setMode() immediately with the current system preference, then listens
 * for future changes.
 *
 * Returns a cleanup function — call it to remove the listener.
 *
 * @example
 * import { followSystemMode } from '@btech/tokens';
 *
 * const stop = followSystemMode();
 * // …later, in cleanup:
 * stop();
 */
export function followSystemMode(
  root: HTMLElement = document.documentElement,
): () => void {
  const mq = window.matchMedia('(prefers-color-scheme: dark)');
  const apply = (): void => setMode(mq.matches ? 'dark' : 'light', root);
  apply();
  mq.addEventListener('change', apply);
  return () => mq.removeEventListener('change', apply);
}

// Token exports (auto-generated)
export * from './stroke/index';

// Token exports (auto-generated)
export * from './shadow/index';
