// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

/**
 * All valid BTech design token paths.
 * Grammar: [category].[property].[role].[emphasis].[state]
 *
 * @example
 * 'color.bg.primary'                — primary background color
 * 'color.text.secondary'           — secondary text color
 * 'spacing.md'                      — medium spacing (12px)
 * 'radius.sm'                       — small border radius (8px)
 */
export type TokenPath =
  | 'button.danger.bg'
  | 'button.danger.bgHover'
  | 'button.danger.border'
  | 'button.danger.fg'
  | 'button.danger.radius'
  | 'button.primary.bg'
  | 'button.primary.bgHover'
  | 'button.primary.border'
  | 'button.primary.fg'
  | 'button.primary.radius'
  | 'button.secondary.bg'
  | 'button.secondary.bgHover'
  | 'button.secondary.border'
  | 'button.secondary.fg'
  | 'button.secondary.radius'
  | 'button.size.lg.fontSize'
  | 'button.size.lg.paddingX'
  | 'button.size.lg.paddingY'
  | 'button.size.md.fontSize'
  | 'button.size.md.paddingX'
  | 'button.size.md.paddingY'
  | 'button.size.sm.fontSize'
  | 'button.size.sm.paddingX'
  | 'button.size.sm.paddingY'
  | 'color.amber.100'
  | 'color.amber.200'
  | 'color.amber.300'
  | 'color.amber.400'
  | 'color.amber.50'
  | 'color.amber.500'
  | 'color.amber.600'
  | 'color.amber.700'
  | 'color.amber.800'
  | 'color.amber.900'
  | 'color.bg.inverse'
  | 'color.bg.overlay'
  | 'color.bg.primary'
  | 'color.bg.secondary'
  | 'color.bg.subtle'
  | 'color.bg.subtler'
  | 'color.bg.subtlest'
  | 'color.bg.tertiary'
  | 'color.blue.100'
  | 'color.blue.200'
  | 'color.blue.300'
  | 'color.blue.400'
  | 'color.blue.50'
  | 'color.blue.500'
  | 'color.blue.600'
  | 'color.blue.700'
  | 'color.blue.800'
  | 'color.blue.900'
  | 'color.border.disabled'
  | 'color.border.inverse'
  | 'color.border.primary'
  | 'color.border.secondary'
  | 'color.border.tertiary'
  | 'color.brand.primary'
  | 'color.brand.primary-bold'
  | 'color.brand.primary-subtle'
  | 'color.brand.secondary'
  | 'color.brand.secondary-bold'
  | 'color.brand.secondary-subtle'
  | 'color.ext.error'
  | 'color.ext.error-bold'
  | 'color.ext.error-subtle'
  | 'color.ext.error-subtler'
  | 'color.ext.info'
  | 'color.ext.info-bold'
  | 'color.ext.info-subtle'
  | 'color.ext.info-subtler'
  | 'color.ext.success'
  | 'color.ext.success-bold'
  | 'color.ext.success-subtle'
  | 'color.ext.success-subtler'
  | 'color.ext.warning'
  | 'color.ext.warning-bold'
  | 'color.ext.warning-subtle'
  | 'color.ext.warning-subtler'
  | 'color.green.100'
  | 'color.green.200'
  | 'color.green.300'
  | 'color.green.400'
  | 'color.green.50'
  | 'color.green.500'
  | 'color.green.600'
  | 'color.green.700'
  | 'color.green.800'
  | 'color.green.900'
  | 'color.icon.disabled'
  | 'color.icon.error'
  | 'color.icon.info'
  | 'color.icon.inverse'
  | 'color.icon.link'
  | 'color.icon.primary'
  | 'color.icon.secondary'
  | 'color.icon.success'
  | 'color.icon.tertiary'
  | 'color.icon.warning'
  | 'color.indigo.100'
  | 'color.indigo.200'
  | 'color.indigo.300'
  | 'color.indigo.400'
  | 'color.indigo.50'
  | 'color.indigo.500'
  | 'color.indigo.600'
  | 'color.indigo.700'
  | 'color.indigo.800'
  | 'color.indigo.900'
  | 'color.lightblue.100'
  | 'color.lightblue.200'
  | 'color.lightblue.300'
  | 'color.lightblue.400'
  | 'color.lightblue.50'
  | 'color.lightblue.500'
  | 'color.lightblue.600'
  | 'color.lightblue.700'
  | 'color.lightblue.800'
  | 'color.lightblue.900'
  | 'color.neutral.0'
  | 'color.neutral.100'
  | 'color.neutral.1000'
  | 'color.neutral.200'
  | 'color.neutral.300'
  | 'color.neutral.400'
  | 'color.neutral.50'
  | 'color.neutral.500'
  | 'color.neutral.600'
  | 'color.neutral.700'
  | 'color.neutral.800'
  | 'color.neutral.900'
  | 'color.orange.100'
  | 'color.orange.200'
  | 'color.orange.300'
  | 'color.orange.400'
  | 'color.orange.50'
  | 'color.orange.500'
  | 'color.orange.600'
  | 'color.orange.700'
  | 'color.orange.800'
  | 'color.orange.900'
  | 'color.purple.100'
  | 'color.purple.200'
  | 'color.purple.300'
  | 'color.purple.400'
  | 'color.purple.50'
  | 'color.purple.500'
  | 'color.purple.600'
  | 'color.purple.700'
  | 'color.purple.800'
  | 'color.purple.900'
  | 'color.red.100'
  | 'color.red.200'
  | 'color.red.300'
  | 'color.red.400'
  | 'color.red.50'
  | 'color.red.500'
  | 'color.red.600'
  | 'color.red.700'
  | 'color.red.800'
  | 'color.red.900'
  | 'color.rose.100'
  | 'color.rose.200'
  | 'color.rose.300'
  | 'color.rose.400'
  | 'color.rose.50'
  | 'color.rose.500'
  | 'color.rose.600'
  | 'color.rose.700'
  | 'color.rose.800'
  | 'color.rose.900'
  | 'color.sky.100'
  | 'color.sky.200'
  | 'color.sky.300'
  | 'color.sky.400'
  | 'color.sky.50'
  | 'color.sky.500'
  | 'color.sky.600'
  | 'color.sky.700'
  | 'color.sky.800'
  | 'color.sky.900'
  | 'color.teal.100'
  | 'color.teal.200'
  | 'color.teal.300'
  | 'color.teal.400'
  | 'color.teal.50'
  | 'color.teal.500'
  | 'color.teal.600'
  | 'color.teal.700'
  | 'color.teal.800'
  | 'color.teal.900'
  | 'color.text.disabled'
  | 'color.text.error'
  | 'color.text.info'
  | 'color.text.inverse'
  | 'color.text.link'
  | 'color.text.primary'
  | 'color.text.secondary'
  | 'color.text.success'
  | 'color.text.tertiary'
  | 'color.text.warning'
  | 'radius.2xl'
  | 'radius.2xs'
  | 'radius.lg'
  | 'radius.md'
  | 'radius.rd'
  | 'radius.sm'
  | 'radius.xl'
  | 'radius.xs'
  | 'shadow.button.pressed'
  | 'shadow.elevation.lg'
  | 'shadow.elevation.md'
  | 'shadow.elevation.sm'
  | 'shadow.elevation.xl'
  | 'shadow.elevation.xs'
  | 'shadow.table.left'
  | 'shadow.table.right'
  | 'spacing.2xl'
  | 'spacing.2xs'
  | 'spacing.3xl'
  | 'spacing.lg'
  | 'spacing.md'
  | 'spacing.sm'
  | 'spacing.xl'
  | 'spacing.xs'
  | 'stroke.lg'
  | 'stroke.md'
  | 'stroke.sm'
  | 'stroke.xl'
  | 'stroke.xs'
  | 'typography.body.fontFamily'
  | 'typography.body.fontSize'
  | 'typography.body.fontWeight'
  | 'typography.body.large'
  | 'typography.body.largeB'
  | 'typography.body.lineHeight'
  | 'typography.body.micro'
  | 'typography.body.microB'
  | 'typography.body.regular'
  | 'typography.body.regularB'
  | 'typography.body.small'
  | 'typography.body.smallB'
  | 'typography.body.xtrasmall'
  | 'typography.body.xtrasmallB'
  | 'typography.code.fontFamily'
  | 'typography.code.fontSize'
  | 'typography.fontFamily.mono'
  | 'typography.fontFamily.sans'
  | 'typography.fontSize.2xl'
  | 'typography.fontSize.2xs'
  | 'typography.fontSize.3xl'
  | 'typography.fontSize.3xs'
  | 'typography.fontSize.4xl'
  | 'typography.fontSize.5xl'
  | 'typography.fontSize.lg'
  | 'typography.fontSize.md'
  | 'typography.fontSize.sm'
  | 'typography.fontSize.xl'
  | 'typography.fontSize.xs'
  | 'typography.fontWeight.bold'
  | 'typography.fontWeight.medium'
  | 'typography.fontWeight.regular'
  | 'typography.fontWeight.semibold'
  | 'typography.heading.display'
  | 'typography.heading.fontFamily'
  | 'typography.heading.fontWeight'
  | 'typography.heading.h1'
  | 'typography.heading.h2'
  | 'typography.heading.h3'
  | 'typography.heading.h4'
  | 'typography.heading.lineHeight'
  | 'typography.label.fontFamily'
  | 'typography.label.fontSize'
  | 'typography.label.fontWeight'
  | 'typography.label.lineHeight'
  | 'typography.letterSpacing.snug'
  | 'typography.letterSpacing.tight'
  | 'typography.letterSpacing.tighter'
  | 'typography.letterSpacing.wide'
  | 'typography.letterSpacing.wider'
  | 'typography.lineHeight.2xl'
  | 'typography.lineHeight.2xs'
  | 'typography.lineHeight.3xl'
  | 'typography.lineHeight.4xl'
  | 'typography.lineHeight.lg'
  | 'typography.lineHeight.md'
  | 'typography.lineHeight.sm'
  | 'typography.lineHeight.xl'
  | 'typography.lineHeight.xs'
  | 'typography.subheading.h5'
  | 'typography.subheading.h6'
  | 'typography.subheading.h7'
  | 'typography.subheading.h8'
  | 'typography.typeScale.body.large.fontSize'
  | 'typography.typeScale.body.large.fontWeight'
  | 'typography.typeScale.body.large.lineHeightPx'
  | 'typography.typeScale.body.largeB.fontSize'
  | 'typography.typeScale.body.largeB.fontWeight'
  | 'typography.typeScale.body.largeB.lineHeightPx'
  | 'typography.typeScale.body.micro.fontSize'
  | 'typography.typeScale.body.micro.fontWeight'
  | 'typography.typeScale.body.micro.lineHeightPx'
  | 'typography.typeScale.body.microB.fontSize'
  | 'typography.typeScale.body.microB.fontWeight'
  | 'typography.typeScale.body.microB.lineHeightPx'
  | 'typography.typeScale.body.regular.fontSize'
  | 'typography.typeScale.body.regular.fontWeight'
  | 'typography.typeScale.body.regular.lineHeightPx'
  | 'typography.typeScale.body.regularB.fontSize'
  | 'typography.typeScale.body.regularB.fontWeight'
  | 'typography.typeScale.body.regularB.lineHeightPx'
  | 'typography.typeScale.body.small.fontSize'
  | 'typography.typeScale.body.small.fontWeight'
  | 'typography.typeScale.body.small.lineHeightPx'
  | 'typography.typeScale.body.smallB.fontSize'
  | 'typography.typeScale.body.smallB.fontWeight'
  | 'typography.typeScale.body.smallB.lineHeightPx'
  | 'typography.typeScale.body.xtrasmall.fontSize'
  | 'typography.typeScale.body.xtrasmall.fontWeight'
  | 'typography.typeScale.body.xtrasmall.lineHeightPx'
  | 'typography.typeScale.body.xtrasmallB.fontSize'
  | 'typography.typeScale.body.xtrasmallB.fontWeight'
  | 'typography.typeScale.body.xtrasmallB.lineHeightPx'
  | 'typography.typeScale.heading.display.fontSize'
  | 'typography.typeScale.heading.display.fontWeight'
  | 'typography.typeScale.heading.display.lineHeightPx'
  | 'typography.typeScale.heading.h1.fontSize'
  | 'typography.typeScale.heading.h1.fontWeight'
  | 'typography.typeScale.heading.h1.lineHeightPx'
  | 'typography.typeScale.heading.h2.fontSize'
  | 'typography.typeScale.heading.h2.fontWeight'
  | 'typography.typeScale.heading.h2.lineHeightPx'
  | 'typography.typeScale.heading.h3.fontSize'
  | 'typography.typeScale.heading.h3.fontWeight'
  | 'typography.typeScale.heading.h3.lineHeightPx'
  | 'typography.typeScale.heading.h4.fontSize'
  | 'typography.typeScale.heading.h4.fontWeight'
  | 'typography.typeScale.heading.h4.lineHeightPx'
  | 'typography.typeScale.subheading.h5.fontSize'
  | 'typography.typeScale.subheading.h5.fontWeight'
  | 'typography.typeScale.subheading.h5.lineHeightPx'
  | 'typography.typeScale.subheading.h6.fontSize'
  | 'typography.typeScale.subheading.h6.fontWeight'
  | 'typography.typeScale.subheading.h6.lineHeightPx'
  | 'typography.typeScale.subheading.h7.fontSize'
  | 'typography.typeScale.subheading.h7.fontWeight'
  | 'typography.typeScale.subheading.h7.lineHeightPx'
  | 'typography.typeScale.subheading.h8.fontSize'
  | 'typography.typeScale.subheading.h8.fontWeight'
  | 'typography.typeScale.subheading.h8.lineHeightPx'

// =============================================================================
// CSS variable naming (no vendor prefix)
// =============================================================================
// styles.css defines every token as a CSS custom property:
//   :root {
//     --bg-primary: #...;                  (color — category dropped)
//     --space-md: 16px;                    (spacing → space)
//     --typography-font-family-sans: ...;  (typography — category kept)
//     --border-neutral: #...;              (color.stroke → border)
//     --duration-fast: 100ms;              (motion — category dropped)
//     --z-modal: 400;                      (zIndex → z)
//   }
//
// token() returns the identical var() — same as writing it by hand in CSS.
// Dark mode via [data-mode="dark"] works automatically for both.
// =============================================================================

// Internal: same logic as pathToCssVarStem() in config/generators/utils.ts
const PRIMITIVE_COLORS = new Set(['blue','red','green','orange','neutral','yellow','pink','purple','teal','slate']);
function _pathToVarName(dotPath: string): string {
  const [cat, ...rest] = dotPath.split('.');
  let stem: string;
  switch (cat) {
    case 'color': {
      const sub = rest[0];
      if (PRIMITIVE_COLORS.has(sub)) { stem = ['color', ...rest].join('-'); break; }
      if (sub === 'stroke')          { stem = ['border', ...rest.slice(1)].join('-'); break; }
      stem = rest.join('-'); break;
    }
    case 'spacing': stem = ['space', ...rest].join('-'); break;
    case 'typography': stem = [cat, ...rest].join('-'); break;
    case 'zIndex': stem = ['z', ...rest].join('-'); break;
    case 'motion': stem = rest.join('-'); break;
    default: stem = [cat, ...rest].join('-');
  }
  return stem.replace(/([A-Z])/g, m => `-${m.toLowerCase()}`);
}

/**
 * Returns the CSS custom property reference for any design token.
 * Atlassian-aligned: category is dropped from the var name.
 *
 * ── Color ────────────────────────────────────────────────────────────────────
 * token('color.bg.primary')           → var(--bg-primary)
 * token('color.text.primary')         → var(--text-primary)
 * token('color.icon.success')         → var(--icon-success)
 * token('color.border.primary')       → var(--border-primary)
 * token('color.brand.primary')        → var(--brand-primary)
 * token('color.ext.success-subtler')  → var(--ext-success-subtler)
 * token('color.blue.500')             → var(--color-blue-500)
 *
 * ── Spacing ─────────────────────────────────────────────────────────────────
 * token('spacing.xs')   → var(--space-xs)
 * token('spacing.md')   → var(--space-md)
 *
 * ── Radius / Shadow ─────────────────────────────────────────────────────────
 * token('radius.sm')              → var(--radius-sm)
 * token('shadow.elevation.md')    → var(--shadow-elevation-md)
 *
 * ── Typography ─────────────────────────────────────────────────────────────
 * token('typography.fontFamily.sans')     → var(--typography-font-family-sans)
 * token('typography.fontSize.sm')         → var(--typography-font-size-sm)
 * token('typography.heading.h1')          → var(--typography-heading-h1)
 * token('typography.body.regular')        → var(--typography-body-regular)
 *
 * ── Motion / Z-Index ───────────────────────────────────────────────────────
 * token('motion.duration.fast')  → var(--duration-fast)
 * token('motion.easing.ease')    → var(--easing-ease)
 * token('zIndex.modal')          → var(--z-modal)
 *
 * ── With fallback ───────────────────────────────────────────────────────────
 * token('color.bg.primary', '#fff') → var(--bg-primary, #fff)
 */
export function token(path: TokenPath, fallback?: string): string {
  const varName = `--${_pathToVarName(path)}`;
  return fallback ? `var(${varName}, ${fallback})` : `var(${varName})`;
}

/**
 * Raw CSS variable name — no var() wrapper.
 * Use for setProperty(), CSS-in-JS that wraps var() itself, or calc().
 *
 * cssVar('color.bg.primary')              → '--bg-primary'
 * cssVar('typography.fontFamily.sans')    → '--typography-font-family-sans'
 * element.style.setProperty(cssVar('color.bg.primary'), '#0057b7');
 */
export function cssVar(path: TokenPath): string {
  return `--${_pathToVarName(path)}`;
}

/**
 * Wraps a token in calc().
 *
 * tokenCalc('spacing.md', '* 2')    → 'calc(var(--space-md) * 2)'
 * tokenCalc('spacing.sm', '+ 4px')  → 'calc(var(--space-sm) + 4px)'
 */
export function tokenCalc(path: TokenPath, expression: string): string {
  return `calc(${token(path)} ${expression})`;
}
