// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'font.theme.dart';

/// Heading text styles (display, h1–h4).
/// Font family is tenant-aware — driven by BTechTypography.fontFamily.
///
/// ```dart
/// Text('Hero',  style: BTechTypography.heading.display)
/// Text('Title', style: BTechTypography.heading.h1)
/// ```
class BTechTypographyHeading extends TextStyle {
  BTechTypographyHeading()
      : super(
          fontFamily: BTechTypography.fontFamily,
          fontSize: 40,
          fontWeight: FontWeight.w700,
          height: 48 / 40,
        );

  /// DISPLAY — 40px · w700 · lineHeight: 48/40 = 1.200
  final TextStyle display = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 40, fontWeight: FontWeight.w700, height: 48 / 40);

  /// H1 — 32px · w700 · lineHeight: 40/32 = 1.250
  final TextStyle h1 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 32, fontWeight: FontWeight.w700, height: 40 / 32);

  /// H2 — 28px · w700 · lineHeight: 36/28 = 1.286
  final TextStyle h2 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 28, fontWeight: FontWeight.w700, height: 36 / 28);

  /// H3 — 24px · w600 · lineHeight: 32/24 = 1.333
  final TextStyle h3 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 24, fontWeight: FontWeight.w600, height: 32 / 24);

  /// H4 — 20px · w600 · lineHeight: 28/20 = 1.400
  final TextStyle h4 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 20, fontWeight: FontWeight.w600, height: 28 / 20);

}

