// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import 'font.theme.dart';

/// Subheading text styles (h5–h8).
/// Font family is tenant-aware — driven by BTechTypography.fontFamily.
///
/// ```dart
/// Text('Section', style: BTechTypography.subheading.h5)
/// Text('Label',   style: BTechTypography.subheading.h6)
/// ```
class BTechTypographySubHeading extends TextStyle {
  BTechTypographySubHeading()
      : super(
          fontFamily: BTechTypography.fontFamily,
          fontSize: 18,
          fontWeight: FontWeight.w600,
          height: 24 / 18,
        );

  /// H5 — 18px · w600 · lineHeight: 24/18 = 1.333
  final TextStyle h5 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 18, fontWeight: FontWeight.w600, height: 24 / 18);

  /// H6 — 16px · w600 · lineHeight: 20/16 = 1.250
  final TextStyle h6 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 16, fontWeight: FontWeight.w600, height: 20 / 16);

  /// H7 — 14px · w600 · lineHeight: 16/14 = 1.143
  final TextStyle h7 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 14, fontWeight: FontWeight.w600, height: 16 / 14);

  /// H8 — 12px · w600 · lineHeight: 16/12 = 1.333
  final TextStyle h8 = TextStyle(
      fontFamily: BTechTypography.fontFamily,
      fontSize: 12, fontWeight: FontWeight.w600, height: 16 / 12);

}

