import StyleDictionary from 'style-dictionary';
import type { Format, TransformedToken } from 'style-dictionary/types';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync } from 'fs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ---------------------------------------------------------------------------
// Custom format: Dart primitives + tenant tokens
// ---------------------------------------------------------------------------
const dartFormat: Format = {
  name: 'custom/dart',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;

    function dartColor(hex: string): string {
      // #RRGGBB → Color(0xFFRRGGBB)
      const clean = hex.replace('#', '');
      const padded = clean.length === 3
        ? clean.split('').map(c => c + c).join('')
        : clean;
      return `Color(0xFF${padded.toUpperCase()})`;
    }

    function dartDouble(val: string | number): string {
      const n = typeof val === 'string' ? parseFloat(val) : val;
      return Number.isInteger(n) ? `${n}` : `${n}`;
    }

    function group(type: string): TransformedToken[] {
      return tokens.filter(t => t.$type === type || t.type === type);
    }

    const colors  = group('color');
    const dims    = group('dimension');
    const weights = group('fontWeight');
    const families= group('fontFamily');

    // Helper: token path → Dart const name (camelCase)
    function constName(t: TransformedToken): string {
      return t.path.map((p, i) =>
        i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)
      ).join('').replace(/[^a-zA-Z0-9_]/g, '_');
    }

    // Split into primitive (base) vs semantic tokens by path depth / parent
    const isPrimitive = (t: TransformedToken) =>
      t.filePath.includes('/base/');

    const primColors   = colors.filter(isPrimitive);
    const primDims     = dims.filter(isPrimitive);
    const primWeights  = weights.filter(isPrimitive);
    const primFamilies = families.filter(isPrimitive);

    const semColors    = colors.filter(t => !isPrimitive(t));
    const semDims      = dims.filter(t => !isPrimitive(t));
    const semFamilies  = families.filter(t => !isPrimitive(t));

    const lines: string[] = [
      '// AUTO-GENERATED by @ramams06/design-tokens — do not edit manually.',
      '// Run `pnpm generate` to regenerate from tokens/.',
      '',
      '// ignore_for_file: lines_longer_than_80_chars',
      '',
      "import 'package:flutter/material.dart';",
      '',
      '/// Primitive color tokens (Tier 1) — never consume in components directly.',
      'abstract class DsPrimitiveColors {',
    ];

    for (const t of primColors) {
      const hex = String(t.value ?? t.$value);
      lines.push(`  static const ${constName(t)} = ${dartColor(hex)};`);
    }
    lines.push('}', '');

    lines.push('/// Primitive spacing / dimension tokens (Tier 1).');
    lines.push('abstract class DsPrimitiveDimensions {');
    for (const t of primDims) {
      const raw = String(t.value ?? t.$value).replace('px', '');
      lines.push(`  static const double ${constName(t)} = ${dartDouble(raw)};`);
    }
    lines.push('}', '');

    lines.push('/// Primitive font-weight tokens (Tier 1).');
    lines.push('abstract class DsPrimitiveFontWeights {');
    for (const t of primWeights) {
      const w = Number(t.value ?? t.$value);
      lines.push(`  static const FontWeight ${constName(t)} = FontWeight.w${w};`);
    }
    lines.push('}', '');

    lines.push('/// Primitive font-family tokens (Tier 1).');
    lines.push('abstract class DsPrimitiveFontFamilies {');
    for (const t of primFamilies) {
      const fam = String(t.value ?? t.$value).split(',')[0].trim().replace(/'/g, '');
      lines.push(`  static const String ${constName(t)} = '${fam}';`);
    }
    lines.push('}', '');

    lines.push('/// Semantic color tokens (Tier 2) — default tenant values.');
    lines.push('abstract class DsSemanticColors {');
    for (const t of semColors) {
      const hex = String(t.value ?? t.$value);
      lines.push(`  static const ${constName(t)} = ${dartColor(hex)};`);
    }
    lines.push('}', '');

    lines.push('/// Semantic radius tokens (Tier 2).');
    lines.push('abstract class DsSemanticRadius {');
    for (const t of semDims) {
      const raw = String(t.value ?? t.$value).replace('px', '');
      lines.push(`  static const double ${constName(t)} = ${dartDouble(raw)};`);
    }
    lines.push('}', '');

    if (semFamilies.length > 0) {
      lines.push('/// Semantic font-family tokens (Tier 2).');
      lines.push('abstract class DsSemanticFontFamilies {');
      for (const t of semFamilies) {
        const fam = String(t.value ?? t.$value).split(',')[0].trim().replace(/'/g, '');
        lines.push(`  static const String ${constName(t)} = '${fam}';`);
      }
      lines.push('}', '');
    }

    return lines.join('\n') + '\n';
  },
};

StyleDictionary.registerFormat(dartFormat);

// ---------------------------------------------------------------------------
// Ensure output dirs exist
// ---------------------------------------------------------------------------
const dartOutDir = `${ROOT}/packages/tokens-dart/lib/src/`;
mkdirSync(dartOutDir, { recursive: true });
mkdirSync(`${ROOT}/packages/tokens-web/dist/`, { recursive: true });
mkdirSync(`${ROOT}/packages/tokens-react/src/`, { recursive: true });
mkdirSync(`${ROOT}/packages/tokens-vue/src/`, { recursive: true });

// ---------------------------------------------------------------------------
// Style Dictionary instance
// ---------------------------------------------------------------------------
const sd = new StyleDictionary({
  source: [
    `${ROOT}/tokens/base/**/*.json`,
    `${ROOT}/tokens/semantic/**/*.json`,
    `${ROOT}/tokens/components/**/*.json`,
  ],

  platforms: {
    // CSS custom properties → tokens-web
    css: {
      transformGroup: 'css',
      prefix: 'ds',
      buildPath: `${ROOT}/packages/tokens-web/dist/`,
      files: [
        {
          destination: 'styles.css',
          format: 'css/variables',
          options: { outputReferences: true, selector: ':root' },
        },
      ],
    },

    // TypeScript objects → tokens-react
    'ts-react': {
      transformGroup: 'js',
      buildPath: `${ROOT}/packages/tokens-react/src/`,
      files: [
        {
          destination: 'generated.ts',
          format: 'javascript/es6',
          options: { outputReferences: false },
        },
      ],
    },

    // TypeScript objects → tokens-vue (same shape as React)
    'ts-vue': {
      transformGroup: 'js',
      buildPath: `${ROOT}/packages/tokens-vue/src/`,
      files: [
        {
          destination: 'generated.ts',
          format: 'javascript/es6',
          options: { outputReferences: false },
        },
      ],
    },

    // Dart classes → tokens-dart
    dart: {
      transformGroup: 'css', // resolves references before our format runs
      buildPath: dartOutDir,
      files: [
        {
          destination: 'generated.dart',
          format: 'custom/dart',
        },
      ],
    },
  },
});

(async () => {
  await sd.buildAllPlatforms();
  console.log('\n✅ Style Dictionary build complete.\n');
})();
