// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.
//
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Base design token values for all BTech tenants.
///
/// Tenant packages extend this class and override only the tokens
/// that differ from the defaults. All other tokens are inherited.
///
/// Usage in consuming app:
///   final token = BtechTokenBspace(); // from btech_tokens_bspace package
///   token.backgroundPrimary          // Color(0xFF0066CC)
///   token.radiusInteractive          // 6.0
class BtechToken {
  const BtechToken();

  // ── typography ─────────────────────────────────────────────
  String get fontFamilySans => 'Inter';
  String get fontFamilyMono => 'JetBrains Mono';

  // ── background ─────────────────────────────────────────────
  Color get backgroundPrimary => const Color(0xFF15803D);
  Color get backgroundPrimaryHover => const Color(0xFF166534);
  Color get backgroundPrimaryPressed => const Color(0xFF14532D);
  Color get backgroundPrimaryDisable => const Color(0xFFE5E7EB);
  Color get backgroundPrimarySubtle => const Color(0xFFF0FDF4);
  Color get backgroundPrimaryBolder => const Color(0xFF166534);
  Color get backgroundSecondary => const Color(0xFFF0FDF4);
  Color get backgroundSecondaryHover => const Color(0xFFDCFCE7);
  Color get backgroundSecondaryPressed => const Color(0xFFBBF7D0);
  Color get backgroundSecondaryDisable => const Color(0xFFF3F4F6);
  Color get backgroundSecondarySubtle => const Color(0xFFF9FAFB);
  Color get backgroundSecondaryBolder => const Color(0xFFBBF7D0);

  // ── stroke ─────────────────────────────────────────────────
  Color get strokePrimary => const Color(0xFF15803D);
  Color get strokePrimaryBolder => const Color(0xFF14532D);

  // ── radius ─────────────────────────────────────────────────
  double get radiusInteractive => 8;
  double get radiusCard => 14;

}
