// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export const BTechRadius = {
  none: 0,
  sm: 2,
  md: 8,
  lg: 14,
  xl: 20,
  full: 9999,
  interactive: 8,
  card: 14,
  badge: 9999,
  tooltip: 2,
} as const;

