// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

import 'package:flutter/material.dart';

// ── InnerShadowDecoration ────────────────────────────────────────────────────
//
// A drop-in Decoration for true CSS-style inset shadows.
//
// Flutter's BoxShadow(blurStyle: BlurStyle.inner) does not work correctly with
// the Impeller renderer (Flutter ≥ 3.10). This implementation uses the
// clip-and-offset CustomPainter technique which works on both Skia and Impeller.
//
// IMPORTANT — blur mapping:
//   CSS  box-shadow blur uses the value as the Gaussian sigma directly.
//   Flutter BoxShadow.blurSigma applies a lossy conversion (r×0.577+0.5) that
//   produces a much softer result than CSS.  We intentionally pass blurRadius
//   directly to MaskFilter so Flutter matches the CSS output.
//
// Usage — identical mental model to CSS inset:
//
//   // CSS
//   style={{ boxShadow: BTechShadow.button.pressed }}   // "inset 0 4px 4px …"
//
//   // Flutter
//   Container(
//     decoration: InnerShadowDecoration(
//       color: context.btechColor.background.primary,
//       borderRadius: BorderRadius.circular(BTechRadius.sm),
//       boxShadow: BTechShadow.button.pressed,
//     ),
//   )

class InnerShadowDecoration extends Decoration {
  const InnerShadowDecoration({
    this.color,
    this.borderRadius,
    this.border,
    this.boxShadow = const [],
  });

  /// Background fill.
  final Color? color;

  /// Corner radius — pass BorderRadius.circular(BTechRadius.sm) etc.
  final BorderRadiusGeometry? borderRadius;

  /// Optional border drawn beneath the shadow layer.
  final BoxBorder? border;

  /// Inner shadow layers.  Pass BTechShadow.button.pressed directly.
  /// The blurStyle field on each BoxShadow is ignored — always rendered inset.
  final List<BoxShadow> boxShadow;

  // ── Lerp ───────────────────────────────────────────────────────────────────

  @override
  InnerShadowDecoration lerpFrom(Decoration? a, double t) {
    if (a is InnerShadowDecoration) return InnerShadowDecoration.lerp(a, this, t)!;
    return super.lerpFrom(a, t) as InnerShadowDecoration;
  }

  @override
  InnerShadowDecoration lerpTo(Decoration? b, double t) {
    if (b is InnerShadowDecoration) return InnerShadowDecoration.lerp(this, b, t)!;
    return super.lerpTo(b, t) as InnerShadowDecoration;
  }

  static InnerShadowDecoration? lerp(
    InnerShadowDecoration? a,
    InnerShadowDecoration? b,
    double t,
  ) {
    if (a == null && b == null) return null;
    return InnerShadowDecoration(
      color:        Color.lerp(a?.color, b?.color, t),
      borderRadius: BorderRadiusGeometry.lerp(a?.borderRadius, b?.borderRadius, t),
      border:       BoxBorder.lerp(a?.border, b?.border, t),
      boxShadow:    BoxShadow.lerpList(a?.boxShadow, b?.boxShadow, t) ?? const [],
    );
  }

  // ── Equality ────────────────────────────────────────────────────────────────

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InnerShadowDecoration &&
          color == other.color &&
          borderRadius == other.borderRadius &&
          border == other.border &&
          boxShadow == other.boxShadow;

  @override
  int get hashCode => Object.hash(color, borderRadius, boxShadow, border);

  // ── Painter ─────────────────────────────────────────────────────────────────

  @override
  BoxPainter createBoxPainter([VoidCallback? onChanged]) =>
      _InnerShadowBoxPainter(this, onChanged);
}

// ── _InnerShadowBoxPainter ───────────────────────────────────────────────────

class _InnerShadowBoxPainter extends BoxPainter {
  _InnerShadowBoxPainter(this._dec, VoidCallback? onChanged) : super(onChanged);

  final InnerShadowDecoration _dec;

  @override
  void paint(Canvas canvas, Offset offset, ImageConfiguration config) {
    final size   = config.size ?? Size.zero;
    final rect   = offset & size;
    final radius = (_dec.borderRadius?.resolve(config.textDirection)
        ?? BorderRadius.zero) as BorderRadius;
    final rrect  = radius.toRRect(rect);

    // 1. Background
    if (_dec.color != null) {
      canvas.drawRRect(rrect, Paint()..color = _dec.color!);
    }

    // 2. Border
    _dec.border?.paint(canvas, rect, borderRadius: radius);

    // 3. Inner shadow layers
    for (final shadow in _dec.boxShadow) {
      _paintInner(canvas, rrect, shadow);
    }
  }

  void _paintInner(Canvas canvas, RRect rrect, BoxShadow shadow) {
    final rect = rrect.outerRect;

    // "Wall" path: a rect large enough to always surround the widget in every
    // direction, with the widget's rounded shape subtracted from it.
    // When shifted by the shadow offset, the wall bleeds into the widget
    // producing the inset shadow.
    final wallSize  = rect.longestSide * 3;
    final outerPath = Path()
      ..addRect(Rect.fromCenter(
          center: rect.center, width: wallSize, height: wallSize));
    final innerPath = Path()..addRRect(rrect);
    final wallPath  = Path.combine(PathOperation.difference, outerPath, innerPath);

    // Use blurRadius directly (not blurSigma) so the result matches CSS:
    //   CSS blur:4px → sigma = 4
    //   Flutter blurSigma for radius=4 → ~2.81  (too soft)
    final paint = Paint()
      ..color      = shadow.color
      ..maskFilter = MaskFilter.blur(BlurStyle.normal, shadow.blurRadius);

    // Save a layer bounded to the widget rect, clip to its shape, then draw
    // the translated wall — only the portion that falls inside the clip
    // (the inset area) is visible.
    canvas.saveLayer(rect, Paint());
    canvas.clipRRect(rrect);
    canvas.save();
    canvas.translate(shadow.offset.dx, shadow.offset.dy);
    canvas.drawPath(wallPath, paint);
    canvas.restore(); // undo translate
    canvas.restore(); // restore clip layer
  }
}
