// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Shadow tokens.
/// Access: BTechShadow.button.pressed  BTechShadow.elevation.md
/// Each getter returns List<BoxShadow> — use inside BoxDecoration.boxShadow.
///
/// ```dart
/// Container(
///   decoration: BoxDecoration(boxShadow: BTechShadow.elevation.md),
/// )
/// ```
class _BTechShadowButtonGroup {
  const _BTechShadowButtonGroup();

  List<BoxShadow> get pressed => const [
    BoxShadow(
      color: Color(0x40000000),
      offset: Offset(0, 4),
      blurRadius: 4,
      spreadRadius: 0,
      blurStyle: BlurStyle.inner,
    ),
  ];

}

class _BTechShadowTableGroup {
  const _BTechShadowTableGroup();

  List<BoxShadow> get left => const [
    BoxShadow(
      color: Color(0x26000000),
      offset: Offset(4, 0),
      blurRadius: 4,
      spreadRadius: 0,
    ),
  ];

  List<BoxShadow> get right => const [
    BoxShadow(
      color: Color(0x26000000),
      offset: Offset(-4, 0),
      blurRadius: 4,
      spreadRadius: 0,
    ),
  ];

}

class _BTechShadowElevationGroup {
  const _BTechShadowElevationGroup();

  List<BoxShadow> get xs => const [
    BoxShadow(
      color: Color(0x0D000000),
      offset: Offset(0, 1),
      blurRadius: 2,
      spreadRadius: 0,
    ),
  ];

  List<BoxShadow> get sm => const [
    BoxShadow(
      color: Color(0x0F000000),
      offset: Offset(0, 1),
      blurRadius: 2,
      spreadRadius: -1,
    ),
    BoxShadow(
      color: Color(0x1A000000),
      offset: Offset(0, 1),
      blurRadius: 3,
      spreadRadius: 0,
    ),
  ];

  List<BoxShadow> get md => const [
    BoxShadow(
      color: Color(0x0F000000),
      offset: Offset(0, 2),
      blurRadius: 4,
      spreadRadius: -2,
    ),
    BoxShadow(
      color: Color(0x1A000000),
      offset: Offset(0, 4),
      blurRadius: 6,
      spreadRadius: -1,
    ),
  ];

  List<BoxShadow> get lg => const [
    BoxShadow(
      color: Color(0x0D000000),
      offset: Offset(0, 4),
      blurRadius: 6,
      spreadRadius: -4,
    ),
    BoxShadow(
      color: Color(0x1A000000),
      offset: Offset(0, 10),
      blurRadius: 15,
      spreadRadius: -3,
    ),
  ];

  List<BoxShadow> get xl => const [
    BoxShadow(
      color: Color(0x0A000000),
      offset: Offset(0, 8),
      blurRadius: 10,
      spreadRadius: -6,
    ),
    BoxShadow(
      color: Color(0x1A000000),
      offset: Offset(0, 20),
      blurRadius: 25,
      spreadRadius: -5,
    ),
  ];

}

abstract class BTechShadow {
  static const button = _BTechShadowButtonGroup();
  static const table = _BTechShadowTableGroup();
  static const elevation = _BTechShadowElevationGroup();
}

