// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate.

// Side-effect: load this tenant's CSS variables into :root.
import './styles.css';

// Re-export the entire base @btech/tokens API.
// Consumers import once: `import { token, setMode, BTechColor } from '@btech/tokens-bspace'`.
export * from '@btech/tokens';
