// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

/**
 * All valid BTech design token paths.
 * Grammar: [category].[property].[role].[emphasis].[state]
 *
 * @example
 * 'color.background.primary'        — primary brand background
 * 'color.text.neutral.subtle'       — secondary text color
 * 'spacing.md'                      — medium spacing (16px)
 * 'radius.interactive'              — button/input border radius
 */
export type TokenPath =
  | 'button.danger.bg'
  | 'button.danger.bgHover'
  | 'button.danger.border'
  | 'button.danger.fg'
  | 'button.danger.radius'
  | 'button.primary.bg'
  | 'button.primary.bgHover'
  | 'button.primary.border'
  | 'button.primary.fg'
  | 'button.primary.radius'
  | 'button.secondary.bg'
  | 'button.secondary.bgHover'
  | 'button.secondary.border'
  | 'button.secondary.fg'
  | 'button.secondary.radius'
  | 'button.size.lg.fontSize'
  | 'button.size.lg.paddingX'
  | 'button.size.lg.paddingY'
  | 'button.size.md.fontSize'
  | 'button.size.md.paddingX'
  | 'button.size.md.paddingY'
  | 'button.size.sm.fontSize'
  | 'button.size.sm.paddingX'
  | 'button.size.sm.paddingY'
  | 'color.amber.100'
  | 'color.amber.200'
  | 'color.amber.300'
  | 'color.amber.400'
  | 'color.amber.50'
  | 'color.amber.500'
  | 'color.amber.600'
  | 'color.amber.700'
  | 'color.amber.800'
  | 'color.amber.900'
  | 'color.background.danger'
  | 'color.background.danger.bolder'
  | 'color.background.danger.disable'
  | 'color.background.danger.hover'
  | 'color.background.danger.pressed'
  | 'color.background.danger.subtle'
  | 'color.background.info'
  | 'color.background.info.bolder'
  | 'color.background.info.disable'
  | 'color.background.info.hover'
  | 'color.background.info.pressed'
  | 'color.background.info.subtle'
  | 'color.background.neutral'
  | 'color.background.neutral.bolder'
  | 'color.background.neutral.subtle'
  | 'color.background.primary'
  | 'color.background.primary.bolder'
  | 'color.background.primary.disable'
  | 'color.background.primary.hover'
  | 'color.background.primary.pressed'
  | 'color.background.primary.subtle'
  | 'color.background.secondary'
  | 'color.background.secondary.bolder'
  | 'color.background.secondary.disable'
  | 'color.background.secondary.hover'
  | 'color.background.secondary.pressed'
  | 'color.background.secondary.subtle'
  | 'color.background.success'
  | 'color.background.success.bolder'
  | 'color.background.success.disable'
  | 'color.background.success.hover'
  | 'color.background.success.pressed'
  | 'color.background.success.subtle'
  | 'color.background.surface'
  | 'color.background.surface.inverse'
  | 'color.background.surface.overlay'
  | 'color.background.surface.raised'
  | 'color.background.surface.subtle'
  | 'color.background.surface.subtler'
  | 'color.background.surface.tertiary'
  | 'color.background.warning'
  | 'color.background.warning.bolder'
  | 'color.background.warning.disable'
  | 'color.background.warning.hover'
  | 'color.background.warning.pressed'
  | 'color.background.warning.subtle'
  | 'color.blue.100'
  | 'color.blue.200'
  | 'color.blue.300'
  | 'color.blue.400'
  | 'color.blue.50'
  | 'color.blue.500'
  | 'color.blue.600'
  | 'color.blue.700'
  | 'color.blue.800'
  | 'color.blue.900'
  | 'color.brand.primary'
  | 'color.brand.primary.bold'
  | 'color.brand.primary.subtle'
  | 'color.brand.secondary'
  | 'color.brand.secondary.bold'
  | 'color.brand.secondary.subtle'
  | 'color.extended.error'
  | 'color.extended.error.bold'
  | 'color.extended.error.subtle'
  | 'color.extended.error.subtler'
  | 'color.extended.info'
  | 'color.extended.info.bold'
  | 'color.extended.info.subtle'
  | 'color.extended.info.subtler'
  | 'color.extended.success'
  | 'color.extended.success.bold'
  | 'color.extended.success.subtle'
  | 'color.extended.success.subtler'
  | 'color.extended.warning'
  | 'color.extended.warning.bold'
  | 'color.extended.warning.subtle'
  | 'color.extended.warning.subtler'
  | 'color.green.100'
  | 'color.green.200'
  | 'color.green.300'
  | 'color.green.400'
  | 'color.green.50'
  | 'color.green.500'
  | 'color.green.600'
  | 'color.green.700'
  | 'color.green.800'
  | 'color.green.900'
  | 'color.icon.danger.base'
  | 'color.icon.danger.bolder'
  | 'color.icon.info.base'
  | 'color.icon.info.bolder'
  | 'color.icon.neutral'
  | 'color.icon.neutral.disabled'
  | 'color.icon.neutral.inverse'
  | 'color.icon.neutral.link'
  | 'color.icon.neutral.subtle'
  | 'color.icon.neutral.tertiary'
  | 'color.icon.secondary.base'
  | 'color.icon.secondary.bolder'
  | 'color.icon.success.base'
  | 'color.icon.success.bolder'
  | 'color.icon.warning.base'
  | 'color.icon.warning.bolder'
  | 'color.indigo.100'
  | 'color.indigo.200'
  | 'color.indigo.300'
  | 'color.indigo.400'
  | 'color.indigo.50'
  | 'color.indigo.500'
  | 'color.indigo.600'
  | 'color.indigo.700'
  | 'color.indigo.800'
  | 'color.indigo.900'
  | 'color.lightblue.100'
  | 'color.lightblue.200'
  | 'color.lightblue.300'
  | 'color.lightblue.400'
  | 'color.lightblue.50'
  | 'color.lightblue.500'
  | 'color.lightblue.600'
  | 'color.lightblue.700'
  | 'color.lightblue.800'
  | 'color.lightblue.900'
  | 'color.neutral.0'
  | 'color.neutral.100'
  | 'color.neutral.1000'
  | 'color.neutral.200'
  | 'color.neutral.300'
  | 'color.neutral.400'
  | 'color.neutral.50'
  | 'color.neutral.500'
  | 'color.neutral.600'
  | 'color.neutral.700'
  | 'color.neutral.800'
  | 'color.neutral.900'
  | 'color.orange.100'
  | 'color.orange.200'
  | 'color.orange.300'
  | 'color.orange.400'
  | 'color.orange.50'
  | 'color.orange.500'
  | 'color.orange.600'
  | 'color.orange.700'
  | 'color.orange.800'
  | 'color.orange.900'
  | 'color.purple.100'
  | 'color.purple.200'
  | 'color.purple.300'
  | 'color.purple.400'
  | 'color.purple.50'
  | 'color.purple.500'
  | 'color.purple.600'
  | 'color.purple.700'
  | 'color.purple.800'
  | 'color.purple.900'
  | 'color.red.100'
  | 'color.red.200'
  | 'color.red.300'
  | 'color.red.400'
  | 'color.red.50'
  | 'color.red.500'
  | 'color.red.600'
  | 'color.red.700'
  | 'color.red.800'
  | 'color.red.900'
  | 'color.rose.100'
  | 'color.rose.200'
  | 'color.rose.300'
  | 'color.rose.400'
  | 'color.rose.50'
  | 'color.rose.500'
  | 'color.rose.600'
  | 'color.rose.700'
  | 'color.rose.800'
  | 'color.rose.900'
  | 'color.sky.100'
  | 'color.sky.200'
  | 'color.sky.300'
  | 'color.sky.400'
  | 'color.sky.50'
  | 'color.sky.500'
  | 'color.sky.600'
  | 'color.sky.700'
  | 'color.sky.800'
  | 'color.sky.900'
  | 'color.stroke.danger'
  | 'color.stroke.danger.bolder'
  | 'color.stroke.info'
  | 'color.stroke.info.bolder'
  | 'color.stroke.neutral'
  | 'color.stroke.neutral.disabled'
  | 'color.stroke.neutral.inverse'
  | 'color.stroke.neutral.strong'
  | 'color.stroke.neutral.subtle'
  | 'color.stroke.neutral.tertiary'
  | 'color.stroke.primary'
  | 'color.stroke.primary.bolder'
  | 'color.stroke.secondary'
  | 'color.stroke.secondary.bolder'
  | 'color.stroke.success'
  | 'color.stroke.success.bolder'
  | 'color.stroke.warning'
  | 'color.stroke.warning.bolder'
  | 'color.teal.100'
  | 'color.teal.200'
  | 'color.teal.300'
  | 'color.teal.400'
  | 'color.teal.50'
  | 'color.teal.500'
  | 'color.teal.600'
  | 'color.teal.700'
  | 'color.teal.800'
  | 'color.teal.900'
  | 'color.text.danger.base'
  | 'color.text.danger.bolder'
  | 'color.text.info.base'
  | 'color.text.info.bolder'
  | 'color.text.neutral'
  | 'color.text.neutral.disabled'
  | 'color.text.neutral.inverse'
  | 'color.text.neutral.link'
  | 'color.text.neutral.subtle'
  | 'color.text.neutral.tertiary'
  | 'color.text.secondary.base'
  | 'color.text.secondary.bolder'
  | 'color.text.success.base'
  | 'color.text.success.bolder'
  | 'color.text.warning.base'
  | 'color.text.warning.bolder'
  | 'motion.duration.fast'
  | 'motion.duration.normal'
  | 'motion.duration.slow'
  | 'motion.easing.ease'
  | 'motion.easing.easeIn'
  | 'motion.easing.easeOut'
  | 'motion.easing.linear'
  | 'radius.2xl'
  | 'radius.2xs'
  | 'radius.badge'
  | 'radius.card'
  | 'radius.interactive'
  | 'radius.lg'
  | 'radius.md'
  | 'radius.rd'
  | 'radius.sm'
  | 'radius.tooltip'
  | 'radius.xl'
  | 'radius.xs'
  | 'shadow.lg'
  | 'shadow.md'
  | 'shadow.none'
  | 'shadow.sm'
  | 'shadow.xl'
  | 'spacing.2xl'
  | 'spacing.2xs'
  | 'spacing.3xl'
  | 'spacing.lg'
  | 'spacing.md'
  | 'spacing.sm'
  | 'spacing.xl'
  | 'spacing.xs'
  | 'typography.body.fontFamily'
  | 'typography.body.fontSize'
  | 'typography.body.fontWeight'
  | 'typography.body.lineHeight'
  | 'typography.code.fontFamily'
  | 'typography.code.fontSize'
  | 'typography.fontFamily.mono'
  | 'typography.fontFamily.sans'
  | 'typography.fontSize.2xl'
  | 'typography.fontSize.2xs'
  | 'typography.fontSize.3xl'
  | 'typography.fontSize.3xs'
  | 'typography.fontSize.4xl'
  | 'typography.fontSize.5xl'
  | 'typography.fontSize.lg'
  | 'typography.fontSize.md'
  | 'typography.fontSize.sm'
  | 'typography.fontSize.xl'
  | 'typography.fontSize.xs'
  | 'typography.fontWeight.bold'
  | 'typography.fontWeight.medium'
  | 'typography.fontWeight.regular'
  | 'typography.fontWeight.semibold'
  | 'typography.heading.fontFamily'
  | 'typography.heading.fontWeight'
  | 'typography.heading.lineHeight'
  | 'typography.label.fontFamily'
  | 'typography.label.fontSize'
  | 'typography.label.fontWeight'
  | 'typography.label.lineHeight'
  | 'typography.letterSpacing.snug'
  | 'typography.letterSpacing.tight'
  | 'typography.letterSpacing.tighter'
  | 'typography.letterSpacing.wide'
  | 'typography.letterSpacing.wider'
  | 'typography.lineHeight.2xl'
  | 'typography.lineHeight.2xs'
  | 'typography.lineHeight.3xl'
  | 'typography.lineHeight.4xl'
  | 'typography.lineHeight.lg'
  | 'typography.lineHeight.md'
  | 'typography.lineHeight.sm'
  | 'typography.lineHeight.xl'
  | 'typography.lineHeight.xs'
  | 'typography.typeScale.body.base.fontSize'
  | 'typography.typeScale.body.base.fontWeight'
  | 'typography.typeScale.body.base.lineHeightPx'
  | 'typography.typeScale.body.base.withTextColor'
  | 'typography.typeScale.body.bold.fontSize'
  | 'typography.typeScale.body.bold.fontWeight'
  | 'typography.typeScale.body.bold.lineHeightPx'
  | 'typography.typeScale.body.bold.withTextColor'
  | 'typography.typeScale.body.italic.fontSize'
  | 'typography.typeScale.body.italic.fontStyle'
  | 'typography.typeScale.body.italic.fontWeight'
  | 'typography.typeScale.body.italic.lineHeightPx'
  | 'typography.typeScale.body.italic.withTextColor'
  | 'typography.typeScale.body.medium.fontSize'
  | 'typography.typeScale.body.medium.fontWeight'
  | 'typography.typeScale.body.medium.lineHeightPx'
  | 'typography.typeScale.body.medium.withTextColor'
  | 'typography.typeScale.body.paragraph.fontSize'
  | 'typography.typeScale.body.paragraph.fontWeight'
  | 'typography.typeScale.body.paragraph.lineHeightPx'
  | 'typography.typeScale.body.paragraph.withTextColor'
  | 'typography.typeScale.body.small.fontSize'
  | 'typography.typeScale.body.small.fontWeight'
  | 'typography.typeScale.body.small.lineHeightPx'
  | 'typography.typeScale.body.small.withTextColor'
  | 'typography.typeScale.body.underline.fontSize'
  | 'typography.typeScale.body.underline.fontWeight'
  | 'typography.typeScale.body.underline.lineHeightPx'
  | 'typography.typeScale.body.underline.textDecoration'
  | 'typography.typeScale.body.underline.withTextColor'
  | 'typography.typeScale.body.xstraSmall.fontSize'
  | 'typography.typeScale.body.xstraSmall.fontWeight'
  | 'typography.typeScale.body.xstraSmall.lineHeightPx'
  | 'typography.typeScale.body.xstraSmall.withTextColor'
  | 'typography.typeScale.heading.h1.fontSize'
  | 'typography.typeScale.heading.h1.fontWeight'
  | 'typography.typeScale.heading.h1.lineHeightPx'
  | 'typography.typeScale.heading.h2.fontSize'
  | 'typography.typeScale.heading.h2.fontWeight'
  | 'typography.typeScale.heading.h2.lineHeightPx'
  | 'typography.typeScale.heading.h3.fontSize'
  | 'typography.typeScale.heading.h3.fontWeight'
  | 'typography.typeScale.heading.h3.lineHeightPx'
  | 'typography.typeScale.heading.h3.withTextColor'
  | 'typography.typeScale.heading.h4.fontSize'
  | 'typography.typeScale.heading.h4.fontWeight'
  | 'typography.typeScale.heading.h4.lineHeightPx'
  | 'typography.typeScale.heading.h4.withTextColor'
  | 'typography.typeScale.subheading.h5.fontSize'
  | 'typography.typeScale.subheading.h5.fontWeight'
  | 'typography.typeScale.subheading.h5.lineHeightPx'
  | 'typography.typeScale.subheading.h5.withTextColor'
  | 'typography.typeScale.subheading.h6.fontSize'
  | 'typography.typeScale.subheading.h6.fontWeight'
  | 'typography.typeScale.subheading.h6.lineHeightPx'
  | 'typography.typeScale.subheading.h6.withTextColor'
  | 'typography.typeScale.subheading.h7.fontSize'
  | 'typography.typeScale.subheading.h7.fontWeight'
  | 'typography.typeScale.subheading.h7.lineHeightPx'
  | 'typography.typeScale.subheading.h7.withTextColor'
  | 'zIndex.base'
  | 'zIndex.dropdown'
  | 'zIndex.modal'
  | 'zIndex.overlay'
  | 'zIndex.raised'
  | 'zIndex.sticky'
  | 'zIndex.toast'
  | 'zIndex.tooltip'

// =============================================================================
// Atlassian-aligned CSS variable naming (mirrors --ds-* with --btech-* prefix)
// =============================================================================
// styles.css defines every token as a CSS custom property:
//   :root {
//     --btech-background-primary: #...;   (was --btech-color-background-primary)
//     --btech-space-md: 16px;             (was --btech-spacing-md)
//     --btech-font-family-sans: ...;      (was --btech-typography-font-family-sans)
//     --btech-border-neutral: #...;       (was --btech-color-stroke-neutral)
//     --btech-duration-fast: 100ms;       (was --btech-motion-duration-fast)
//     --btech-z-modal: 400;               (was --btech-z-index-modal)
//   }
//
// token() returns the identical var() — same as writing it by hand in CSS.
// Tenant switching via [data-tenant="bjb"] works automatically for both.
// =============================================================================

// Internal: same logic as pathToCssVarStem() in config/generators/utils.ts
const PRIMITIVE_COLORS = new Set(['blue','red','green','orange','neutral','yellow','pink','purple','teal','slate']);
function _pathToVarName(dotPath: string): string {
  const [cat, ...rest] = dotPath.split('.');
  let stem: string;
  switch (cat) {
    case 'color': {
      const sub = rest[0];
      if (PRIMITIVE_COLORS.has(sub)) { stem = ['color', ...rest].join('-'); break; }
      if (sub === 'stroke')          { stem = ['border', ...rest.slice(1)].join('-'); break; }
      stem = rest.join('-'); break;
    }
    case 'spacing': stem = ['space', ...rest].join('-'); break;
    case 'typography': stem = rest.join('-'); break;
    case 'zIndex': stem = ['z', ...rest].join('-'); break;
    case 'motion': stem = rest.join('-'); break;
    default: stem = [cat, ...rest].join('-');
  }
  return stem.replace(/([A-Z])/g, m => `-${m.toLowerCase()}`);
}

/**
 * Returns the CSS custom property reference for any design token.
 * Atlassian-aligned: category is dropped from the var name.
 *
 * ── Color ────────────────────────────────────────────────────────────────────
 * token('color.background.primary')        → var(--btech-background-primary)
 * token('color.background.primary.hover')  → var(--btech-background-primary-hover)
 * token('color.text.on.primary')           → var(--btech-text-on-primary)
 * token('color.icon.neutral.subtle')       → var(--btech-icon-neutral-subtle)
 * token('color.stroke.primary')            → var(--btech-border-primary)
 * token('color.blue.500')                  → var(--btech-color-blue-500)
 *
 * ── Spacing ─────────────────────────────────────────────────────────────────
 * token('spacing.xs')   → var(--btech-space-xs)
 * token('spacing.md')   → var(--btech-space-md)
 *
 * ── Radius / Shadow ─────────────────────────────────────────────────────────
 * token('radius.interactive') → var(--btech-radius-interactive)
 * token('shadow.md')          → var(--btech-shadow-md)
 *
 * ── Typography ─────────────────────────────────────────────────────────────
 * token('typography.fontFamily.sans')     → var(--btech-font-family-sans)
 * token('typography.fontSize.sm')         → var(--btech-font-size-sm)
 * token('typography.fontWeight.semibold') → var(--btech-font-weight-semibold)
 * token('typography.lineHeight.normal')   → var(--btech-line-height-normal)
 *
 * ── Motion / Z-Index ───────────────────────────────────────────────────────
 * token('motion.duration.fast')  → var(--btech-duration-fast)
 * token('motion.easing.ease')    → var(--btech-easing-ease)
 * token('zIndex.modal')          → var(--btech-z-modal)
 *
 * ── With fallback ───────────────────────────────────────────────────────────
 * token('color.background.primary', '#15803d') → var(--btech-background-primary, #15803d)
 */
export function token(path: TokenPath, fallback?: string): string {
  const varName = `--btech-${_pathToVarName(path)}`;
  return fallback ? `var(${varName}, ${fallback})` : `var(${varName})`;
}

/**
 * Raw CSS variable name — no var() wrapper.
 * Use for setProperty(), CSS-in-JS that wraps var() itself, or calc().
 *
 * cssVar('color.background.primary') → '--btech-background-primary'
 * element.style.setProperty(cssVar('color.background.primary'), '#0057b7');
 */
export function cssVar(path: TokenPath): string {
  return `--btech-${_pathToVarName(path)}`;
}

/**
 * Wraps a token in calc().
 *
 * tokenCalc('spacing.md', '* 2')    → 'calc(var(--btech-space-md) * 2)'
 * tokenCalc('spacing.sm', '+ 4px')  → 'calc(var(--btech-space-sm) + 4px)'
 */
export function tokenCalc(path: TokenPath, expression: string): string {
  return `calc(${token(path)} ${expression})`;
}
