// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechBackgroundColor {
  readonly surface = '#f4f5f6' as const;
  readonly surfaceSubtle = '#ecedee' as const;
  readonly surfaceRaised = '#ffffff' as const;
  readonly surfaceSubtler = '#dbdde1' as const;
  readonly surfaceTertiary = '#64748b' as const;
  readonly surfaceInverse = '#181c20' as const;
  readonly surfaceOverlay = 'rgba(24,28,32,0.8)' as const;
  readonly primary = '#08a94c' as const;
  readonly primaryHover = '#0a853e' as const;
  readonly primaryPressed = '#0a632f' as const;
  readonly primaryDisable = '#dbdde1' as const;
  readonly primarySubtle = '#f0f8f4' as const;
  readonly primaryBolder = '#0a853e' as const;
  readonly secondary = '#f0f8f4' as const;
  readonly secondaryHover = '#e2f3e9' as const;
  readonly secondaryPressed = '#c5ead5' as const;
  readonly secondaryDisable = '#ecedee' as const;
  readonly secondarySubtle = '#f4f5f6' as const;
  readonly secondaryBolder = '#c5ead5' as const;
  readonly danger = '#ef4444' as const;
  readonly dangerHover = '#d81818' as const;
  readonly dangerPressed = '#991515' as const;
  readonly dangerDisable = '#dbdde1' as const;
  readonly dangerSubtle = '#f9f2f2' as const;
  readonly dangerBolder = '#991515' as const;
  readonly success = '#08a94c' as const;
  readonly successHover = '#0a853e' as const;
  readonly successPressed = '#0a632f' as const;
  readonly successDisable = '#dbdde1' as const;
  readonly successSubtle = '#f0f8f4' as const;
  readonly successBolder = '#0a632f' as const;
  readonly warning = '#f59e0b' as const;
  readonly warningHover = '#bd7c0c' as const;
  readonly warningPressed = '#885a0d' as const;
  readonly warningDisable = '#dbdde1' as const;
  readonly warningSubtle = '#f9f6f1' as const;
  readonly warningBolder = '#885a0d' as const;
  readonly info = '#0ea5e9' as const;
  readonly infoHover = '#0f81b4' as const;
  readonly infoPressed = '#0f5e81' as const;
  readonly infoDisable = '#dbdde1' as const;
  readonly infoSubtle = '#f1f6f9' as const;
  readonly infoBolder = '#0f5e81' as const;
  readonly neutral = '#ecedee' as const;
  readonly neutralSubtle = '#f4f5f6' as const;
  readonly neutralBolder = '#dbdde1' as const;
}

