// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

import { BTechTextColor } from './text.color';
import { BTechIconColor } from './icon.color';
import { BTechBorderColor } from './border.color';
import { BTechBgColor } from './bg.color';
import { BTechBrandColor } from './brand.color';
import { BTechExtColor } from './ext.color';
import { btechColorGreen, btechColorLightblue, btechColorOrange, btechColorBlue, btechColorPurple, btechColorTeal, btechColorIndigo, btechColorRose, btechColorYellow, btechColorNeutral, btechColorRed, btechColorAmber, btechColorSky, btechColorBrandPrimary, btechColorBrandSecondary } from './swatches.color';

export const BTechColor = {
  text: new BTechTextColor(),
  icon: new BTechIconColor(),
  border: new BTechBorderColor(),
  bg: new BTechBgColor(),
  brand: new BTechBrandColor(),
  ext: new BTechExtColor(),

  // Primitive color groups — direct numeric-key access.
  green: btechColorGreen,
  lightblue: btechColorLightblue,
  orange: btechColorOrange,
  blue: btechColorBlue,
  purple: btechColorPurple,
  teal: btechColorTeal,
  indigo: btechColorIndigo,
  rose: btechColorRose,
  yellow: btechColorYellow,
  neutral: btechColorNeutral,
  red: btechColorRed,
  amber: btechColorAmber,
  sky: btechColorSky,

  // Brand primitive swatches (tenant-overridable).
  brandPrimary: btechColorBrandPrimary,
  brandSecondary: btechColorBrandSecondary,
} as const;

