// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechShadesGreenColor {
  readonly s50 = '#f0f8f4' as const;
  readonly s100 = '#e2f3e9' as const;
  readonly s200 = '#c5ead5' as const;
  readonly s300 = '#94e2b5' as const;
  readonly s400 = '#41e084' as const;
  readonly s500 = '#08a94c' as const;
  readonly s600 = '#0a853e' as const;
  readonly s700 = '#0a632f' as const;
  readonly s800 = '#094623' as const;
  readonly s900 = '#072d17' as const;
}

export class BTechShadesLightblueColor {
  readonly s50 = '#f2f6f8' as const;
  readonly s100 = '#e9f1f4' as const;
  readonly s200 = '#d6e6ed' as const;
  readonly s300 = '#b6d7e4' as const;
  readonly s400 = '#80c3de' as const;
  readonly s500 = '#30aee1' as const;
  readonly s600 = '#1f8cb8' as const;
  readonly s700 = '#1a6583' as const;
  readonly s800 = '#134357' as const;
  readonly s900 = '#0b2530' as const;
}

export class BTechShadesOrangeColor {
  readonly s50 = '#f9f6f1' as const;
  readonly s100 = '#f6efe8' as const;
  readonly s200 = '#f0e3d3' as const;
  readonly s300 = '#ebd2b1' as const;
  readonly s400 = '#ebb876' as const;
  readonly s500 = '#f8981d' as const;
  readonly s600 = '#ce790c' as const;
  readonly s700 = '#93580c' as const;
  readonly s800 = '#603b0a' as const;
  readonly s900 = '#352107' as const;
}

export class BTechShadesBlueColor {
  readonly s50 = '#e7eff9' as const;
  readonly s100 = '#d0def3' as const;
  readonly s200 = '#a1bde7' as const;
  readonly s300 = '#729ddb' as const;
  readonly s400 = '#437ccf' as const;
  readonly s500 = '#145bc3' as const;
  readonly s600 = '#10499c' as const;
  readonly s700 = '#0c3775' as const;
  readonly s800 = '#08244e' as const;
  readonly s900 = '#041227' as const;
}

export class BTechShadesPurpleColor {
  readonly s50 = '#f3eef9' as const;
  readonly s100 = '#e8def3' as const;
  readonly s200 = '#d0bde7' as const;
  readonly s300 = '#b99bda' as const;
  readonly s400 = '#a17ace' as const;
  readonly s500 = '#8a59c2' as const;
  readonly s600 = '#6e479b' as const;
  readonly s700 = '#533574' as const;
  readonly s800 = '#37244e' as const;
  readonly s900 = '#1c1227' as const;
}

export class BTechShadesTealColor {
  readonly s50 = '#f0f8f7' as const;
  readonly s100 = '#e2f2f0' as const;
  readonly s200 = '#c4e8e5' as const;
  readonly s300 = '#93ddd7' as const;
  readonly s400 = '#3ed8ca' as const;
  readonly s500 = '#0d9488' as const;
  readonly s600 = '#0d766c' as const;
  readonly s700 = '#0c5852' as const;
  readonly s800 = '#0a403b' as const;
  readonly s900 = '#082a27' as const;
}

export class BTechShadesIndigoColor {
  readonly s50 = '#f3f3f9' as const;
  readonly s100 = '#ececf6' as const;
  readonly s200 = '#dedef2' as const;
  readonly s300 = '#c7c7ed' as const;
  readonly s400 = '#9fa0eb' as const;
  readonly s500 = '#6366f1' as const;
  readonly s600 = '#2328e6' as const;
  readonly s700 = '#181ba7' as const;
  readonly s800 = '#12146b' as const;
  readonly s900 = '#0a0b36' as const;
}

export class BTechShadesRoseColor {
  readonly s50 = '#f8f2f3' as const;
  readonly s100 = '#f4e8ea' as const;
  readonly s200 = '#ecd3d8' as const;
  readonly s300 = '#e3b0bb' as const;
  readonly s400 = '#de758c' as const;
  readonly s500 = '#e11d48' as const;
  readonly s600 = '#ae1b3b' as const;
  readonly s700 = '#7d162d' as const;
  readonly s800 = '#531120' as const;
  readonly s900 = '#2f0b13' as const;
}

export class BTechShadesNeutralColor {
  readonly s0 = '#ffffff' as const;
  readonly s50 = '#f4f5f6' as const;
  readonly s100 = '#ecedee' as const;
  readonly s200 = '#dbdde1' as const;
  readonly s300 = '#c1c6cd' as const;
  readonly s400 = '#98a2b0' as const;
  readonly s500 = '#64748b' as const;
  readonly s600 = '#505c6d' as const;
  readonly s700 = '#3c4450' as const;
  readonly s800 = '#292f37' as const;
  readonly s900 = '#181c20' as const;
  readonly s1000 = '#000000' as const;
}

export class BTechShadesRedColor {
  readonly s50 = '#f9f2f2' as const;
  readonly s100 = '#f6eaea' as const;
  readonly s200 = '#f0d9d9' as const;
  readonly s300 = '#ebbdbd' as const;
  readonly s400 = '#e88d8d' as const;
  readonly s500 = '#ef4444' as const;
  readonly s600 = '#d81818' as const;
  readonly s700 = '#991515' as const;
  readonly s800 = '#631010' as const;
  readonly s900 = '#340a0a' as const;
}

export class BTechShadesAmberColor {
  readonly s50 = '#f9f6f1' as const;
  readonly s100 = '#f5f0e7' as const;
  readonly s200 = '#efe3d0' as const;
  readonly s300 = '#e9d2ab' as const;
  readonly s400 = '#e8ba6c' as const;
  readonly s500 = '#f59e0b' as const;
  readonly s600 = '#bd7c0c' as const;
  readonly s700 = '#885a0d' as const;
  readonly s800 = '#5a3d0b' as const;
  readonly s900 = '#332307' as const;
}

export class BTechShadesSkyColor {
  readonly s50 = '#f1f6f9' as const;
  readonly s100 = '#e7f0f4' as const;
  readonly s200 = '#d0e4ed' as const;
  readonly s300 = '#aad4e7' as const;
  readonly s400 = '#69bee4' as const;
  readonly s500 = '#0ea5e9' as const;
  readonly s600 = '#0f81b4' as const;
  readonly s700 = '#0f5e81' as const;
  readonly s800 = '#0c3f57' as const;
  readonly s900 = '#082431' as const;
}

export class BTechShadesColor {
  readonly green = new BTechShadesGreenColor();
  readonly lightblue = new BTechShadesLightblueColor();
  readonly orange = new BTechShadesOrangeColor();
  readonly blue = new BTechShadesBlueColor();
  readonly purple = new BTechShadesPurpleColor();
  readonly teal = new BTechShadesTealColor();
  readonly indigo = new BTechShadesIndigoColor();
  readonly rose = new BTechShadesRoseColor();
  readonly neutral = new BTechShadesNeutralColor();
  readonly red = new BTechShadesRedColor();
  readonly amber = new BTechShadesAmberColor();
  readonly sky = new BTechShadesSkyColor();
}

