// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

export class BTechStrokeColor {
  readonly neutral = '#dbdde1' as const;
  readonly neutralStrong = '#98a2b0' as const;
  readonly neutralSubtle = '#ecedee' as const;
  readonly neutralTertiary = '#c1c6cd' as const;
  readonly neutralInverse = '#292f37' as const;
  readonly neutralDisabled = '#c1c6cd' as const;
  readonly primary = '#08a94c' as const;
  readonly primaryBolder = '#0a632f' as const;
  readonly danger = '#ef4444' as const;
  readonly dangerBolder = '#991515' as const;
  readonly success = '#08a94c' as const;
  readonly successBolder = '#0a632f' as const;
  readonly warning = '#f59e0b' as const;
  readonly warningBolder = '#885a0d' as const;
  readonly info = '#0ea5e9' as const;
  readonly infoBolder = '#0f5e81' as const;
  readonly secondary = '#8a59c2' as const;
  readonly secondaryBolder = '#533574' as const;
}

