// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechBackgroundSurfaceColor extends Color {
  const BTechBackgroundSurfaceColor()
    : subtle = const Color(0xFFF3F4F6),
      raised = const Color(0xFFFFFFFF),
      super(0xFFF9FAFB);
  final Color subtle;
  final Color raised;
}

class BTechBackgroundPrimaryColor extends Color {
  const BTechBackgroundPrimaryColor()
    : hover = const Color(0xFF166534),
      super(0xFF15803D);
  final Color hover;
}

class BTechBackgroundSecondaryColor extends Color {
  const BTechBackgroundSecondaryColor()
    : hover = const Color(0xFFDCFCE7),
      super(0xFFF0FDF4);
  final Color hover;
}

class BTechBackgroundDangerColor extends Color {
  const BTechBackgroundDangerColor()
    : hover = const Color(0xFFB91C1C),
      super(0xFFDC2626);
  final Color hover;
}

class BTechBackgroundSuccessColor extends Color {
  const BTechBackgroundSuccessColor()
    : hover = const Color(0xFF16A34A),
      super(0xFF22C55E);
  final Color hover;
}

class BTechBackgroundWarningColor extends Color {
  const BTechBackgroundWarningColor()
    : hover = const Color(0xFFF97316),
      super(0xFFFB923C);
  final Color hover;
}

/// Semantic background color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechBackgroundColor.surface → Color
class BTechBackgroundColor {
  const BTechBackgroundColor()
    : surface = const BTechBackgroundSurfaceColor(),
      primary = const BTechBackgroundPrimaryColor(),
      secondary = const BTechBackgroundSecondaryColor(),
      danger = const BTechBackgroundDangerColor(),
      success = const BTechBackgroundSuccessColor(),
      warning = const BTechBackgroundWarningColor();
  final BTechBackgroundSurfaceColor surface;
  final BTechBackgroundPrimaryColor primary;
  final BTechBackgroundSecondaryColor secondary;
  final BTechBackgroundDangerColor danger;
  final BTechBackgroundSuccessColor success;
  final BTechBackgroundWarningColor warning;
}

