// AUTO-GENERATED by @ramaMS06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechIconNeutralColor extends Color {
  const BTechIconNeutralColor()
    : subtle = const Color(0xFF9CA3AF),
      disabled = const Color(0xFFD1D5DB),
      inverse = const Color(0xFFFFFFFF),
      super(0xFF374151);
  final Color subtle;
  final Color disabled;
  final Color inverse;
}

class BTechIconDangerColor extends Color {
  const BTechIconDangerColor()
    : bolder = const Color(0xFF991B1B),
      super(0xFFDC2626);
  final Color bolder;
}

class BTechIconSuccessColor extends Color {
  const BTechIconSuccessColor()
    : bolder = const Color(0xFF166534),
      super(0xFF16A34A);
  final Color bolder;
}

class BTechIconWarningColor extends Color {
  const BTechIconWarningColor()
    : bolder = const Color(0xFFC2410C),
      super(0xFFF97316);
  final Color bolder;
}

class BTechIconInfoColor extends Color {
  const BTechIconInfoColor()
    : bolder = const Color(0xFF1E40AF),
      super(0xFF2563EB);
  final Color bolder;
}

class BTechIconSecondaryColor extends Color {
  const BTechIconSecondaryColor()
    : bolder = const Color(0xFF6B21A8),
      super(0xFF9333EA);
  final Color bolder;
}

class BTechIconOnColor extends Color {
  const BTechIconOnColor()
    : secondary = const Color(0xFF166534),
      danger = const Color(0xFFFFFFFF),
      super(0xFFFFFFFF);
  final Color secondary;
  final Color danger;
}

/// Semantic icon color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechIconColor.neutral → Color
class BTechIconColor {
  const BTechIconColor()
    : neutral = const BTechIconNeutralColor(),
      danger = const BTechIconDangerColor(),
      success = const BTechIconSuccessColor(),
      warning = const BTechIconWarningColor(),
      info = const BTechIconInfoColor(),
      secondary = const BTechIconSecondaryColor(),
      on = const BTechIconOnColor();
  final BTechIconNeutralColor neutral;
  final BTechIconDangerColor danger;
  final BTechIconSuccessColor success;
  final BTechIconWarningColor warning;
  final BTechIconInfoColor info;
  final BTechIconSecondaryColor secondary;
  final BTechIconOnColor on;
}

