// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechStrokeNeutralColor extends Color {
  const BTechStrokeNeutralColor()
    : strong = const Color(0xFF9CA3AF),
      super(0xFFE5E7EB);
  final Color strong;
}

class BTechStrokePrimaryColor extends Color {
  const BTechStrokePrimaryColor() : super(0xFF15803D);
}

class BTechStrokeDangerColor extends Color {
  const BTechStrokeDangerColor() : super(0xFFDC2626);
}

/// Semantic stroke color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechStrokeColor.neutral → Color
class BTechStrokeColor {
  const BTechStrokeColor()
    : neutral = const BTechStrokeNeutralColor(),
      primary = const BTechStrokePrimaryColor(),
      danger = const BTechStrokeDangerColor();
  final BTechStrokeNeutralColor neutral;
  final BTechStrokePrimaryColor primary;
  final BTechStrokeDangerColor danger;
}

