/**
 * Interactive CLI to scaffold a new tenant override file.
 *
 * Usage: pnpm add-tenant
 */
import { createInterface } from 'readline';
import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dirname, '..');

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve));
}

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function isValidHex(hex: string): boolean {
  return /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(hex);
}

async function main() {
  console.log('\n🎨 Add a new tenant\n');

  const rawId = await ask('Tenant ID (slug, e.g. mandiri): ');
  const tenantId = slugify(rawId);

  if (!tenantId) {
    console.error('❌ Invalid tenant ID');
    process.exit(1);
  }

  const tenantDir = resolve(ROOT, `tokens/tenants/${tenantId}`);
  if (existsSync(tenantDir)) {
    console.error(`❌ Tenant "${tenantId}" already exists at ${tenantDir}`);
    process.exit(1);
  }

  let primaryColor = await ask('Primary brand color (hex, e.g. #003D7C): ');
  primaryColor = primaryColor.trim();
  if (!isValidHex(primaryColor)) {
    console.error('❌ Invalid hex color. Must be #RRGGBB or #RGB.');
    process.exit(1);
  }

  const radiusStr = await ask('Base interactive radius in px (e.g. 6): ');
  const radius = parseInt(radiusStr.trim(), 10);
  if (isNaN(radius) || radius < 0) {
    console.error('❌ Invalid radius. Must be a non-negative integer.');
    process.exit(1);
  }

  rl.close();

  const overrides = {
    $description: `Tenant ${tenantId} — auto-generated by add-tenant script`,
    color: {
      background: {
        primary: { $value: primaryColor, $type: 'color' },
      },
    },
    radius: {
      interactive: { $value: `${radius}px`, $type: 'dimension' },
    },
  };

  mkdirSync(tenantDir, { recursive: true });
  writeFileSync(
    resolve(tenantDir, 'overrides.json'),
    JSON.stringify(overrides, null, 2) + '\n'
  );

  console.log(`\n✅ Created tokens/tenants/${tenantId}/overrides.json`);
  console.log(`\nNext steps:`);
  console.log(`  1. Review and extend the overrides file`);
  console.log(`  2. Run "pnpm validate" to check boundary compliance`);
  console.log(`  3. Open a PR — CI will validate automatically\n`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
