// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechBackgroundSurfaceColor extends Color {
  const BTechBackgroundSurfaceColor()
    : subtle = const Color(0xFFF3F4F6),
      raised = const Color(0xFFFFFFFF),
      super(0xFFF9FAFB);
  final Color subtle;
  final Color raised;
}

class BTechBackgroundPrimaryColor extends Color {
  const BTechBackgroundPrimaryColor()
    : hover = const Color(0xFF166534),
      pressed = const Color(0xFF14532D),
      disable = const Color(0xFFE5E7EB),
      subtle = const Color(0xFFF0FDF4),
      bolder = const Color(0xFF166534),
      super(0xFF15803D);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundSecondaryColor extends Color {
  const BTechBackgroundSecondaryColor()
    : hover = const Color(0xFFDCFCE7),
      pressed = const Color(0xFFBBF7D0),
      disable = const Color(0xFFF3F4F6),
      subtle = const Color(0xFFF9FAFB),
      bolder = const Color(0xFFBBF7D0),
      super(0xFFF0FDF4);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundDangerColor extends Color {
  const BTechBackgroundDangerColor()
    : hover = const Color(0xFFB91C1C),
      pressed = const Color(0xFF991B1B),
      disable = const Color(0xFFE5E7EB),
      subtle = const Color(0xFFFEF2F2),
      bolder = const Color(0xFF991B1B),
      super(0xFFDC2626);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundSuccessColor extends Color {
  const BTechBackgroundSuccessColor()
    : hover = const Color(0xFF16A34A),
      pressed = const Color(0xFF15803D),
      disable = const Color(0xFFE5E7EB),
      subtle = const Color(0xFFF0FDF4),
      bolder = const Color(0xFF15803D),
      super(0xFF22C55E);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundWarningColor extends Color {
  const BTechBackgroundWarningColor()
    : hover = const Color(0xFFF97316),
      pressed = const Color(0xFFEA580C),
      disable = const Color(0xFFE5E7EB),
      subtle = const Color(0xFFFFF7ED),
      bolder = const Color(0xFFEA580C),
      super(0xFFFB923C);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundInfoColor extends Color {
  const BTechBackgroundInfoColor()
    : hover = const Color(0xFF1D4ED8),
      pressed = const Color(0xFF1E40AF),
      disable = const Color(0xFFE5E7EB),
      subtle = const Color(0xFFEFF6FF),
      bolder = const Color(0xFF1E40AF),
      super(0xFF2563EB);
  final Color hover;
  final Color pressed;
  final Color disable;
  final Color subtle;
  final Color bolder;
}

class BTechBackgroundNeutralColor extends Color {
  const BTechBackgroundNeutralColor()
    : subtle = const Color(0xFFF9FAFB),
      bolder = const Color(0xFFE5E7EB),
      super(0xFFF3F4F6);
  final Color subtle;
  final Color bolder;
}

/// Semantic background color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechBackgroundColor.surface → Color
class BTechBackgroundColor {
  const BTechBackgroundColor()
    : surface = const BTechBackgroundSurfaceColor(),
      primary = const BTechBackgroundPrimaryColor(),
      secondary = const BTechBackgroundSecondaryColor(),
      danger = const BTechBackgroundDangerColor(),
      success = const BTechBackgroundSuccessColor(),
      warning = const BTechBackgroundWarningColor(),
      info = const BTechBackgroundInfoColor(),
      neutral = const BTechBackgroundNeutralColor();
  final BTechBackgroundSurfaceColor surface;
  final BTechBackgroundPrimaryColor primary;
  final BTechBackgroundSecondaryColor secondary;
  final BTechBackgroundDangerColor danger;
  final BTechBackgroundSuccessColor success;
  final BTechBackgroundWarningColor warning;
  final BTechBackgroundInfoColor info;
  final BTechBackgroundNeutralColor neutral;
}

