// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

class BTechStrokeNeutralColor extends Color {
  const BTechStrokeNeutralColor()
    : strong = const Color(0xFF9CA3AF),
      subtle = const Color(0xFFF3F4F6),
      super(0xFFE5E7EB);
  final Color strong;
  final Color subtle;
}

class BTechStrokePrimaryColor extends Color {
  const BTechStrokePrimaryColor()
    : bolder = const Color(0xFF14532D),
      super(0xFF15803D);
  final Color bolder;
}

class BTechStrokeDangerColor extends Color {
  const BTechStrokeDangerColor()
    : bolder = const Color(0xFF991B1B),
      super(0xFFDC2626);
  final Color bolder;
}

class BTechStrokeSuccessColor extends Color {
  const BTechStrokeSuccessColor()
    : bolder = const Color(0xFF15803D),
      super(0xFF22C55E);
  final Color bolder;
}

class BTechStrokeWarningColor extends Color {
  const BTechStrokeWarningColor()
    : bolder = const Color(0xFFEA580C),
      super(0xFFFB923C);
  final Color bolder;
}

class BTechStrokeInfoColor extends Color {
  const BTechStrokeInfoColor()
    : bolder = const Color(0xFF1D4ED8),
      super(0xFF3B82F6);
  final Color bolder;
}

class BTechStrokeSecondaryColor extends Color {
  const BTechStrokeSecondaryColor()
    : bolder = const Color(0xFF7E22CE),
      super(0xFFA855F7);
  final Color bolder;
}

/// Semantic stroke color tokens.
/// Each property IS a [Color] directly; variants are sub-fields.
/// Example: BTechStrokeColor.neutral → Color
class BTechStrokeColor {
  const BTechStrokeColor()
    : neutral = const BTechStrokeNeutralColor(),
      primary = const BTechStrokePrimaryColor(),
      danger = const BTechStrokeDangerColor(),
      success = const BTechStrokeSuccessColor(),
      warning = const BTechStrokeWarningColor(),
      info = const BTechStrokeInfoColor(),
      secondary = const BTechStrokeSecondaryColor();
  final BTechStrokeNeutralColor neutral;
  final BTechStrokePrimaryColor primary;
  final BTechStrokeDangerColor danger;
  final BTechStrokeSuccessColor success;
  final BTechStrokeWarningColor warning;
  final BTechStrokeInfoColor info;
  final BTechStrokeSecondaryColor secondary;
}

