// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

/// Radius tokens. Access: BTechRadius.sm
abstract class BTechRadius {
  static const double s2xs = 2;
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 24;
  static const double s2xl = 32;
  static const double rd = 9999;
}

