// AUTO-GENERATED by @btech/design-system — do not edit manually.
import { defineConfig } from 'tsup';

export default defineConfig({
  entry:    ['src/index.ts'],
  format:   ['cjs', 'esm'],
  dts:      true,
  clean:    false,
  // styles.css lives in dist/ already (written by the token generator);
  // marking it external preserves the side-effect import in the output.
  external: [/\.css$/],
});
