# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run `pnpm generate` to regenerate from packages/tokens/sources/.

from __future__ import annotations



class BTechShadow:
    """Static dot-access to all resolved shadow tokens."""
