# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run `pnpm generate` to regenerate from packages/tokens/sources/.

from __future__ import annotations


class BTechSpacing:
    """Static dot-access to resolved spacing tokens (int px values)."""
    xs: int = 4
    sm: int = 8
    md: int = 16
    lg: int = 24
    xl: int = 32
    xl2: int = 40
    xl3: int = 48
    xl4: int = 64
