# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run `pnpm generate` to regenerate from packages/tokens/sources/.

from __future__ import annotations


class BTechSpacing:
    """Static dot-access to resolved spacing tokens (int px values)."""
    s2xs: int = 2
    xs: int = 4
    sm: int = 8
    md: int = 12
    lg: int = 16
    xl: int = 24
    s2xl: int = 32
    s3xl: int = 48
