# AUTO-GENERATED by @btech/design-system — do not edit manually.
# Run `pnpm generate` to regenerate from packages/tokens/sources/.

from __future__ import annotations


class _BTechFontFamily:
    """Resolved font-family strings."""
    sans: str = "Inter, system-ui, -apple-system, sans-serif"
    mono: str = "'JetBrains Mono', 'Fira Code', monospace"


class _BTechTypeScaleEntry:
    def __init__(self, font_size: float, font_weight: int, line_height: float):
        self.font_size = font_size
        self.font_weight = font_weight
        self.line_height = line_height
    def __repr__(self) -> str:
        return f"TypeScale(fs={self.font_size}, fw={self.font_weight}, lh={self.line_height})"


class _BTechTypeScaleHeading:
    """heading type-scale entries."""
    h1: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=35, font_weight=700, line_height=40)
    h2: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=29, font_weight=600, line_height=32)
    h3: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=24, font_weight=700, line_height=28)
    h4: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=20, font_weight=500, line_height=24)


class _BTechTypeScaleSubheading:
    """subheading type-scale entries."""
    h5: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=16, font_weight=700, line_height=20)
    h6: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=14, font_weight=600, line_height=16)
    h7: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=600, line_height=16)


class _BTechTypeScaleBody:
    """body type-scale entries."""
    base: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=500, line_height=16)
    bold: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=700, line_height=16)
    small: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=11, font_weight=500, line_height=16)
    medium: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=14, font_weight=500, line_height=18)
    xstraSmall: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=8, font_weight=500, line_height=12)
    italic: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=500, line_height=16)
    underline: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=600, line_height=16)
    paragraph: _BTechTypeScaleEntry = _BTechTypeScaleEntry(font_size=12, font_weight=500, line_height=24)


class BTechTypography:
    """Static dot-access to all resolved typography tokens."""
    family: _BTechFontFamily = _BTechFontFamily()
    heading: _BTechTypeScaleHeading = _BTechTypeScaleHeading()
    subheading: _BTechTypeScaleSubheading = _BTechTypeScaleSubheading()
    body: _BTechTypeScaleBody = _BTechTypeScaleBody()
