// AUTO-GENERATED by @ramams06/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Primitive color tokens (Tier 1) — never consume in components directly.
abstract class DsPrimitiveColors {
  static const colorBlue50 = Color(0xFFEFF6FF);
  static const colorBlue100 = Color(0xFFDBEAFE);
  static const colorBlue200 = Color(0xFFBFDBFE);
  static const colorBlue300 = Color(0xFF93C5FD);
  static const colorBlue400 = Color(0xFF60A5FA);
  static const colorBlue500 = Color(0xFF3B82F6);
  static const colorBlue600 = Color(0xFF2563EB);
  static const colorBlue700 = Color(0xFF1D4ED8);
  static const colorBlue800 = Color(0xFF1E40AF);
  static const colorBlue900 = Color(0xFF1E3A8A);
  static const colorGreen50 = Color(0xFFF0FDF4);
  static const colorGreen100 = Color(0xFFDCFCE7);
  static const colorGreen200 = Color(0xFFBBF7D0);
  static const colorGreen300 = Color(0xFF86EFAC);
  static const colorGreen400 = Color(0xFF4ADE80);
  static const colorGreen500 = Color(0xFF22C55E);
  static const colorGreen600 = Color(0xFF16A34A);
  static const colorGreen700 = Color(0xFF15803D);
  static const colorGreen800 = Color(0xFF166534);
  static const colorGreen900 = Color(0xFF14532D);
  static const colorOrange50 = Color(0xFFFFF7ED);
  static const colorOrange100 = Color(0xFFFFEDD5);
  static const colorOrange200 = Color(0xFFFED7AA);
  static const colorOrange300 = Color(0xFFFDBA74);
  static const colorOrange400 = Color(0xFFFB923C);
  static const colorOrange500 = Color(0xFFF97316);
  static const colorOrange600 = Color(0xFFEA580C);
  static const colorOrange700 = Color(0xFFC2410C);
  static const colorOrange800 = Color(0xFF9A3412);
  static const colorOrange900 = Color(0xFF7C2D12);
  static const colorRed500 = Color(0xFFEF4444);
  static const colorRed600 = Color(0xFFDC2626);
  static const colorRed700 = Color(0xFFB91C1C);
  static const colorNeutral0 = Color(0xFFFFFFFF);
  static const colorNeutral50 = Color(0xFFF9FAFB);
  static const colorNeutral100 = Color(0xFFF3F4F6);
  static const colorNeutral200 = Color(0xFFE5E7EB);
  static const colorNeutral300 = Color(0xFFD1D5DB);
  static const colorNeutral400 = Color(0xFF9CA3AF);
  static const colorNeutral500 = Color(0xFF6B7280);
  static const colorNeutral600 = Color(0xFF4B5563);
  static const colorNeutral700 = Color(0xFF374151);
  static const colorNeutral800 = Color(0xFF1F2937);
  static const colorNeutral900 = Color(0xFF111827);
  static const colorNeutral1000 = Color(0xFF000000);
}

/// Primitive spacing / dimension tokens (Tier 1).
abstract class DsPrimitiveDimensions {
  static const double radiusNone = 0;
  static const double radiusSm = 2;
  static const double radiusMd = 8;
  static const double radiusLg = 14;
  static const double radiusXl = 20;
  static const double radiusFull = 9999;
  static const double spacingScale1 = 4;
  static const double spacingScale2 = 8;
  static const double spacingScale3 = 12;
  static const double spacingScale4 = 16;
  static const double spacingScale5 = 20;
  static const double spacingScale6 = 24;
  static const double spacingScale8 = 32;
  static const double spacingScale10 = 40;
  static const double spacingScale12 = 48;
  static const double spacingScale16 = 64;
  static const double typographyFontSizeXs = 12;
  static const double typographyFontSizeSm = 14;
  static const double typographyFontSizeBase = 16;
  static const double typographyFontSizeLg = 18;
  static const double typographyFontSizeXl = 20;
  static const double typographyFontSize2xl = 24;
  static const double typographyFontSize3xl = 30;
  static const double typographyFontSize4xl = 36;
  static const double typographyLetterSpacingTight = -0.025;
  static const double typographyLetterSpacingNormal = 0;
  static const double typographyLetterSpacingWide = 0.025;
}

/// Primitive font-weight tokens (Tier 1).
abstract class DsPrimitiveFontWeights {
  static const FontWeight typographyFontWeightRegular = FontWeight.w400;
  static const FontWeight typographyFontWeightMedium = FontWeight.w500;
  static const FontWeight typographyFontWeightSemibold = FontWeight.w600;
  static const FontWeight typographyFontWeightBold = FontWeight.w700;
}

/// Primitive font-family tokens (Tier 1).
abstract class DsPrimitiveFontFamilies {
  static const String typographyFontFamilySans = 'Inter';
  static const String typographyFontFamilyMono = 'JetBrains Mono';
}

/// Semantic color tokens (Tier 2) — default tenant values.
abstract class DsSemanticColors {
  static const colorPrimaryBg = Color(0xFF15803D);
  static const colorPrimaryBg_hover = Color(0xFF166534);
  static const colorPrimaryFg = Color(0xFFFFFFFF);
  static const colorPrimaryBorder = Color(0xFF166534);
  static const colorSecondaryBg = Color(0xFFF3F4F6);
  static const colorSecondaryBg_hover = Color(0xFFE5E7EB);
  static const colorSecondaryFg = Color(0xFF1F2937);
  static const colorSecondaryBorder = Color(0xFFD1D5DB);
  static const colorDangerBg = Color(0xFFB91C1C);
  static const colorDangerBg_hover = Color(0xFFB91C1C);
  static const colorDangerFg = Color(0xFFFFFFFF);
  static const colorDangerBorder = Color(0xFFB91C1C);
  static const colorSuccessBg = Color(0xFF22C55E);
  static const colorSuccessFg = Color(0xFFFFFFFF);
  static const colorWarningBg = Color(0xFFF97316);
  static const colorWarningFg = Color(0xFFFFFFFF);
  static const colorSurfaceDefault = Color(0xFFFFFFFF);
  static const colorSurfaceSubtle = Color(0xFFF9FAFB);
  static const colorSurfaceRaised = Color(0xFFF3F4F6);
  static const colorTextDefault = Color(0xFF111827);
  static const colorTextSubtle = Color(0xFF6B7280);
  static const colorTextDisabled = Color(0xFF9CA3AF);
  static const colorTextInverse = Color(0xFFFFFFFF);
  static const colorBorderDefault = Color(0xFFE5E7EB);
  static const colorBorderStrong = Color(0xFF9CA3AF);
  static const buttonPrimaryBg = Color(0xFF15803D);
  static const buttonPrimaryBg_hover = Color(0xFF166534);
  static const buttonPrimaryFg = Color(0xFFFFFFFF);
  static const buttonPrimaryBorder = Color(0xFF166534);
  static const buttonSecondaryBg = Color(0xFFF3F4F6);
  static const buttonSecondaryBg_hover = Color(0xFFE5E7EB);
  static const buttonSecondaryFg = Color(0xFF1F2937);
  static const buttonSecondaryBorder = Color(0xFFD1D5DB);
  static const buttonDangerBg = Color(0xFFB91C1C);
  static const buttonDangerBg_hover = Color(0xFFB91C1C);
  static const buttonDangerFg = Color(0xFFFFFFFF);
  static const buttonDangerBorder = Color(0xFFB91C1C);
}

/// Semantic radius tokens (Tier 2).
abstract class DsSemanticRadius {
  static const double radiusInteractive = 8;
  static const double radiusCard = 14;
  static const double radiusBadge = 9999;
  static const double radiusTooltip = 2;
  static const double typographyBodyFontSize = 16;
  static const double typographyLabelFontSize = 14;
  static const double typographyCodeFontSize = 14;
  static const double buttonPrimaryRadius = 8;
  static const double buttonSecondaryRadius = 8;
  static const double buttonDangerRadius = 8;
  static const double buttonSizeSmPaddingX = 12;
  static const double buttonSizeSmPaddingY = 4;
  static const double buttonSizeSmFontSize = 14;
  static const double buttonSizeMdPaddingX = 16;
  static const double buttonSizeMdPaddingY = 8;
  static const double buttonSizeMdFontSize = 16;
  static const double buttonSizeLgPaddingX = 24;
  static const double buttonSizeLgPaddingY = 12;
  static const double buttonSizeLgFontSize = 18;
}

/// Semantic font-family tokens (Tier 2).
abstract class DsSemanticFontFamilies {
  static const String typographyBodyFontFamily = 'Inter';
  static const String typographyLabelFontFamily = 'Inter';
  static const String typographyHeadingFontFamily = 'Inter';
  static const String typographyCodeFontFamily = 'JetBrains Mono';
}

