// AUTO-GENERATED by @btech/design-tokens — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

// ── Primitive color palette ──────────────────────────────────────────────────
class _BTechPrimColorBlue {
  const _BTechPrimColorBlue()
    : s50 = const Color(0xFFEFF6FF),
      s100 = const Color(0xFFDBEAFE),
      s200 = const Color(0xFFBFDBFE),
      s300 = const Color(0xFF93C5FD),
      s400 = const Color(0xFF60A5FA),
      s500 = const Color(0xFF3B82F6),
      s600 = const Color(0xFF2563EB),
      s700 = const Color(0xFF1D4ED8),
      s800 = const Color(0xFF1E40AF),
      s900 = const Color(0xFF1E3A8A);
  final Color s50;
  final Color s100;
  final Color s200;
  final Color s300;
  final Color s400;
  final Color s500;
  final Color s600;
  final Color s700;
  final Color s800;
  final Color s900;
}

class _BTechPrimColorGreen {
  const _BTechPrimColorGreen()
    : s50 = const Color(0xFFF0FDF4),
      s100 = const Color(0xFFDCFCE7),
      s200 = const Color(0xFFBBF7D0),
      s300 = const Color(0xFF86EFAC),
      s400 = const Color(0xFF4ADE80),
      s500 = const Color(0xFF22C55E),
      s600 = const Color(0xFF16A34A),
      s700 = const Color(0xFF15803D),
      s800 = const Color(0xFF166534),
      s900 = const Color(0xFF14532D);
  final Color s50;
  final Color s100;
  final Color s200;
  final Color s300;
  final Color s400;
  final Color s500;
  final Color s600;
  final Color s700;
  final Color s800;
  final Color s900;
}

class _BTechPrimColorOrange {
  const _BTechPrimColorOrange()
    : s50 = const Color(0xFFFFF7ED),
      s100 = const Color(0xFFFFEDD5),
      s200 = const Color(0xFFFED7AA),
      s300 = const Color(0xFFFDBA74),
      s400 = const Color(0xFFFB923C),
      s500 = const Color(0xFFF97316),
      s600 = const Color(0xFFEA580C),
      s700 = const Color(0xFFC2410C),
      s800 = const Color(0xFF9A3412),
      s900 = const Color(0xFF7C2D12);
  final Color s50;
  final Color s100;
  final Color s200;
  final Color s300;
  final Color s400;
  final Color s500;
  final Color s600;
  final Color s700;
  final Color s800;
  final Color s900;
}

class _BTechPrimColorRed {
  const _BTechPrimColorRed()
    : s500 = const Color(0xFFEF4444),
      s600 = const Color(0xFFDC2626),
      s700 = const Color(0xFFB91C1C);
  final Color s500;
  final Color s600;
  final Color s700;
}

class _BTechPrimColorNeutral {
  const _BTechPrimColorNeutral()
    : s0 = const Color(0xFFFFFFFF),
      s50 = const Color(0xFFF9FAFB),
      s100 = const Color(0xFFF3F4F6),
      s200 = const Color(0xFFE5E7EB),
      s300 = const Color(0xFFD1D5DB),
      s400 = const Color(0xFF9CA3AF),
      s500 = const Color(0xFF6B7280),
      s600 = const Color(0xFF4B5563),
      s700 = const Color(0xFF374151),
      s800 = const Color(0xFF1F2937),
      s900 = const Color(0xFF111827),
      s1000 = const Color(0xFF000000);
  final Color s0;
  final Color s50;
  final Color s100;
  final Color s200;
  final Color s300;
  final Color s400;
  final Color s500;
  final Color s600;
  final Color s700;
  final Color s800;
  final Color s900;
  final Color s1000;
}

abstract class BTechPrimitiveColor {
  static const blue = _BTechPrimColorBlue();
  static const green = _BTechPrimColorGreen();
  static const orange = _BTechPrimColorOrange();
  static const red = _BTechPrimColorRed();
  static const neutral = _BTechPrimColorNeutral();
}

// ── Primitive spacing ────────────────────────────────────────────────────────
abstract class BTechSpacing {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
  static const double xl2 = 40;
  static const double xl3 = 48;
  static const double xl4 = 64;
}

// ── Primitive radius ─────────────────────────────────────────────────────────
abstract class BTechRadius {
  static const double none = 0;
  static const double sm = 2;
  static const double md = 8;
  static const double lg = 14;
  static const double xl = 20;
  static const double full = 9999;
}

// ── Primitive font weights ───────────────────────────────────────────────────
abstract class BTechFontWeight {
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight semibold = FontWeight.w600;
  static const FontWeight bold = FontWeight.w700;
}

// ── Primitive font families ──────────────────────────────────────────────────
abstract class BTechFontFamily {
  static const String sans = 'Inter';
  static const String mono = 'JetBrains Mono';
}

// ── Primitive font sizes ─────────────────────────────────────────────────────
abstract class BTechFontSize {
  static const double xs = 12;
  static const double sm = 14;
  static const double base = 16;
  static const double lg = 18;
  static const double xl = 20;
  static const double s2xl = 24;
  static const double s3xl = 30;
  static const double s4xl = 36;
}

// ── Primitive line heights ────────────────────────────────────────────────────
abstract class BTechLineHeight {
  static const double tight = 1.25;
  static const double normal = 1.5;
  static const double relaxed = 1.75;
}

// ── Semantic color — text group ──────────────────────────────────────────────
class _BTechColorText {
  const _BTechColorText();
  final Color primary = const Color(0xFF111827);
  final Color secondary = const Color(0xFF6B7280);
  final Color disable = const Color(0xFF9CA3AF);
  final Color inverse = const Color(0xFFFFFFFF);
  final Color onPrimary = const Color(0xFFFFFFFF);
  final Color onSecondary = const Color(0xFF1F2937);
  final Color onDanger = const Color(0xFFFFFFFF);
}

// ── Semantic color — background group ──────────────────────────────────────────────
class _BTechColorBackground {
  const _BTechColorBackground();
  final Color defaultBg = const Color(0xFFFFFFFF);
  final Color subtle = const Color(0xFFF9FAFB);
  final Color raised = const Color(0xFFF3F4F6);
  final Color primary = const Color(0xFF15803D);
  final Color primaryHover = const Color(0xFF166534);
  final Color secondary = const Color(0xFFF3F4F6);
  final Color secondaryHover = const Color(0xFFE5E7EB);
  final Color danger = const Color(0xFFB91C1C);
  final Color dangerHover = const Color(0xFFB91C1C);
  final Color success = const Color(0xFF22C55E);
  final Color warning = const Color(0xFFF97316);
}

// ── Semantic color — stroke group ──────────────────────────────────────────────
class _BTechColorStroke {
  const _BTechColorStroke();
  final Color defaultStroke = const Color(0xFFE5E7EB);
  final Color strong = const Color(0xFF9CA3AF);
  final Color primary = const Color(0xFF166534);
  final Color secondary = const Color(0xFFD1D5DB);
  final Color danger = const Color(0xFFB91C1C);
}

/// Semantic color tokens — use context.btechColor for tenant-aware access.
/// BTechColor.background.primary is always the DEFAULT tenant value.
abstract class BTechColor {
  static const text = _BTechColorText();
  static const background = _BTechColorBackground();
  static const stroke = _BTechColorStroke();
}

// ── Semantic radius ──────────────────────────────────────────────────────────
abstract class BTechSemanticRadius {
  static const double interactive = 8;
  static const double card = 14;
  static const double badge = 9999;
  static const double tooltip = 2;
}

// ── Semantic font families ────────────────────────────────────────────────────
abstract class BTechSemanticFontFamily {
  static const String body = 'Inter';
  static const String label = 'Inter';
  static const String heading = 'Inter';
  static const String code = 'JetBrains Mono';
}

// ── Semantic font sizes ───────────────────────────────────────────────────────
abstract class BTechSemanticFontSize {
  static const double body = 16;
  static const double label = 14;
  static const double code = 14;
}

// ── Button component tokens ──────────────────────────────────────────────────
abstract class BTechButtonColors {
  static const primaryBg = Color(0xFF15803D);
  static const primaryBgHover = Color(0xFF166534);
  static const primaryFg = Color(0xFFFFFFFF);
  static const primaryBorder = Color(0xFF166534);
  static const secondaryBg = Color(0xFFF3F4F6);
  static const secondaryBgHover = Color(0xFFE5E7EB);
  static const secondaryFg = Color(0xFF1F2937);
  static const secondaryBorder = Color(0xFFD1D5DB);
  static const dangerBg = Color(0xFFB91C1C);
  static const dangerBgHover = Color(0xFFB91C1C);
  static const dangerFg = Color(0xFFFFFFFF);
  static const dangerBorder = Color(0xFFB91C1C);
}

abstract class BTechButtonDimensions {
  static const double primaryRadius = 8;
  static const double secondaryRadius = 8;
  static const double dangerRadius = 8;
  static const double sizeSmPaddingX = 8;
  static const double sizeSmPaddingY = 4;
  static const double sizeSmFontSize = 14;
  static const double sizeMdPaddingX = 16;
  static const double sizeMdPaddingY = 8;
  static const double sizeMdFontSize = 16;
  static const double sizeLgPaddingX = 24;
  static const double sizeLgPaddingY = 8;
  static const double sizeLgFontSize = 18;
}

