// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Source: packages/tokens/sources/tenants/default/overrides.json
// Run `pnpm generate` to regenerate.

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';
import '../tenant.dart';

/// Default tenant.
/// Auto-generated from sources/tenants/default/overrides.json
const BTechTenantTokens btechTenantDefault = BTechTenantTokens(
  colorBackgroundSurface: const Color(0xFFF9FAFB),
  colorBackgroundSurfaceSubtle: const Color(0xFFF3F4F6),
  colorBackgroundSurfaceRaised: const Color(0xFFFFFFFF),
  colorBackgroundPrimary: const Color(0xFF15803D),
  colorBackgroundPrimaryHover: const Color(0xFF166534),
  colorBackgroundPrimaryPressed: const Color(0xFF14532D),
  colorBackgroundPrimaryDisable: const Color(0xFFE5E7EB),
  colorBackgroundPrimarySubtle: const Color(0xFFF0FDF4),
  colorBackgroundSecondary: const Color(0xFFF0FDF4),
  colorBackgroundSecondaryHover: const Color(0xFFDCFCE7),
  colorBackgroundSecondaryPressed: const Color(0xFFBBF7D0),
  colorBackgroundSecondaryDisable: const Color(0xFFF3F4F6),
  colorBackgroundSecondarySubtle: const Color(0xFFF9FAFB),
  colorBackgroundDanger: const Color(0xFFDC2626),
  colorBackgroundDangerHover: const Color(0xFFB91C1C),
  colorBackgroundDangerPressed: const Color(0xFF991B1B),
  colorBackgroundDangerDisable: const Color(0xFFE5E7EB),
  colorBackgroundDangerSubtle: const Color(0xFFFEF2F2),
  colorBackgroundSuccess: const Color(0xFF22C55E),
  colorBackgroundSuccessSubtle: const Color(0xFFF0FDF4),
  colorBackgroundWarning: const Color(0xFFFB923C),
  colorBackgroundWarningSubtle: const Color(0xFFFFF7ED),
  colorBackgroundInfo: const Color(0xFF2563EB),
  colorBackgroundInfoSubtle: const Color(0xFFEFF6FF),
  colorBackgroundNeutral: const Color(0xFFF3F4F6),
  colorBackgroundNeutralSubtle: const Color(0xFFF9FAFB),
  colorTextNeutral: const Color(0xFF111827),
  colorTextNeutralSubtle: const Color(0xFF6B7280),
  colorTextNeutralDisabled: const Color(0xFFD1D5DB),
  colorTextNeutralInverse: const Color(0xFFF9FAFB),
  colorTextOnPrimary: const Color(0xFF000000),
  colorTextOnSecondary: const Color(0xFF000000),
  colorTextOnDanger: const Color(0xFF000000),
  colorTextOnInfo: const Color(0xFF000000),
  colorIconNeutral: const Color(0xFF374151),
  colorIconNeutralSubtle: const Color(0xFF9CA3AF),
  colorIconNeutralDisabled: const Color(0xFFD1D5DB),
  colorIconNeutralInverse: const Color(0xFFFFFFFF),
  colorIconOnPrimary: const Color(0xFF000000),
  colorIconOnDanger: const Color(0xFF000000),
  colorStrokeNeutral: const Color(0xFFE5E7EB),
  colorStrokeNeutralStrong: const Color(0xFF9CA3AF),
  colorStrokeNeutralSubtle: const Color(0xFFF3F4F6),
  colorStrokePrimary: const Color(0xFF15803D),
  colorStrokePrimaryBolder: const Color(0xFF14532D),
  colorStrokeDanger: const Color(0xFFDC2626),
  radiusInteractive: 8,
  radiusCard: 14,
  radiusBadge: 9999,
  typographyFontFamilySans: 'Inter',
);
