// AUTO-GENERATED by @btech/design-system — do not edit manually.
// Run `pnpm generate` to regenerate from tokens/.

// ignore_for_file: lines_longer_than_80_chars

import 'text.color.dart';
import 'icon.color.dart';
import 'background.color.dart';
import 'stroke.color.dart';
import 'shades.color.dart';

/// Semantic color tokens — use context.btechColor for tenant-aware access.
///   BTechColor.text.neutral           → Color (#111827)
///   BTechColor.text.neutral.subtle    → Color (#6B7280)
///   BTechColor.icon.neutral           → Color (#374151)
///   BTechColor.background.primary     → Color (#15803D)
///   BTechColor.stroke.neutral         → Color (#E5E7EB)
///   BTechColor.shades.green[500]      → Color (#22C55E)
abstract class BTechColor {
  static const BTechTextColor       text       = BTechTextColor();
  static const BTechIconColor       icon       = BTechIconColor();
  static const BTechBackgroundColor background = BTechBackgroundColor();
  static const BTechStrokeColor     stroke     = BTechStrokeColor();
  static const BTechShadesColor     shades     = BTechShadesColor();
}

